# <a id='toc1_'></a>[DGIdb ambiguous claims](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- [DGIdb ambiguous claims](#toc1_)    
    - [Analyzing similaritis b/w alias-primary and alias-alias collisions](#toc1_1_1_)    
      - [Load merged alias-alias and alias-priamry collision sets. Symbols are the ambiguous symbols.](#toc1_1_1_1_)    
      - [How many of the alias-primary collisions are also alias-alias collisions?](#toc1_1_1_2_)    
      - [How many unique ambiguous symbosl are there b/w alias-primary and alias-alias collisions?](#toc1_1_1_3_)    
    - [Primary exploration of DGIdb gene content using collisions](#toc1_1_2_)    
      - [Load gene claim data from DGIdb](#toc1_1_2_1_)    
      - [How many claims are placed in a gene group with a different label?](#toc1_1_2_2_)    
      - [How many claims are not normalized?](#toc1_1_2_3_)    
      - [Create set of gene groups (gene_name) and gene claims (gene_claim_name)](#toc1_1_2_4_)    
      - [Load HGNC, Ensembl (ENSG), and NCBI gene and alias sets](#toc1_1_2_5_)    
      - [How many unique primary gene symbols are there b/w HGNC, Ensembl, and NCBI?](#toc1_1_2_6_)    
      - [How many unique alias symbols are there b/w HGNC, Ensembl, and NCBI?](#toc1_1_2_7_)    
      - [How many unique group names are not primary gene symbols?](#toc1_1_2_8_)    
      - [How many unique claims are not primary gene symbols?](#toc1_1_2_9_)    
      - [Load the collision sets from each data source](#toc1_1_2_10_)    
      - [How many unique group names are primary gene symbols?](#toc1_1_2_11_)    
      - [How many of the groups that are labeled with a primary gene symbol are also alias-alias collisions?](#toc1_1_2_12_)    
      - [How many unique claim symbols are collisions?](#toc1_1_2_13_)    
      - [How many unique groups are labeled with collisions?](#toc1_1_2_14_)    
      - [How many unique claims are not primary gene symbols?](#toc1_1_2_15_)    
      - [How many unique claims that were not primary symbols are collisions?](#toc1_1_2_16_)    
      - [How many unique claims that are primary gene symbols are also collisions?](#toc1_1_2_17_)    
      - [How many of the gene groups that are not primary gene symbols are alias-alias collisions from HGNC?](#toc1_1_2_18_)    
      - [How many claims are ambiguous symbols?](#toc1_1_2_19_)    
      - [How many gene group labels are ambiguous symbols?](#toc1_1_2_20_)    
      - [How many claims are primary symbols?](#toc1_1_2_21_)    
      - [How many gene group labels are primary symbols?](#toc1_1_2_22_)    
      - [How many gene group labels are alias symbols?](#toc1_1_2_23_)    
      - [How many claims are alias symbols?](#toc1_1_2_24_)    
      - [How many claims that were normalized into non-primary symbol labeled groups are alias symbols?](#toc1_1_2_25_)    
      - [How many not normalized claims are alias symbols?](#toc1_1_2_26_)    
      - [How many gene group labels are not primary, alias symbols, or null?](#toc1_1_2_27_)    
      - [How many claims are not primary, alias symbols, or null?](#toc1_1_2_28_)    
      - [How many claims are primary and alias symbols?](#toc1_1_2_29_)    
      - [How many primary symbol claims are normalized into non-primary gene group labels?](#toc1_1_2_30_)    
    - [Summary](#toc1_1_3_)    
      - [Normalization Rates](#toc1_1_3_1_)    
      - [Types of Claim Symbols](#toc1_1_3_2_)    
      - [Types of Normalizations (gene group labels claims are being normliazed into)](#toc1_1_3_3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

### <a id='toc1_1_1_'></a>[Analyzing similarities b/w alias-primary and alias-alias collisions](#toc0_)

#### <a id='toc1_1_1_1_'></a>[Load merged alias-alias and alias-priamry collision sets. Symbols are the ambiguous symbols.](#toc0_)

Input: merged_alias_gene_intersections.csv (total_alias_gene_intersections.ipynb), merged_alias_overlap_df_2.csv (total_alias_overlap.ipynb)

Output: merged_alias_primary_collision_set, merged_alias_alias_collision_set

In [2]:
merged_alias_primary_collisions_df = pd.read_csv(
    "../output/merged_alias_primary_collisions_df.csv", na_values=["", "NULL"], keep_default_na=False
)

In [3]:
merged_alias_primary_collision_set = set(
    merged_alias_primary_collisions_df["collision"]
)
len(merged_alias_primary_collision_set)

1444

In [4]:
merged_alias_alias_collisions_df = pd.read_csv(
    "../output/merged_aa_collision_alias_df.csv", na_values=["", "NULL"], keep_default_na=False
)

In [5]:
merged_alias_alias_collision_set = set(
    merged_alias_alias_collisions_df["collision"].tolist()
)
len(merged_alias_alias_collision_set)

3809

In [6]:
merged_alias_alias_collision_list = merged_alias_alias_collisions_df["collision"].tolist()

In [7]:
merged_alias_alias_collision_list[1]

'H4-16'

#### <a id='toc1_1_1_2_'></a>[How many of the alias-primary collisions are also alias-alias collisions?](#toc0_)

In [8]:
print(
    len(
        merged_alias_alias_collision_set.intersection(
            merged_alias_primary_collision_set
        )
    )
)

184

#### <a id='toc1_1_1_3_'></a>[How many unique ambiguous symbols are there b/w alias-primary and alias-alias collisions?](#toc0_)

In [9]:
ambiguous_symbol_set = merged_alias_alias_collision_set.union(
    merged_alias_primary_collision_set
)
print(len(ambiguous_symbol_set))

5069

In [10]:
ambiguous_symbol_set

{'LAGE2B',
 'DLG3',
 'CD85',
 'SH2B',
 'J3',
 'NP2',
 'NARF',
 'C17DUPP13.3',
 'C7ORF55',
 'ASP',
 'ZFP91',
 'D4',
 'MBD2',
 'PRR3',
 'SCHAD',
 'RAB1C',
 'SPB1',
 'S8',
 'CDH7',
 'BCOX',
 'HDAC7',
 'XPE',
 'MGC22679',
 'TIRAP3',
 'UFD2',
 'PTX3',
 'CTHM',
 'MRX2',
 'AAA',
 'TRF-GAA1-4',
 'PBS',
 'LINC02696',
 'FCRI',
 'LAMP',
 'STX17-DT',
 'ACN',
 'RNU1-8P',
 'LINC02224',
 'PRC17',
 'TEM',
 'TE2',
 'KIAA1426',
 'FCERI',
 'OR11-55',
 'C5A',
 'AMAP1',
 'MRP-S28',
 'PIF',
 'TRE',
 'SRA1',
 'CFD1',
 'SLC16A4-AS1',
 'RNU6-373P',
 'SNRPD1',
 'BAP-1',
 'OI4',
 'SYN1A',
 'NDR',
 'PSEUDO-ICE',
 'HIES2',
 'IMP-3',
 'LMO7B',
 'MSP',
 'TVP23C',
 'TTD',
 'MRLC2',
 'KNO2',
 'RRP4',
 'RGR',
 'SPK',
 'ZAC1',
 'GIG1',
 'LINC00846',
 'KCNJN1',
 'CFAG',
 'HZF',
 'CT45-5',
 'LINC01799',
 'ATS2',
 'H4C4',
 'HMN5',
 'G6PD',
 'EDHB17',
 'MPD6',
 'SIGLECP1',
 'PHEX-AS1',
 'CAPG',
 'HSP70-2',
 'NRP',
 'NSE2',
 'TCI',
 'ART',
 'TRP1',
 'SEF',
 'OFD1P2',
 'AMD1',
 'HH13',
 'ZNF769',
 'LINC02302',
 'PKR2',
 'CT45-2',
 'LIMS3L',
 'OFD1P1',
 'ASB3',
 'STSL',
 'CT45A2',
 'LY-75',
 'PMP22',
 'AH',
 'STAG3L3',
 'P52',
 'MIA1',
 'D3',
 'CPX2',
 'H2BC4',
 'CYP2B7',
 'CKB',
 'HRS',
 'FRP-2',
 'RDS',
 'CST6',
 'BRPF1',
 'KAP-1',
 'EVR1',
 'CED4',
 'BRAP',
 'C6ORF126',
 'TARG1',
 'TCEA1',
 'TRH-GTG1-9',
 'MCAP',
 'PRKAR1',
 'AML1-EVI-1',
 'NAG',
 'GT',
 'H2B/K',
 'ATP2B2',
 'SEMAL',
 'A3',
 'SHMT',
 'NAT5',
 'NOC2',
 'NRK2',
 'MIFR-1',
 'RGS13',
 'MIR499A',
 'PTX1',
 'PP2CB',
 'PRK1',
 'MAP-1',
 'C1',
 'L23A',
 'ARB1',
 'GP',
 'CAB2',
 'MRPS28',
 'TRB2',
 'STP',
 'IPP1',
 'TLN',
 'KRTAP5-8',
 'LAMR',
 'SDH1',
 'P57',
 'GCP-2',
 'KAL',
 'TC4',
 'RPL7P',
 'RZF',
 'ANCR',
 'FPRH1',
 'APPL2',
 'TSK4',
 'KIAA0266',
 'BNSP',
 'MIG-2',
 'LINC01995',
 'G13',
 'METTL2',
 'HSP70.1',
 'TAF',
 '35DAG',
 'FCCMS',
 'APOBEC1L',
 'XGPY',
 'CAPB',
 'WTS',
 'LSH',
 'AUTL1',
 'H2A.2',
 'CDK11-P110',
 'TYRRS',
 'GALNT13',
 'LIMS4',
 'REX1',
 'HGRG8',
 'CEBPZ',
 'SCP-2',
 'MENA',
 'RPS27AP',
 'ABC1',
 'MDSP',
 'FPRH2',
 'KRTAP5-11',
 'DP3',
 'ARP',
 'COX4',
 'BAL',
 'RPA1',
 'ILT5',
 'AGS2',
 'PRX2',
 'CDKN1A',
 'GOLGA5',
 'DAND1',
 'RPP20',
 'ABP',
 'FKBP51',
 'RPL36A',
 'FIB2',
 'FALDH',
 'PGD2',
 'P50',
 'HCGB',
 'TRNAG-CCC',
 'C15ORF38',
 'CD277',
 '7SK',
 'HCCR-2',
 'ICBP90',
 'EAF2',
 'LGS',
 'MRX31',
 'PCDH11Y',
 'MORF4LP4',
 'GP150',
 'TAX1BP2',
 'ZIP2',
 'ZNF468',
 'CLA20',
 'HD6',
 'PIG1',
 'HP-1',
 'AQP1',
 'PORC',
 'TFIIIB90',
 'ACTB',
 'CTR1',
 'LGL1',
 'ETDA',
 'TRAP1',
 'DAN',
 'FAM236D',
 'GT1',
 'FAM90A2P',
 'AM',
 'HBG1',
 'PRPS1',
 'MAML2',
 'MMDS3',
 'S100A16',
 'IFNA13',
 'CDC14B2',
 'HIST1H2BF',
 'P58',
 'INT4',
 'AD1',
 'PAPT',
 'BOS1',
 'CSN3',
 'RSS',
 'RIP5',
 'SGN1',
 'EIF4F',
 'PTB',
 'ERG3',
 'FBXO30',
 'LGALS7',
 'TRK',
 'TRA-TGC3-2',
 'TRIM49B',
 'BB2',
 'MRX15',
 'LST-3TM12',
 'ADAMTS-2',
 'LOR',
 'P2RX5',
 'BR',
 'PRP-1/PRP-2',
 'HN1',
 'OSF-2',
 'MRXSH',
 'NBPF9',
 'RAX',
 'DRP1',
 'MSK16',
 'C11ORF5',
 'NPH2',
 'IL-1RA',
 'LRP4',
 'SCC1',
 'COMT2',
 'CEH',
 'PGII',
 'OTX3',
 'MIZ',
 'OCT-4',
 'TRP2',
 'ECGP',
 'PAK2',
 'CIR',
 'OR19-4',
 'KMS',
 'DBM',
 'CST',
 'CDD',
 'BST1',
 'CTP9',
 'TRS-GCT4-2',
 'TCF6L3',
 'LINC00516',
 'AIB3',
 'CRA',
 'EFA6R',
 'AGPAT8',
 'NGB',
 'CTSO1',
 'MM1',
 'CMS1D',
 'LRRC37',
 'MCS',
 'GPI',
 'HOP',
 'SSS1',
 'NRP2',
 'DNM1DN3@',
 'GNAO1-AS1',
 'SLP4',
 'OBTP',
 'LNP1',
 'HPH-3',
 'TSPY10',
 'OR19-5',
 'NAF1',
 'ASP1',
 'TIP',
 'BIS',
 'L15MT',
 'GDIL',
 'QPC',
 'SPH2',
 'LPC1',
 'NPYR',
 'CEP2',
 'ABP-280',
 'TBC1D3C',
 'PROTEASE',
 'MED',
 'HAST3',
 'MAD3',
 'TTF-1',
 'VPS24',
 'CBLC',
 'IMP',
 'MRS',
 'ATR',
 'NOD5',
 'FJHN',
 'CSN2',
 'CL1',
 'NEM1',
 'NAT6',
 'H2BC10',
 'SKIP',
 'TTMA',
 'SH120',
 'MID1',
 'RK',
 'C13ORF25',
 'JP2',
 'CIT',
 'IFITMD8',
 'MRX99',
 'RIP',
 'TRI-AAT5-5',
 'D6S230E',
 'TRL-AAG2-3',
 'P37',
 'FAPP2',
 'PROTEINASE',
 'SGK2',
 'AR',
 'COD4',
 'TSG',
 'MIR8069',
 'SIP',
 'CLIC5',
 'TTG1',
 'RASA1',
 'SYT12',
 'AD3',
 'AGS1',
 'CEP68',
 'DIFF6',
 'OR1K1',
 'VDAC3',
 'DOC-1',
 'SPC1',
 'GOLGA8F',
 'PAGB',
 'NSP2',
 'DRP3',
 'PP2CE',
 'DFNB35',
 'ELN',
 'SPDYE4',
 'XDH',
 'DKFZP434B204',
 'ARP1',
 'CAHL',
 'SKP2',
 'CAT',
 'ZNT8',
 'UNQ192',
 'IGKV',
 'CDP',
 'HOX3',
 'AP2',
 'SPATA8',
 'SRC1',
 'HCCA2',
 'MAP2',
 'CORD5',
 'ALK1',
 'SAA1',
 'LINC02060',
 'MADD',
 'ZNF2',
 'GLP-1',
 'SWS1',
 '60B8AG',
 'PH',
 'DLEU2',
 'G6PT',
 'DGK',
 'SYN',
 'C6ST',
 'A20',
 'TSSK1',
 'CENPC',
 'CAC',
 'TCRBV21S1',
 'DIA',
 'REH',
 'FOXL3',
 'B3GN-T1',
 'OR19-8',
 'FRA10A',
 'CT5.2',
 'DEFB109',
 'VSD1',
 'NUDT4B',
 'PILRB',
 'CAP1',
 'ZNF408',
 'CAPH2',
 'SPANX-C',
 'TEN1',
 'KRTAP5-1',
 'CFL1',
 'KAP2.4',
 'FRA3B',
 'SUMO3',
 'I1',
 'FE',
 'ELK1',
 'GC',
 'NANOGP3',
 'SMUC',
 'MBP',
 'MBP-1',
 'EWSR2',
 'LACS2',
 'CK20',
 'FAME3',
 'C9ORF36',
 'LPAP',
 'FAH',
 'HYAL1',
 'ARG',
 'HYPP',
 'GEP',
 'PRPH',
 'TRNAV-CAC',
 'RIP-1',
 'UBP',
 'E4TF1',
 'DMC1',
 'PAP1',
 'H2AC13',
 'NET3',
 'TRR-CCG1-2',
 'U3B2',
 'EMAP-2',
 'TRMT1',
 'TADA1',
 'GUSBP9',
 'KRT6C',
 'KLK3',
 'KRTAP2-4',
 'CPSB',
 'SRGAP3',
 'PMI1',
 'ZRC1',
 'PDS',
 'PYPAF7',
 'LINC01017',
 'H2BFH',
 'CAMKIINALPHA',
 'CCNL1',
 'NET1',
 'P78',
 'CPN2',
 'NRP1',
 'RNU1P2',
 'MLT1',
 'PCM1',
 'H2BC7',
 'TCRAV13S1',
 'HMCS',
 'IBP',
 'EDH17B2',
 'OI6',
 'F2',
 'HD7',
 'P24',
 'CACNA1I',
 'DLP1',
 'MOP',
 'CHN',
 'TCRBV13S1',
 'NAPOR',
 'ACC',
 'AS',
 'ODF',
 'CMK',
 'C2',
 'HIST1H2BI',
 'DSEP',
 'HSP70-1',
 'POF',
 'APC4',
 'P600',
 'MRP-L14',
 'MED1',
 'PNMT',
 'RAM',
 'NIF',
 'SRP40',
 'DOR',
 'USP31',
 'C15ORF63',
 'BTRCP1',
 'US2',
 'UIP1',
 'TRAMP',
 'PP',
 'ACSM2',
 'CRD',
 'NET4',
 'CARMEN',
 'DD3',
 'TNX',
 'CT45-3',
 'AMY1',
 'HSTF1',
 'ZNF20',
 'CGB',
 'KPNA7',
 'FAM75D3',
 'SMP1',
 'CED12',
 'LPLAT',
 'MMP20',
 'P56',
 'SCP2',
 'RPT5',
 'RAI1',
 'CLEC2B',
 'LINC00086',
 'SMILE',
 'GALNT4',
 'TRG-GCC2-6',
 'FAM90A19P',
 'RIA1',
 'RU2',
 'JP',
 'KLHL6',
 'GJC1',
 'TTL',
 'ASC',
 'EIF4A',
 'HIP3',
 'NUS1',
 'ARC34',
 'RUFY3',
 'CT2',
 'DLK',
 'FY',
 'VDR',
 'FADS2',
 'MPI',
 'CMPD1',
 'H1RNA',
 'OAT6',
 'ALS2CR3',
 'SCKL4',
 'MGC15397',
 'LCN5',
 'BHLHE42',
 'RAK',
 'A15',
 'POMP',
 'TRX-CAT1-7',
 'TMSA',
 'PMS2P2',
 'TRL-AAG2-2',
 'ANT1',
 'NTE',
 'TUBB',
 'GAB1',
 'FIM1',
 'HK',
 'SIGLECP2',
 'APRO5',
 'TCRBV3S1',
 'LONP',
 'GE',
 'CHL',
 'FBP',
 'LHFPL4',
 'CD98',
 'MCDR2',
 'FH',
 'HCG1',
 'IFN-ALPHAI',
 'CYPL1',
 'LRP10',
 'LINC01167',
 'CREB2',
 'APS1',
 'KSP37',
 'IL8RA',
 'TERA',
 'DPPA3',
 'VAT1',
 'ANG2',
 'MFRP',
 'MADH7',
 'GCP',
 'PAR-6',
 'MASK',
 'HSD3B',
 'MSH',
 'LYP',
 'CGA',
 'MAGE2',
 'DUX1',
 'TRF-GAA1-6',
 'NRXN4',
 'CSBP',
 'POM121',
 'YRRM1',
 'C7',
 'MTTF1',
 'NR6',
 'FOXO3B',
 'HIES6',
 'POP4',
 'DPPIV',
 'RED',
 'LIPH',
 'RNF21',
 'PFD',
 'SCP1',
 'RNU1-7',
 'AOH1',
 'APITD1',
 'BAR',
 'EXOC1',
 'LNCPENG',
 'ARF1P2',
 'P19',
 'CDM',
 'HIST2H2BD',
 'P130',
 'LAS1',
 'NL1',
 'PMS2CL',
 'ACT',
 'GAGE2',
 'PMR1',
 'MEP',
 'CXORF49B',
 'SCAP',
 'HG523',
 'GCD',
 'HD1',
 'TP1',
 'L11',
 'TRQ-CTG1-4',
 'TPX1',
 'L1',
 'TRY1',
 'EP2',
 'TRR-ACG1-2',
 'MPDZ',
 'ESG1',
 'TRC-GCA2-3',
 'HRG1',
 'CT4.4',
 'PIR-B',
 'HCS',
 'TCBA1',
 'PGD',
 'PN-I',
 'IL-21',
 'H2A.1',
 'ZNF32',
 'GDN',
 'TRP-AGG2-5',
 'PH2A/F',
 'GPRASP3',
 'PIG5',
 'L30',
 'TRIM49D2P',
 'OCC1',
 'ACVRLK4',
 'SOSS-B2',
 'FRP1',
 'MADM',
 'GP39',
 'HSJ-2',
 'H2AC17',
 'PRL3',
 'CAB1',
 'GEM',
 'AGPAT10',
 'PAGE-1',
 'FAF',
 'PIGU',
 'NSE1',
 'H3C6',
 'EIF-4D',
 'ODC1L',
 'POD1',
 'PSP',
 'NKH',
 'CLK2',
 'IDD',
 'TCF-1',
 'CD25',
 'GDH2',
 'HBH',
 'C2ORF74-DT',
 'PLP',
 'CHAT',
 'MPP',
 'TRP-AGG2-2',
 'ALDR1',
 'SPO',
 'UFM1P1',
 'MZF-1',
 'PHKD',
 'TP53TG3F',
 'SNT1',
 'MMP23A',
 'VMA5',
 'USP12-DT',
 'GALNAC-T10',
 'BGR',
 'FOP',
 'NOV',
 'DAP1',
 'GLYT1',
 'MGAT2',
 'TRF-GAA1-2',
 'P68',
 'MRP6',
 'L19',
 'GRINL1A',
 'AP-1',
 'AMD',
 'MRP-L32',
 'VWS1',
 'LINC02921',
 'RHOGAP2',
 'S3',
 'NPIPA8',
 'FCR-10',
 'H4C9',
 'THY1-AS1',
 'ADH4',
 'XG',
 'CCRL1',
 'GOLGA8R',
 'CES2',
 'Y4',
 'PEO',
 'HSP40',
 'MLCK2',
 'PRR4',
 'LINC01731',
 'CDS1',
 'P27',
 'AIBP',
 'HLP3',
 'LINC02544',
 'APC',
 'HSM',
 'AIB1',
 'KRAS',
 'GLUT6',
 'GGTA1P',
 'IMP3',
 'CKS1',
 'NBS',
 'PRG-3',
 'P450DB1',
 'ATP5A',
 'L14',
 'TRS-AGA2-3',
 'MIRHG1',
 'HNP-1',
 'SIL',
 'ARF1',
 'EBF3',
 'CHIF',
 'BDPLT1',
 'PAF1',
 'STM',
 'STAP',
 'NR1',
 'H2BFG',
 'AGT',
 'ADRA1A',
 'CRS3',
 'PTPRO',
 'CSN1',
 'ACTP1',
 'HLA-DRB',
 'THG1',
 'SDH',
 'STK22D',
 'IGO1',
 'SPS1',
 'VRP',
 'C82',
 'EIF1AP1',
 'P67',
 'LINC02110',
 'MIFR',
 'COM1',
 'H3C15',
 'ACP1',
 'TAZ',
 'PS1',
 'SP5',
 'CSE',
 'PTG',
 'MRX17',
 'PTA1',
 'SRGAP2',
 'COX11P',
 'HLA-DQB1',
 'ALDC',
 'SOHLH2',
 'PARS',
 'MRP-L15',
 'DIP',
 'IGFR2',
 'FBL2',
 'OPT',
 'CYP11B',
 'P45',
 '37LRP',
 'TGIF',
 'HDGF2',
 'FAM21A',
 'MIP-2A',
 'PIG11',
 'TRI-AAT5-1',
 'PAI',
 'HA-1',
 'ALG14-AS1',
 'SCP',
 'ARP5',
 'PSBG-9',
 'CHS1',
 'PRL1',
 'UCMD1',
 'FZD3',
 'EST',
 'H2BFA',
 'HK4',
 'LH2',
 'P-PST',
 'EEF1B',
 'SEMAF',
 'ARAT',
 'HNK1ST',
 'GAP',
 'TRW-CCA3-2',
 'BAF190',
 'CD32',
 'DAGK6',
 'SCYA2',
 'H9',
 'MAG',
 'JUNB',
 'HMG-1',
 'AGS8',
 'NEURL3',
 'LNP',
 'CEP4',
 'AIP-1',
 'HCRN',
 'PRH1',
 'PISD',
 'IGFR1',
 'CYP2D7AP',
 'TRS-AGA2-2',
 'P140',
 'STAT5',
 'TNRC18',
 'ORC1',
 'NUDT10',
 'ST1A3/ST1A4',
 'FAD',
 'CAP2',
 'IMPDH1',
 'TRQ-CTG1-1',
 'PARP',
 'DESI1',
 'POU5F1',
 'SCA31',
 'AOS1',
 'FAME',
 'PRG',
 'VWS2',
 'P200',
 'U3A',
 '67LR',
 'SRK',
 'SELP',
 'SPDYE9',
 'STIP',
 'SEA',
 'APC1',
 'EPM2A',
 'NMB',
 'TRYP2',
 'MART2',
 'ASPS',
 'TP55',
 'T6',
 'DRS',
 'DDX11L1',
 'DA1',
 'PIX1',
 'BACH1',
 'PER1',
 'FAM28A',
 'TAH1',
 'NEDF',
 'RNU12',
 'DEFA1',
 'FAAH',
 'P35',
 'TRK-CTT2-4',
 'TRP-TGG3-5',
 'ZNF183',
 'ANKRD30BP3',
 'FKBP12',
 'SWS',
 'PSK',
 'GJA9',
 'TRNAI-AAU',
 'LINC01357',
 'DVL1',
 'KRTAP5-6',
 'KIAA0172',
 'CACNA1C-AS1',
 'MIR1',
 'RNU1-7P',
 'KOX31',
 'KLK6',
 'KOX2',
 'CHL1',
 'CD182',
 ...}

In [11]:
ambiguous_symbol_set = set(item.strip() for item in ambiguous_symbol_set)

print(len(ambiguous_symbol_set))

5069

In [12]:
with open("../output/ambiguous_symbol_set.txt", "w") as file:
    for item in ambiguous_symbol_set:
        file.write(f"{item.strip()}\n")

In [13]:
with open("../output/ambiguous_symbol_set.txt", "r") as file:
    # read each line, strip newline characters, and convert to a set
    ambiguous_symbol_set = set(line.strip() for line in file)
len(ambiguous_symbol_set)

5069

In [14]:
ambiguous_symbol_set

{'LAGE2B',
 'DLG3',
 'CD85',
 'SH2B',
 'J3',
 'NP2',
 'ASP',
 'ZFP91',
 'SCHAD',
 'RAB1C',
 'BCOX',
 'XPE',
 'MGC22679',
 'PTX3',
 'MRX2',
 'TRF-GAA1-4',
 'PBS',
 'LINC02696',
 'FCRI',
 'STX17-DT',
 'RNU1-8P',
 'LINC02224',
 'PRC17',
 'FCERI',
 'C5A',
 'AMAP1',
 'MRP-S28',
 'PIF',
 'SLC16A4-AS1',
 'BAP-1',
 'OI4',
 'SYN1A',
 'HIES2',
 'TTD',
 'LINC00846',
 'CT45-5',
 'LINC01799',
 'ATS2',
 'H4C4',
 'G6PD',
 'EDHB17',
 'SIGLECP1',
 'CAPG',
 'NSE2',
 'SEF',
 'OFD1P2',
 'AMD1',
 'HH13',
 'ASB3',
 'LY-75',
 'D3',
 'P52',
 'H2BC4',
 'CKB',
 'RDS',
 'CST6',
 'BRPF1',
 'MCAP',
 'AML1-EVI-1',
 'NAG',
 'GT',
 'A3',
 'NAT5',
 'MIFR-1',
 'RGS13',
 'PRK1',
 'MAP-1',
 'L23A',
 'GP',
 'CAB2',
 'MRPS28',
 'TRB2',
 'STP',
 'TLN',
 'KRTAP5-8',
 'P57',
 'GCP-2',
 'KAL',
 'TC4',
 'RPL7P',
 'APPL2',
 'FPRH1',
 'KIAA0266',
 'MIG-2',
 'G13',
 'HSP70.1',
 'TAF',
 'FCCMS',
 'APOBEC1L',
 'XGPY',
 'WTS',
 'AUTL1',
 'H2A.2',
 'CDK11-P110',
 'TYRRS',
 'GALNT13',
 'HGRG8',
 'MENA',
 'ABC1',
 'MDSP',
 'ARP',
 'COX4',
 'BAL',
 'ILT5',
 'AGS2',
 'PRX2',
 'GOLGA5',
 'RPL36A',
 'FIB2',
 'FALDH',
 'P50',
 'HCCR-2',
 'LGS',
 'MRX31',
 'MORF4LP4',
 'CLA20',
 'HD6',
 'TFIIIB90',
 'ACTB',
 'ETDA',
 'FAM236D',
 'GT1',
 'HBG1',
 'MAML2',
 'MMDS3',
 'S100A16',
 'CDC14B2',
 'INT4',
 'AD1',
 'BOS1',
 'CSN3',
 'RIP5',
 'EIF4F',
 'PTB',
 'ERG3',
 'FBXO30',
 'BB2',
 'LST-3TM12',
 'LOR',
 'PRP-1/PRP-2',
 'OSF-2',
 'NBPF9',
 'RAX',
 'MSK16',
 'C11ORF5',
 'NPH2',
 'IL-1RA',
 'LRP4',
 'MIZ',
 'TRP2',
 'CIR',
 'OR19-4',
 'DBM',
 'CST',
 'TRS-GCT4-2',
 'TCF6L3',
 'CRA',
 'EFA6R',
 'AGPAT8',
 'CTSO1',
 'CMS1D',
 'GPI',
 'SSS1',
 'NRP2',
 'GNAO1-AS1',
 'SLP4',
 'OBTP',
 'TSPY10',
 'NAF1',
 'TIP',
 'BIS',
 'LPC1',
 'NPYR',
 'CEP2',
 'ABP-280',
 'PROTEASE',
 'MED',
 'MAD3',
 'TTF-1',
 'MRS',
 'ATR',
 'FJHN',
 'CSN2',
 'MID1',
 'H2BC10',
 'SKIP',
 'TTMA',
 'SH120',
 'TRL-AAG2-3',
 'FAPP2',
 'PROTEINASE',
 'SGK2',
 'AR',
 'COD4',
 'SIP',
 'RASA1',
 'SYT12',
 'AD3',
 'AGS1',
 'CEP68',
 'DIFF6',
 'DOC-1',
 'SPC1',
 'DRP3',
 'PP2CE',
 'DFNB35',
 'XDH',
 'UNQ192',
 'HOX3',
 'AP2',
 'SPATA8',
 'SRC1',
 'CORD5',
 'SAA1',
 'MADD',
 'ZNF2',
 'GLP-1',
 'SWS1',
 'DLEU2',
 'G6PT',
 'DGK',
 'C6ST',
 'CAC',
 'REH',
 'FOXL3',
 'B3GN-T1',
 'FRA10A',
 'CT5.2',
 'DEFB109',
 'VSD1',
 'NUDT4B',
 'CAPH2',
 'SPANX-C',
 'TEN1',
 'KAP2.4',
 'FRA3B',
 'I1',
 'FE',
 'ELK1',
 'GC',
 'NANOGP3',
 'MBP',
 'CK20',
 'FAME3',
 'ARG',
 'HYPP',
 'GEP',
 'PRPH',
 'RIP-1',
 'E4TF1',
 'PAP1',
 'H2AC13',
 'NET3',
 'U3B2',
 'EMAP-2',
 'GUSBP9',
 'KRTAP2-4',
 'CPSB',
 'SRGAP3',
 'PMI1',
 'H2BFH',
 'RNU1P2',
 'MLT1',
 'TCRAV13S1',
 'HMCS',
 'EDH17B2',
 'OI6',
 'HD7',
 'P24',
 'CACNA1I',
 'DLP1',
 'MOP',
 'TCRBV13S1',
 'NAPOR',
 'ACC',
 'AS',
 'HIST1H2BI',
 'HSP70-1',
 'POF',
 'P600',
 'MRP-L14',
 'RAM',
 'SRP40',
 'DOR',
 'C15ORF63',
 'US2',
 'UIP1',
 'CRD',
 'NET4',
 'CARMEN',
 'TNX',
 'AMY1',
 'HSTF1',
 'CED12',
 'LPLAT',
 'MMP20',
 'SCP2',
 'RAI1',
 'CLEC2B',
 'LINC00086',
 'GALNT4',
 'FAM90A19P',
 'RIA1',
 'KLHL6',
 'ASC',
 'DLK',
 'VDR',
 'FADS2',
 'MPI',
 'H1RNA',
 'SCKL4',
 'MGC15397',
 'BHLHE42',
 'RAK',
 'TMSA',
 'PMS2P2',
 'TRL-AAG2-2',
 'ANT1',
 'NTE',
 'SIGLECP2',
 'TCRBV3S1',
 'LONP',
 'CD98',
 'MCDR2',
 'FH',
 'HCG1',
 'IFN-ALPHAI',
 'CYPL1',
 'LINC01167',
 'CREB2',
 'IL8RA',
 'VAT1',
 'ANG2',
 'MFRP',
 'GCP',
 'PAR-6',
 'MASK',
 'HSD3B',
 'LYP',
 'MAGE2',
 'DUX1',
 'TRF-GAA1-6',
 'NRXN4',
 'NR6',
 'HIES6',
 'DPPIV',
 'RED',
 'SCP1',
 'AOH1',
 'APITD1',
 'EXOC1',
 'BAR',
 'LNCPENG',
 'P130',
 'LAS1',
 'ACT',
 'CXORF49B',
 'SCAP',
 'HG523',
 'GCD',
 'HD1',
 'EP2',
 'ESG1',
 'TCBA1',
 'PGD',
 'IL-21',
 'TRP-AGG2-5',
 'GDN',
 'PH2A/F',
 'L30',
 'TRIM49D2P',
 'HSJ-2',
 'GEM',
 'POD1',
 'PSP',
 'NKH',
 'CLK2',
 'IDD',
 'CD25',
 'HBH',
 'C2ORF74-DT',
 'MPP',
 'SPO',
 'UFM1P1',
 'MZF-1',
 'TP53TG3F',
 'VMA5',
 'USP12-DT',
 'GALNAC-T10',
 'BGR',
 'MGAT2',
 'TRF-GAA1-2',
 'MRP6',
 'AMD',
 'VWS1',
 'NPIPA8',
 'THY1-AS1',
 'ADH4',
 'CCRL1',
 'CES2',
 'Y4',
 'PEO',
 'MLCK2',
 'PRR4',
 'LINC01731',
 'P27',
 'HLP3',
 'GGTA1P',
 'CKS1',
 'ATP5A',
 'TRS-AGA2-3',
 'HNP-1',
 'CHIF',
 'STM',
 'STAP',
 'ACTP1',
 'HLA-DRB',
 'SDH',
 'IGO1',
 'EIF1AP1',
 'P67',
 'H3C15',
 'TAZ',
 'PS1',
 'SP5',
 'CSE',
 'PTG',
 'SRGAP2',
 'COX11P',
 'ALDC',
 'FBL2',
 'CYP11B',
 '37LRP',
 'TGIF',
 'FAM21A',
 'MIP-2A',
 'TRI-AAT5-1',
 'ARP5',
 'PRL1',
 'EEF1B',
 'P-PST',
 'SEMAF',
 'ARAT',
 'GAP',
 'BAF190',
 'DAGK6',
 'JUNB',
 'HMG-1',
 'LNP',
 'CEP4',
 'AIP-1',
 'PRH1',
 'IGFR1',
 'TRS-AGA2-2',
 'P140',
 'STAT5',
 'TNRC18',
 'ORC1',
 'NUDT10',
 'IMPDH1',
 'SCA31',
 'PRG',
 'VWS2',
 'P200',
 'U3A',
 'SRK',
 'SELP',
 'SPDYE9',
 'TRYP2',
 'ASPS',
 'TP55',
 'DDX11L1',
 'BACH1',
 'PER1',
 'NEDF',
 'DEFA1',
 'FAAH',
 'P35',
 'ZNF183',
 'ANKRD30BP3',
 'GJA9',
 'TRNAI-AAU',
 'LINC01357',
 'DVL1',
 'KOX31',
 'KLK6',
 'KOX2',
 'CD182',
 'FSP2',
 'MLN',
 'PGDS',
 'ORF1',
 'RARF',
 'BRF1',
 'STV1',
 'DFNA52',
 'DUP',
 'HN1L',
 'HZF-3',
 'CSB',
 'C9',
 'H2AB3',
 'TRS4',
 'SERPINA11',
 'RIS1',
 'SMCC',
 'TFP',
 'FEZ',
 'PRR23D1',
 'CAF-1',
 'LGCR',
 'OR17-30',
 'PVALB',
 'P29',
 'IA4',
 'GALNT16',
 'EJM',
 'NSPLII',
 'SES2',
 'NEU1',
 'LOXL',
 'CK1',
 'EEF1AKMT4',
 'CYP1',
 'SG2NA',
 'CIR1',
 'CPX1',
 'LIG1',
 'POU2F2-AS2',
 'CRHSP24',
 'PPYR1',
 'RN5-8S1',
 'ARTS',
 'UGT1-03',
 'KAP1.6',
 'LIP1',
 'OCA8',
 'CHMP3',
 'NECC1',
 'LINC02634',
 'TCS3',
 'ISGF-3',
 'SCA4',
 'SAE2',
 'PAM',
 'AIS',
 'OCT-3',
 'CKR-1',
 'CHRNA7',
 'USP12-AS2',
 'DM1',
 'PRIP',
 'ENV',
 'C16ORF15',
 'MNS',
 'TRPM2',
 'PRR20A',
 'DVL1L1',
 'GAGE-7B',
 'CSF',
 'MCAF',
 'P60',
 'MIA2',
 'PRKACA',
 'MTP',
 'ICE',
 'BETA4GALNACT',
 'CCL',
 'PAR3',
 'GCAP-II',
 'EP',
 'ADK',
 'U14',
 'CALM',
 'TCF4',
 'PHLP3',
 'SRA',
 'TP53TG3',
 'CLC',
 'LRP1',
 'SPEN',
 'RHEB2',
 'GTF2IRD2',
 'LAGE-2',
 'CXORF2',
 'TIM',
 'TRT-AGT4-1',
 'CTNND1',
 'MAST',
 'GRP',
 'NOP',
 'RASSF3',
 'HNRPA3',
 'BA548K23.1',
 'LINC01358',
 'IHG1',
 'LINC00473',
 'P2',
 'AD026',
 'P450C2D',
 'TCP11X2',
 'SNO',
 'KIAA0700',
 'CYC1',
 'LIS2',
 'NAPA',
 'MAD1',
 'L22',
 'EVA',
 'ZNF581',
 'PD1',
 'BEX1',
 'PSISSX8',
 'CGB5',
 'MCM',
 'MS4A4',
 'TRB',
 'WBS',
 'MTF',
 'P02',
 'EIF2',
 'SPTBN1-AS2',
 'RINZF',
 'HN3',
 'GLYT2',
 'AC1',
 'POM121L1',
 'UCN2',
 'PTEX',
 'MIO',
 'ANKRD33',
 'CLDN21',
 'SWAP',
 'PMS2L2',
 '3-ALPHA-HSD',
 'FSSV',
 'DEFB-5',
 'SEPT2',
 'XAP3',
 'ASH1',
 'HLAL',
 'GO',
 'FLJ37712',
 'TRS-GCT4-3',
 'LNMAT1',
 'LINC01974',
 'RGS9',
 'PIRB',
 'DQA1',
 'MIG6',
 'CT6.1',
 'RBAK',
 'RHO',
 'PFM2',
 'IGSF13',
 'SCG3',
 'PAK1',
 'ABP1',
 'ART1',
 'PLCE',
 'C18ORF53',
 'IGLV',
 'NAP1',
 'PABP4',
 'METTL2A',
 'CNP',
 'CN-IB',
 'PI',
 'ACC1',
 'DIA2',
 'FXYD6',
 'L8',
 'CDG2T',
 'SUT2',
 'SF3B1',
 'SPH1',
 'GARS',
 'TRD-GTC2-6',
 'BNC1',
 'RTA',
 'NBR',
 'BCS1',
 'OR3A5P',
 'BEC1',
 'ANXA8',
 'U3B1',
 'INV',
 'SMN-AS1',
 'TCF6L1',
 'P54',
 'RNA18S5',
 'CDA12',
 'TBC1D3I',
 'KAP1',
 'GJA10',
 'RTP',
 'MIR17HG',
 'C1QTNF5',
 'U1P2A',
 'IGVPB',
 'KIAA0229',
 'IGHEP1',
 'FRP',
 'MAFA',
 'TTTY6',
 'CLP1',
 'CDC14B',
 'RAB7',
 'CAV',
 'IGHV',
 'EDG1',
 'OR7E68P',
 'EIF2B',
 'CTF',
 'DAR',
 'EPPK',
 'FBRNP',
 'HSD17',
 'AP47B',
 'PE-1',
 'ZNF264',
 'S4',
 'HSPA1',
 'OPG',
 'PPAT',
 'PAT1',
 'MTS1',
 'OP2',
 'TMSB15B',
 'ASF',
 'MART1',
 'SCL',
 'DAP3',
 'RDC1',
 'CP11',
 'HK1',
 'DEFB108B',
 'TTTY8',
 'ECD',
 'LVG2',
 'MIR-129B',
 'CPO',
 'MOS',
 'LRRC37A',
 'PLAP-1',
 'FCRIII',
 'SPANX-A',
 'DXS648E',
 'HDC',
 'L18',
 'LINC00407',
 'PPN',
 'FBXW6',
 'AF',
 'TTF2',
 'G18',
 'ADAMTS-4',
 'CFP1',
 'ES31',
 'CXORF49',
 'GAGE7B',
 'DS',
 'SST2',
 'SARS',
 'ELOA3',
 'BIP',
 'ECA2',
 'DFNA3',
 'TCRGV5P',
 'FMR2',
 'AK3',
 'SPAP1',
 'CCA3',
 'WWP4',
 'DMT1',
 'PIGF',
 'NFIC',
 'MCPH4',
 'TPS2',
 'ENO1-IT1',
 'ME3',
 'ATD',
 'PGR2',
 'C2ORF27B',
 'L13',
 'SUH',
 'CORO7',
 'TCRAV10S1',
 'FMR1',
 'B61',
 'HLX1',
 'IFP1',
 'CSS1',
 'RBP2',
 'NRF2',
 'CMT2A',
 'GBP3',
 'OR19-7',
 'CREB-2',
 'PSMD15',
 'SEN1',
 'MOSP',
 'NTT',
 'RANBP2L2',
 'H3.1',
 'NB',
 'CAT1',
 'LGL2',
 'TRAF2',
 'PPS',
 'SDR1',
 'PI7',
 'CCL4L',
 'SDH3',
 'SPP2',
 'K13',
 'HSST2',
 'H2AC16',
 'ICLN',
 'FCGR2C',
 'KIR2DL1',
 'SOF1',
 'TCEB3L2',
 'CPLA2-BETA',
 'TSH2',
 'RC3',
 'SEMA',
 'CDC25L',
 'TMS',
 'SPATA31D3',
 'ULG4',
 'FGD2',
 'FAM25C',
 'GM2AP',
 'MTC',
 'RBM5-AS1',
 'EIF5A',
 'CAMC',
 'SIP1',
 'ZNF322',
 'PAP',
 'MBP1',
 'SNRPB1',
 'DAB1',
 'SPX1',
 'P39',
 'L32MT',
 'APOC4',
 'POP3',
 'PNR',
 'RPL29P3',
 'LGMD1E',
 'ND1',
 'HC5',
 'SYD1',
 'SK2',
 'SCYL2',
 'XAGE1B',
 'P60TRP',
 'BS',
 'RNA18S4',
 'USP17L25',
 'OSCP',
 'APT2',
 'C17ORF106',
 'CD205',
 'OP-2',
 'TANGO',
 'TDGF2',
 'FADS',
 'CAIN',
 'GAGE-12B',
 'BGP',
 'PLAC8',
 'C4B',
 'IGH',
 'LINC02595',
 'PLD1',
 'CYP2A',
 'II',
 'OCT3',
 'ALDH4',
 'HPP1',
 'B4',
 'BHD',
 'ATP6G',
 'BD-6',
 'LINC02193',
 'TTY9',
 'FAM138F',
 'V1S5P',
 'FRAG1',
 'GS2',
 'TRIP1',
 'HPH2',
 'ARH1',
 'OR7E73P',
 'L5',
 'CRYG5',
 'GP130',
 'BD-4',
 'MRF1',
 'SCG2',
 'MBD3',
 'TUBB4',
 'PACAP',
 'ACAT1',
 'PDK1',
 'INT3',
 'HCA3',
 'MURF2',
 'MCL',
 'IGEL',
 'C1ORF175',
 'MIR198',
 'PGI',
 'CAL',
 'H2B/A',
 'OSX',
 'SMC5-DT',
 'SIT',
 'RP7',
 'ENH1',
 'P12',
 'RER',
 'SPR',
 'TAT',
 'LD78',
 'BOCA',
 'L4',
 'SNURF',
 'GLM1',
 'UGT1',
 'OR19-12',
 'AITD3',
 'NET7',
 'BEX2',
 'PEPP-2',
 'TMSNB',
 'LGMD1D',
 'ACTBP2',
 'SAS',
 'COAS-2',
 'HOM-MEL-40',
 'LINC01238',
 'PCP2',
 'CARDINAL',
 'BTR',
 'CIP',
 'EK',
 'TRIM34',
 'GUSBP1',
 'GDH',
 'ULG5',
 'EPPK1',
 'C10ORF77',
 'PTEN2',
 'ERK3',
 'NABC1',
 'NGBR',
 'H2BFL',
 'LBH',
 'RBM14',
 'E4',
 'RBMY1D',
 'CIP1',
 'EGLN2',
 'FCP',
 'HMS',
 'ZNF72',
 'GALNT7',
 'EDM4',
 'HEPTP',
 'DRP',
 'CIA',
 'UGAT',
 'SOCS7',
 'L10',
 'AUGA',
 'GP1BB',
 'TS',
 'AIM-1',
 'AAAT',
 'NOS',
 'ER',
 'CTRP5',
 'CDH24',
 'BSC',
 'OLFR42B',
 'P42',
 'NUBP1',
 'NOMO',
 'CDG1P',
 'CRP3',
 'CLS',
 'HLP2',
 'TPP1',
 'C20ORF197',
 'EMAP2',
 'SPANXC',
 ...}

### <a id='toc1_1_2_'></a>[Primary exploration of DGIdb gene content using collisions](#toc0_)

#### <a id='toc1_1_2_1_'></a>[Load gene claim data from DGIdb](#toc0_)

In [15]:
dgidb_gene_df = pd.read_csv(
    "../input/dgidb_genes_JUNE.tsv", sep="\t", na_values=["", "NULL"], keep_default_na=False
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17

In [16]:
num_total_claims = len(dgidb_gene_df)

In [17]:
dgidb_gene_df.loc[dgidb_gene_df["gene_claim_name"] == "HES1"]

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
30772,HES1,Gene Symbol,hgnc:5192,HES1,Pharos,10-Apr-24
76844,HES1,Gene Symbol,hgnc:5192,HES1,HGNC,20240408
76845,HES1,Gene Symbol,hgnc:5192,HES1,NCBI,20240410
76846,HES1,Gene Symbol,hgnc:5192,HES1,Ensembl,111
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17

#### <a id='toc1_1_2_2_'></a>[How many claims are placed in a gene group with a different label?](#toc0_)

In [18]:
dgidb_gene_df.query("gene_name != gene_claim_name")

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
...,...,...,...,...,...,...
79999,SEPT5,Gene Symbol,hgnc:9164,SEPTIN5,FoundationOneGenes,9/3/20
80014,ENSEMBL:ENSG00000185821,Ensembl Gene ID,hgnc:31305,OR6C76,RussLampel,26-Jul-11
80053,SEPT5,Gene Symbol,hgnc:9164,SEPTIN5,CarisMolecularIntelligence,9/4/20
80166,SEPT6,Gene Symbol,hgnc:15848,SEPTIN6,CarisMolecularIntelligence,9/4/20
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20

#### <a id='toc1_1_2_3_'></a>[How many claims are not normalized?](#toc0_)

claims without a symbol/name/identifier
 (there shouldn't be any hooray)

In [19]:
no_claim_symbols_df = dgidb_gene_df[dgidb_gene_df["gene_claim_name"].isnull()]
no_claim_symbols_df

Empty DataFrame
Columns: [gene_claim_name, nomenclature, concept_id, gene_name, source_db_name, source_db_version]
Index: []

In [20]:
no_name_symbols_df = dgidb_gene_df[dgidb_gene_df["gene_name"].isnull()]
num_not_normalized_claims = len(no_name_symbols_df)
num_not_normalized_claims

2144

In [21]:
num_normalized_claims = num_total_claims - num_not_normalized_claims

#### <a id='toc1_1_2_4_'></a>[Create set of gene groups (gene_name) and gene claims (gene_claim_name)](#toc0_)

In [22]:
dgidb_name_set = set(dgidb_gene_df["gene_name"])
len(dgidb_name_set)

12001

In [23]:
dgidb_gene_claim_name_set = set(dgidb_gene_df["gene_claim_name"])
len(dgidb_gene_claim_name_set)

26739

#### <a id='toc1_1_2_5_'></a>[Load HGNC, Ensembl (ENSG), and NCBI gene and alias sets](#toc0_)

Input: mini_hgnc_df, mini_ensg_df, mini_ncbi_df (total_alias_gene_intersections.ipynb)

Output: x_gene_symbol_set, x_alias_symbol_set where x is ncbi, ensg or ncbi

In [24]:
mini_hgnc_df = pd.read_csv(
    "../output/mini_hgnc_df.csv", na_values=["", "NULL"], keep_default_na=False
)

In [25]:
mini_ensg_df = pd.read_csv(
    "../output/mini_ensg_df.csv", na_values=["", "NULL"], keep_default_na=False
)

In [26]:
mini_ncbi_df = pd.read_csv(
    "../output/mini_ncbi_df.csv", na_values=["", "NULL"], keep_default_na=False
)

In [27]:
hgnc_gene_symbol_set = set(mini_hgnc_df["primary_gene_symbol"])
len(hgnc_gene_symbol_set)

44228

In [28]:
ensg_gene_symbol_set = set(mini_ensg_df["primary_gene_symbol"])
len(ensg_gene_symbol_set)

41164

In [29]:
ncbi_gene_symbol_set = set(mini_ncbi_df["primary_gene_symbol"])
len(ncbi_gene_symbol_set)

44530

In [30]:
hgnc_alias_symbol_set = set(mini_hgnc_df["alias_symbol"])
len(hgnc_alias_symbol_set)

43072

In [31]:
ensg_alias_symbol_set = set(mini_ensg_df["alias_symbol"])
len(ensg_alias_symbol_set)

55413

In [32]:
ncbi_alias_symbol_set = set(mini_ncbi_df["alias_symbol"])
len(ncbi_alias_symbol_set)

69210

#### <a id='toc1_1_2_6_'></a>[How many unique primary gene symbols are there b/w HGNC, Ensembl, and NCBI?](#toc0_)

In [33]:
hgnc_ensg_gene_symbol_set = hgnc_gene_symbol_set.union(ensg_gene_symbol_set)

In [34]:
hgnc_ensg_ncbi_gene_symbol_set = hgnc_ensg_gene_symbol_set.union(ncbi_gene_symbol_set)
len(hgnc_ensg_ncbi_gene_symbol_set)

44786

#### <a id='toc1_1_2_7_'></a>[How many unique alias symbols are there b/w HGNC, Ensembl, and NCBI?](#toc0_)

In [35]:
hgnc_ensg_alias_symbol_set = hgnc_alias_symbol_set.union(ensg_alias_symbol_set)

In [36]:
hgnc_ensg_ncbi_alias_symbol_set = hgnc_ensg_alias_symbol_set.union(
    ncbi_alias_symbol_set
)
len(hgnc_ensg_ncbi_alias_symbol_set)

92995

#### <a id='toc1_1_2_8_'></a>[How many unique group names are not primary gene symbols?](#toc0_)

In [37]:
name_ensg_notmatch = dgidb_name_set.difference(ensg_gene_symbol_set)
len(name_ensg_notmatch)

297

In [38]:
name_hgnc_notmatch = dgidb_name_set.difference(hgnc_gene_symbol_set)
len(name_hgnc_notmatch)

176

In [39]:
cleaned_name_hgnc_notmatch = [x for x in name_hgnc_notmatch if str(x) != "NaN"]
len(cleaned_name_hgnc_notmatch)

176

In [40]:
name_ncbi_notmatch = dgidb_name_set.difference(ncbi_gene_symbol_set)
len(name_ncbi_notmatch)

187

In [41]:
name_ncbi_hgnc_notmatch = name_ncbi_notmatch.difference(hgnc_gene_symbol_set)
len(name_ncbi_hgnc_notmatch)

169

How many groups are labeled with a symbol not found in the sets of primary symbols from HGNC, NCBI, or ENSG?

In [42]:
name_ncbi_hgnc_ensg_notmatch = name_ncbi_hgnc_notmatch.difference(ensg_gene_symbol_set)
len(name_ncbi_hgnc_ensg_notmatch)

150

In [43]:
name_ncbi_hgnc_ensg_notmatch

{'A12M1',
 'A12M2',
 'A12M3',
 'A12M4',
 'ACT',
 'ACTBP5',
 'ACTL4',
 'ACTL5',
 'ADAL',
 'ADFN',
 'AGTRL2',
 'ALDRL2',
 'ALS3',
 'AMCN',
 'ANOP1',
 'ANTP2',
 'ANTP4',
 'APOBER1',
 'ARCN2',
 'ARVD3',
 'ARVD4',
 'ASD1',
 'ATD',
 'ATHS',
 'ATP3',
 'ATP5A2',
 'ATP5BL2',
 'AZF1',
 'AZF2',
 'BCGF1',
 'BCHEL1',
 'BCHEL3',
 'BCL5',
 'BDM',
 'BEVI',
 'BRAFPS1',
 'BTNL1',
 'BTS1',
 'CATHL1L',
 'CCA1',
 'CDB2',
 'CHR',
 'CMM',
 'CMR1A',
 'CMR3A',
 'CMTX3',
 'CNA1',
 'CNC2',
 'COD2',
 'CORD1',
 'CORD4',
 'CSNKA2IP',
 'CTAA1',
 'CTAA2',
 'CTD',
 'CYB5P1',
 'CYP3A',
 'DBIL3',
 'DFNA19',
 'DFNB13',
 'DFNB14',
 'DFNB5',
 'DYT7',
 'E11S',
 'EBM',
 'EBR3',
 'EBR4',
 'EEGV1',
 'EGI',
 'ELNL1',
 'ENUR1',
 'ENUR2',
 'ERCM1',
 'ERPL1',
 'ERPL2',
 'ERV1',
 'ERVK2',
 'ERVK3',
 'ERVT1',
 'ERVT3',
 'ERVT4',
 'ERVT5',
 'EXT3',
 'F13A3',
 'F2L',
 'F7R',
 'FAUNA@',
 'FCP1',
 'FEB1',
 'FEB2',
 'FNL1',
 'FNTBL1',
 'FNZ',
 'FOLR2L',
 'FRA4E',
 'FRA8F',
 'FRDA2',
 'FRV1',
 'FRV3',
 'FSHMD1A',
 'FSHMD1B',
 'FUSE',
 'GAPDHL17',
 'GCF1',
 'GGTL1',
 'GGTL2',
 'GKP4',
 'GKP5',
 'GLC#',
 'GLC1B',
 'GLC1C',
 'GLC1D',
 'GLC3B',
 'GMFA',
 'GPR34P',
 'GSK1',
 'GSM1',
 'GUSM',
 'H4F3',
 'HCA1',
 'HCL2',
 'HCVS',
 'HEMC',
 'HMAA',
 'HMAB',
 'HMG1P',
 'HMS1',
 'HOXB@',
 'HOXC@',
 'HOXD@',
 'HPE1',
 'HPFH2',
 'HPRTP1',
 'HPT',
 'LOC102723996',
 'LOC102724428',
 'LOC105376944',
 'LOC112268384',
 'LOC112694756',
 'LOC344967',
 'LOC408186',
 'LOC653303',
 'MRSD',
 'OA1',
 'PAND1',
 'UGT2B@',
 'USP17L',
 'XS',
 'mCR',
 nan}

In [44]:
len(dgidb_name_set)

12001

#### <a id='toc1_1_2_9_'></a>[How many unique claims are not primary gene symbols?](#toc0_)

In [45]:
gene_claim_name_ensg_notmatch = dgidb_gene_claim_name_set.difference(
    ensg_gene_symbol_set
)
len(gene_claim_name_ensg_notmatch)

15030

In [46]:
cleaned_gene_claim_name_ensg_notmatch = [
    x for x in gene_claim_name_ensg_notmatch if str(x) != "NaN"
]
len(cleaned_gene_claim_name_ensg_notmatch)

15030

In [47]:
gene_claim_name_hgnc_notmatch = dgidb_gene_claim_name_set.difference(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_notmatch)

14908

In [48]:
gene_claim_name_ncbi_notmatch = dgidb_gene_claim_name_set.difference(
    ncbi_gene_symbol_set
)
len(gene_claim_name_ncbi_notmatch)

14919

In [49]:
gene_claim_name_ncbi_hngc_notmatch = gene_claim_name_ncbi_notmatch.difference(
    hgnc_gene_symbol_set
)
len(gene_claim_name_ncbi_hngc_notmatch)

14901

How many unique claims are not primary symbols

In [50]:
gene_claim_name_ncbi_hngc_ensg_notmatch = gene_claim_name_ncbi_hngc_notmatch.difference(
    ensg_gene_symbol_set
)
num_not_primary_claims = len(gene_claim_name_ncbi_hngc_ensg_notmatch)
num_not_primary_claims

14882

#### <a id='toc1_1_2_10_'></a>[Load the collision sets from each data source](#toc0_)

Input: aa_collision_x_df.csv (total_alis_overlap.ipynb)

Output: x_alias_alias_collision_set

In [51]:
merged_alias_aa_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_aa_collision_hgnc_df.csv",
    na_values=["", "NULL"],
    keep_default_na=False,
)

In [52]:
hgnc_alias_alias_collision_set = set(merged_alias_aa_collision_hgnc_df["collision"])
len(hgnc_alias_alias_collision_set)

1458

In [53]:
merged_alias_aa_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ncbi_df.csv",
    na_values=["", "NULL"],
    keep_default_na=False,
)

In [54]:
ncbi_alias_alias_collision_set = set(merged_alias_aa_collision_ncbi_df["collision"])
len(ncbi_alias_alias_collision_set)

4031

In [55]:
merged_alias_aa_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ensg_df.csv",
    na_values=["", "NULL"],
    keep_default_na=False,
)

In [56]:
ensg_alias_alias_collision_set = set(merged_alias_aa_collision_ensg_df["collision"])
len(ensg_alias_alias_collision_set)

1617

#### <a id='toc1_1_2_11_'></a>[How many unique group names are primary gene symbols?](#toc0_)

In [57]:
name_hgnc_match = dgidb_name_set.intersection(hgnc_gene_symbol_set)
len(name_hgnc_match)

11825

In [58]:
name_ensg_match = dgidb_name_set.intersection(ensg_gene_symbol_set)
len(name_ensg_match)

11704

In [59]:
name_ncbi_match = dgidb_name_set.intersection(ncbi_gene_symbol_set)
len(name_ncbi_match)

11814

In [60]:
name_ncbi_ensg_match = name_ncbi_match.intersection(ensg_gene_symbol_set)
len(name_ncbi_ensg_match)

11669

In [61]:
name_ncbi_ensg_hgnc_match = name_ncbi_ensg_match.intersection(hgnc_gene_symbol_set)
len(name_ncbi_ensg_hgnc_match)

11668

#### <a id='toc1_1_2_12_'></a>[How many of the groups that are labeled with a primary gene symbol are also alias-alias collisions?](#toc0_)

In [62]:
name_ncbi_match_aacollision = name_ncbi_match.intersection(
    ncbi_alias_alias_collision_set
)
len(name_ncbi_match_aacollision)

130

In [63]:
name_ensg_match_aacollision = name_ensg_match.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_match_aacollision)

41

In [64]:
name_ensg_notmatch_aacollision = name_ensg_notmatch.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_notmatch_aacollision)

3

#### <a id='toc1_1_2_13_'></a>[How many unique claim symbols are collisions?](#toc0_)

In [65]:
gene_claim_name_ensg_aacollision_match = dgidb_gene_claim_name_set.intersection(
    ensg_alias_alias_collision_set
)
len(gene_claim_name_ensg_aacollision_match)

98

In [66]:
gene_claim_name_hgnc_aacollision_match = dgidb_gene_claim_name_set.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_aacollision_match)

73

In [67]:
gene_claim_name_ncbi_aacollision_match = dgidb_gene_claim_name_set.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_aacollision_match)

232

#### <a id='toc1_1_2_14_'></a>[How many unique groups are labeled with collisions?](#toc0_)

In [68]:
name_ensg_aacollision_match = dgidb_name_set.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_aacollision_match)

44

In [69]:
name_hgnc_aacollision_match = dgidb_name_set.intersection(
    hgnc_alias_alias_collision_set
)
len(name_hgnc_aacollision_match)

38

In [70]:
name_ncbi_aacollision_match = dgidb_name_set.intersection(
    ncbi_alias_alias_collision_set
)
len(name_ncbi_aacollision_match)

135

#### <a id='toc1_1_2_15_'></a>[How many unique claims are not primary gene symbols?](#toc0_)

In [71]:
gene_claim_name_hgnc_notmatch = dgidb_gene_claim_name_set.difference(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_notmatch)

14908

In [72]:
gene_claim_name_ensg_notmatch = dgidb_gene_claim_name_set.difference(
    ensg_gene_symbol_set
)
len(gene_claim_name_ensg_notmatch)

15030

In [73]:
gene_claim_name_ncbi_notmatch = dgidb_gene_claim_name_set.difference(
    ncbi_gene_symbol_set
)
len(gene_claim_name_ncbi_notmatch)

14919

#### <a id='toc1_1_2_16_'></a>[How many unique claims that were not primary symbols are collisions?](#toc0_)

In [74]:
gene_claim_name_hgnc_notmatch_aacollision = gene_claim_name_hgnc_notmatch.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_notmatch_aacollision)

37

In [75]:
gene_claim_name_ncbi_notmatch_aacollision = gene_claim_name_ncbi_notmatch.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_notmatch_aacollision)

102

In [76]:
gene_claim_name_ensg_notmatch_aacollision = gene_claim_name_ensg_notmatch.intersection(
    ensg_alias_alias_collision_set
)
len(gene_claim_name_ensg_notmatch_aacollision)

57

#### <a id='toc1_1_2_17_'></a>[How many unique claims that are primary gene symbols are also collisions?](#toc0_)

In [77]:
gene_claim_name_hgnc_match = dgidb_gene_claim_name_set.intersection(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_match)

11831

In [78]:
gene_claim_name_hgnc_match_aacollision = gene_claim_name_hgnc_match.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_match_aacollision)

36

In [79]:
gene_claim_name_ncbi_match = dgidb_gene_claim_name_set.intersection(
    ncbi_gene_symbol_set
)
len(gene_claim_name_ncbi_match)

11820

In [80]:
gene_claim_name_ncbi_match_aacollision = gene_claim_name_ncbi_match.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_match_aacollision)

130

In [81]:
gene_claim_name_ensg_match = dgidb_gene_claim_name_set.intersection(
    ensg_gene_symbol_set
)
len(gene_claim_name_ensg_match)

11709

In [82]:
gene_claim_name_ensg_match_aacollision = gene_claim_name_ensg_match.intersection(
    ensg_alias_alias_collision_set
)
len(gene_claim_name_ensg_match_aacollision)

41

#### <a id='toc1_1_2_18_'></a>[How many of the gene groups that are not primary gene symbols are alias-alias collisions from HGNC?](#toc0_)

In [83]:
name_hngc_notmatch_aacollision = name_hgnc_notmatch.intersection(
    hgnc_alias_alias_collision_set
)
len(name_hngc_notmatch_aacollision)

2

In [84]:
name_ncbi_notmatch_aacollision = name_ncbi_notmatch.intersection(
    ncbi_alias_alias_collision_set
)
len(name_ncbi_notmatch_aacollision)

5

In [85]:
name_ensg_notmatch_aacollision = name_ensg_notmatch.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_notmatch_aacollision)

3

#### <a id='toc1_1_2_19_'></a>[How many claims are ambiguous symbols?](#toc0_)

In [86]:
dgidb_gene_df["claim_ambiguous_status"] = dgidb_gene_df["gene_claim_name"].isin(
    ambiguous_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False

In [87]:
dgidb_gene_df["claim_ambiguous_status"].value_counts()

claim_ambiguous_status
False    75573
True      4661
Name: count, dtype: int64

In [88]:
ambiguous_claim_df = dgidb_gene_df.loc[dgidb_gene_df["claim_ambiguous_status"]]
num_ambiguous_claim = len(ambiguous_claim_df)
num_ambiguous_claim

4661

In [89]:
ambiguous_claim_df.loc[ambiguous_claim_df["gene_claim_name"] == "TR2"]

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status
18,TR2,NCBI Gene Name,hgnc:7971,NR2C1,BaderLab,Feb-14,True

#### <a id='toc1_1_2_20_'></a>[How many gene group labels are ambiguous symbols?](#toc0_)

In [90]:
dgidb_gene_df["name_ambiguous_status"] = dgidb_gene_df["gene_name"].isin(
    ambiguous_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False

In [91]:
dgidb_gene_df["name_ambiguous_status"].value_counts()

name_ambiguous_status
False    74708
True      5526
Name: count, dtype: int64

In [92]:
ambiguous_name_df = dgidb_gene_df.loc[dgidb_gene_df["name_ambiguous_status"]]
num_ambiguous_name = len(ambiguous_name_df)
num_ambiguous_name

5526

#### <a id='toc1_1_2_21_'></a>[How many claims are primary symbols?](#toc0_)

In [93]:
dgidb_gene_df["claim_primary_status"] = dgidb_gene_df["gene_claim_name"].isin(
    hgnc_ensg_ncbi_gene_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
...,...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False,True
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False,True
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False,False
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False,True

In [94]:
dgidb_gene_df["claim_primary_status"].value_counts()

claim_primary_status
True     64034
False    16200
Name: count, dtype: int64

In [95]:
primary_claim_df = dgidb_gene_df.loc[dgidb_gene_df["claim_primary_status"]]
num_primary_claim = len(primary_claim_df)
num_primary_claim

64034

#### <a id='toc1_1_2_22_'></a>[How many gene group labels are primary symbols?](#toc0_)

In [96]:
dgidb_gene_df["name_primary_status"] = (
    dgidb_gene_df["gene_name"].astype(str).isin(hgnc_ensg_ncbi_gene_symbol_set)
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False,True,True
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False,True,True
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False,False,True
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False,True,True

In [97]:
dgidb_gene_df["name_primary_status"].value_counts()

name_primary_status
True     77778
False     2456
Name: count, dtype: int64

In [98]:
primary_name_df = dgidb_gene_df.loc[dgidb_gene_df["name_primary_status"]]
num_primary_name = len(primary_name_df)
num_primary_name

77778

In [99]:
not_primary_group_name_df = dgidb_gene_df.loc[~dgidb_gene_df["name_primary_status"]]
not_primary_group_name_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
75376,LOC102723996,Gene Symbol,ncbigene:102723996,LOC102723996,GO,10-Apr-24,False,False,False,False
78051,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,HGNC,20240408,False,False,False,False
78052,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,Ensembl,111,False,False,False,False
78053,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,NCBI,20240410,False,False,False,False
78054,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,Pharos,10-Apr-24,False,False,False,False

#### <a id='toc1_1_2_23_'></a>[How many gene group labels are alias symbols?](#toc0_)

In [100]:
dgidb_gene_df["name_alias_status"] = dgidb_gene_df["gene_name"].isin(
    hgnc_ensg_ncbi_alias_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False,True,True,False
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True,True,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False,True,True,False
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False,False,True,False
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False,True,True,False

In [101]:
dgidb_gene_df["name_alias_status"].value_counts()

name_alias_status
False    72203
True      8031
Name: count, dtype: int64

In [102]:
alias_name_df = dgidb_gene_df.loc[dgidb_gene_df["name_alias_status"]]
num_alias_name = len(alias_name_df)
num_alias_name

8031

In [103]:
print("Calmbp1" in hgnc_ensg_ncbi_alias_symbol_set)

True

#### <a id='toc1_1_2_24_'></a>[How many claims are alias symbols?](#toc0_)

In [104]:
dgidb_gene_df["claim_alias_status"] = dgidb_gene_df["gene_claim_name"].isin(
    hgnc_ensg_ncbi_alias_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False,True,True,False,False
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True,True,True,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False,True,True,False,False
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False,False,True,False,True
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False,True,True,False,False

In [105]:
dgidb_gene_df["claim_alias_status"].value_counts()

claim_alias_status
False    74637
True      5597
Name: count, dtype: int64

In [106]:
alias_claims_df = dgidb_gene_df.loc[dgidb_gene_df["claim_alias_status"]]
num_alias_claims = len(alias_claims_df)
num_alias_claims

5597

#### <a id='toc1_1_2_25_'></a>[How many claims that were normalized into non-primary symbol labeled groups are alias symbols?](#toc0_)

In [107]:
dgidb_gene_df["claim_alias_status"] = dgidb_gene_df["gene_claim_name"].isin(
    hgnc_ensg_ncbi_alias_symbol_set
)
alias_claim_not_primary_group_name_df = dgidb_gene_df.loc[
    dgidb_gene_df["claim_alias_status"] & ~dgidb_gene_df["name_primary_status"]
]
alias_claim_not_primary_group_name_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status
2249,HCA1,Gene Symbol,ncbigene:266790,HCA1,dGene,27-Jun-13,True,True,False,False,True,True
3251,USP17L,Gene Symbol,ncbigene:100862847,USP17L,dGene,27-Jun-13,False,False,False,False,True,True
5920,ALDA,Gene Name,ncbigene:112694756,LOC112694756,DrugBank,5.1.12,False,False,False,False,False,True
15424,CYP3A,Gene Name,ncbigene:1574,CYP3A,NCI,14-Sep-17,False,False,False,False,True,True
16482,CYP3A,Gene Name,ncbigene:1574,CYP3A,PharmGKB,4/5/24,False,False,False,False,True,True
27217,SIK1B,Gene Symbol,ncbigene:102724428,LOC102724428,GO,10-Apr-24,False,False,False,False,False,True
31884,SIK1B,Gene Symbol,ncbigene:102724428,LOC102724428,Pharos,10-Apr-24,False,False,False,False,False,True
36686,HCA1,Gene Symbol,ncbigene:266790,HCA1,NCBI,20240410,True,True,False,False,True,True
38737,USP17L,Gene Symbol,ncbigene:100862847,USP17L,NCBI,20240410,False,False,False,False,True,True
42309,HPT,Gene Symbol,ncbigene:3258,HPT,NCBI,20240410,False,False,False,False,True,True
42310,HPT,Gene Name,ncbigene:3258,HPT,DrugBank,5.1.12,False,False,False,False,True,True
49186,ADAL,Gene Symbol,hgnc:31853,ADAL,HGNC,20240408,False,False,False,False,True,True
49187,ADAL,Gene Symbol,hgnc:31853,ADAL,Ensembl,111,False,False,False,False,True,True
49188,ADAL,Gene Symbol,hgnc:31853,ADAL,NCBI,20240410,False,False,False,False,True,True
51788,CYP3A,Gene Symbol,ncbigene:1574,CYP3A,NCBI,20240410,False,False,False,False,True,True
55006,ACT,Gene Symbol,ncbigene:389036,ACT,NCBI,20240410,True,True,False,False,True,True
56883,CNA1,Gene Symbol,ncbigene:1255,CNA1,NCBI,20240410,False,False,False,False,True,True
57009,BCL5,Gene Symbol,ncbigene:603,BCL5,NCBI,20240410,False,False,False,False,True,True
57053,CCA1,Gene Symbol,ncbigene:878,CCA1,NCBI,20240410,False,False,False,False,True,True
57147,AMCN,Gene Symbol,ncbigene:261,AMCN,NCBI,20240410,False,False,False,False,True,True
57279,COD2,Gene Symbol,ncbigene:1275,COD2,NCBI,20240410,False,False,False,False,True,True
57327,ERV1,Gene Symbol,ncbigene:2085,ERV1,NCBI,20240410,True,True,False,False,True,True
57390,ATD,Gene Symbol,ncbigene:465,ATD,NCBI,20240410,True,True,False,False,True,True
66195,OA1,Gene Symbol,ncbigene:474285,OA1,NCBI,20240410,False,False,False,False,True,True
66196,OA1,Gene Symbol,ncbigene:474285,OA1,dGene,27-Jun-13,False,False,False,False,True,True
73831,FNZ,Gene Symbol,ncbigene:2345,FNZ,NCBI,20240410,False,False,False,False,True,True
74494,FCP1,Gene Symbol,ncbigene:2221,FCP1,NCBI,20240410,False,False,False,False,True,True
74536,FEB2,Gene Symbol,ncbigene:2234,FEB2,NCBI,20240410,False,False,False,False,True,True
74541,BCGF1,Gene Symbol,ncbigene:588,BCGF1,NCBI,20240410,False,False,False,False,True,True
78051,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,HGNC,20240408,False,False,False,False,True,True
78052,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,Ensembl,111,False,False,False,False,True,True
78053,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,NCBI,20240410,False,False,False,False,True,True
78054,CSNKA2IP,Gene Symbol,hgnc:53637,CSNKA2IP,Pharos,10-Apr-24,False,False,False,False,True,True

#### <a id='toc1_1_2_26_'></a>[How many not normalized claims are alias symbols?](#toc0_)

In [108]:
alias_claim_null_name_df = dgidb_gene_df.loc[
    dgidb_gene_df["claim_alias_status"] & dgidb_gene_df["gene_name"].isnull()
]
len(alias_claim_null_name_df)

0

#### <a id='toc1_1_2_27_'></a>[How many gene group labels are not primary, alias symbols, or null?](#toc0_)

In [109]:
other_name_df = dgidb_gene_df.loc[
    ~dgidb_gene_df["name_alias_status"]
    & ~dgidb_gene_df["name_primary_status"]
    & ~dgidb_gene_df["gene_name"].isnull()
]
num_other_name = len(other_name_df)
num_other_name

267

#### <a id='toc1_1_2_28_'></a>[How many claims are not primary, alias symbols, or null?](#toc0_)

In [110]:
other_claim_df = dgidb_gene_df.loc[
    ~dgidb_gene_df["claim_alias_status"] & ~dgidb_gene_df["claim_primary_status"]
]
num_other_claim = len(other_claim_df)
num_other_claim

15411

#### <a id='toc1_1_2_29_'></a>[How many claims are primary and alias symbols?](#toc0_)

In [111]:
primaryandalias_claim_df = dgidb_gene_df.loc[
    dgidb_gene_df["claim_alias_status"] & dgidb_gene_df["claim_primary_status"]
]
num_primaryandalias_claim = len(primaryandalias_claim_df)
num_primaryandalias_claim

4808

#### <a id='toc1_1_2_30_'></a>[How many primary symbol claims are normalized into non-primary gene group labels?](#toc0_)

In [112]:
claim_true_name_false_df = dgidb_gene_df.loc[
    dgidb_gene_df["claim_primary_status"] & ~dgidb_gene_df["name_primary_status"]
]
claim_true_name_false_df

Empty DataFrame
Columns: [gene_claim_name, nomenclature, concept_id, gene_name, source_db_name, source_db_version, claim_ambiguous_status, name_ambiguous_status, claim_primary_status, name_primary_status, name_alias_status, claim_alias_status]
Index: []

In [113]:
len(claim_true_name_false_df)

0

### <a id='toc1_1_3_'></a>[Summary](#toc0_)

#### <a id='toc1_1_3_1_'></a>[Normalization Rates](#toc0_)

In [114]:
normalization_index = "Normalized", "Not Normalized", "Total"
normalization_summary = {
    "Number of Claims": [
        num_normalized_claims,
        num_not_normalized_claims,
        num_total_claims,
    ]
}
normalization_summary_df = pd.DataFrame(
    normalization_summary, index=normalization_index
)
normalization_summary_df

                Number of Claims
Normalized                 78090
Not Normalized              2144
Total                      80234

#### <a id='toc1_1_3_2_'></a>[Types of Claim Symbols](#toc0_)

- Primary and Alias symbols are not exclusive as some primary symbols are used as aliases (alias-primary collisions)
- Other does not include any Primary or Alias symbols
- Ambiguous symbols can be either Primary or Alias

In [115]:
claim_index = "Primary", "Alias", "Other", "Ambiguous", "Total"
claim_summary = {
    "Number of Claims": [
        num_primary_claim,
        num_alias_claims,
        num_other_claim,
        num_ambiguous_claim,
        num_total_claims,
    ]
}
claim_summary_df = pd.DataFrame(claim_summary, index=claim_index)
claim_summary_df

           Number of Claims
Primary               64034
Alias                  5597
Other                 15411
Ambiguous              4661
Total                 80234

#### <a id='toc1_1_3_3_'></a>[Types of Normalizations (gene group labels claims are being normliazed into)](#toc0_)

In [116]:
gene_group_index = "Primary", "Alias", "Null", "Other", "Ambiguous", "Total"
gene_group_summary = {
    "Number of Claims": [
        num_primary_name,
        num_alias_name,
        num_not_normalized_claims,
        num_other_name,
        num_ambiguous_name,
        num_total_claims,
    ]
}
gene_group_summary_df = pd.DataFrame(gene_group_summary, index=gene_group_index)
gene_group_summary_df

           Number of Claims
Primary               77778
Alias                  8031
Null                   2144
Other                   267
Ambiguous              5526
Total                 80234