**Table of contents**<a id='toc0_'></a>    
- [ENSG](#toc1_)    
    - [How many total unique gene records are there in Ensembl](#toc1_1_1_)    
    - [Identify alias-alias collision symbols](#toc1_1_2_)    
- [HGNC](#toc2_)    
    - [How many total unique gene records are there in HGNC](#toc2_1_1_)    
    - [Identify alias-alias collision symbols](#toc2_1_2_)    
- [NCBI Info](#toc3_)    
    - [How many total unique gene records are there in NCBI Gene](#toc3_1_1_)    
    - [Identify alias-alias collision symbols](#toc3_1_2_)    
- [Merge to create Alias-Alias Collision Table- On Primary Gene Symbol](#toc4_)    
- [Merge to create Alias-Alias Collision Table- On Alias Symbol](#toc5_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [465]:
import pandas as pd
import numpy as np
import plotly.express as px

In [466]:
def create_aa_collision_df(subset_genes_xxxx_df: pd.DataFrame, merged_alias_xxxx_df: pd.DataFrame, source: str) -> pd.DataFrame:
    """ CASE INSENSITIVE COLLISIONS
    Create a df of alias-alias collision symbols 

    :param subset_genes_xxxx_df: Processed df of gene records
    :param source: Representation of the source of the gene records
    :return: A df of genes that share an alias with another gene
    """

    dup_alias = subset_genes_xxxx_df.copy()
    dup_alias = dup_alias.dropna(subset=["alias_symbol"])
    dup_alias["alias_symbol_upper"] = dup_alias["alias_symbol"].str.upper()

    #Find alias_symbols that are shared by multiple different gene_symbols
    dup_alias = (
        dup_alias.groupby('alias_symbol_upper')['gene_symbol']
        .nunique()
        .reset_index()
    )
    #Keep only alias_symbols linked to more than one gene
    dup_alias = dup_alias[dup_alias['gene_symbol'] > 1]['alias_symbol_upper']

    #Filter the original df for those alias collisions
    aa_collision_xxxx_df = subset_genes_xxxx_df.copy()
    aa_collision_xxxx_df["alias_symbol_upper"] = aa_collision_xxxx_df["alias_symbol"].str.upper()
    aa_collision_xxxx_df = aa_collision_xxxx_df[aa_collision_xxxx_df['alias_symbol_upper'].isin(dup_alias)]
    aa_collision_xxxx_df = aa_collision_xxxx_df.rename(
    columns={"alias_symbol_upper": "collision"})
    aa_collision_xxxx_df = aa_collision_xxxx_df.drop("alias_symbol", axis=1)

    aa_collision_xxxx_df = aa_collision_xxxx_df.sort_values("collision")

    #Add a source tag for future merging efforts
    aa_collision_xxxx_df["source"] = str(source)
    aa_collision_xxxx_df.to_csv(f'../output/single_alias_aa_collision_{source.lower()}_df.csv', index=True)

    #Create a secondary collision df that merges the alias symbols for each record
    columns_map = {
    'ENSG': ['NCBI_ID', 'HGNC_ID'],
    'HGNC': ['NCBI_ID', 'ENSG_ID'],
    'NCBI': ['HGNC_ID', 'ENSG_ID']
    }
    cols_of_interest = columns_map.get(source, [])

    merged_alias_aa_collision_xxxx_df = aa_collision_xxxx_df.drop(columns=cols_of_interest)

    merged_alias_aa_collision_xxxx_df = pd.merge(
        merged_alias_aa_collision_xxxx_df,
        merged_alias_xxxx_df[[f"{source}_ID"] + cols_of_interest + ['alias_symbol']],
        on=[f"{source}_ID"],
        how="left"
    )
    #Convert the df into a csv
    merged_alias_aa_collision_xxxx_df.to_csv(f'../output/merged_alias_aa_collision_{source.lower()}_df.csv', index=True)

    return merged_alias_aa_collision_xxxx_df.head()

In [467]:
# def create_aa_collision_df(subset_genes_xxxx_df: pd.DataFrame, merged_alias_xxxx_df: pd.DataFrame, source: str) -> pd.DataFrame:
#     """CASE SENSITIVE COLLISIONS
#     Create a df of alias-alias collision symbols 

#     :param subset_genes_xxxx_df: Processed df of gene records
#     :param source: Representation of the source of the gene records
#     :return: A df of genes that share an alias with another gene
#     """
#     #Find alias_symbols that are shared by multiple different gene_symbols
#     dup_alias = (
#         subset_genes_xxxx_df.groupby('alias_symbol')['gene_symbol']
#         .nunique()
#         .reset_index()
#     )
#     #Keep only alias_symbols linked to more than one gene
#     dup_alias = dup_alias[dup_alias['gene_symbol'] > 1]['alias_symbol']

#     #Filter the original df for those alias collisions
#     aa_collision_xxxx_df = subset_genes_xxxx_df[subset_genes_xxxx_df['alias_symbol'].isin(dup_alias)].copy()
#     aa_collision_xxxx_df = aa_collision_xxxx_df.rename(
#     columns={"alias_symbol": "collision"})

#     aa_collision_xxxx_df = aa_collision_xxxx_df.sort_values("collision")

#     #Add a source tag for future merging efforts
#     aa_collision_xxxx_df["source"] = str(source)
#     aa_collision_xxxx_df.to_csv(f'../output/single_alias_aa_collision_{source.lower()}_df.csv', index=True)

#     #Create a secondary collision df that merges the alias symbols for each record
#     columns_map = {
#     'ENSG': ['NCBI_ID', 'HGNC_ID'],
#     'HGNC': ['NCBI_ID', 'ENSG_ID'],
#     'NCBI': ['HGNC_ID', 'ENSG_ID']
#     }
#     cols_of_interest = columns_map.get(source, [])

#     merged_alias_aa_collision_xxxx_df = aa_collision_xxxx_df.drop(columns=cols_of_interest)

#     merged_alias_aa_collision_xxxx_df = pd.merge(
#         merged_alias_aa_collision_xxxx_df,
#         merged_alias_xxxx_df[[f"{source}_ID"] + cols_of_interest + ['alias_symbol']],
#         on=[f"{source}_ID"],
#         how="left"
#     )
#     #Convert the df into a csv
#     merged_alias_aa_collision_xxxx_df.to_csv(f'../output/merged_alias_aa_collision_{source.lower()}_df.csv', index=True)

#     return merged_alias_aa_collision_xxxx_df.head()

# <a id='toc1_'></a>[ENSG](#toc0_)

In [468]:
mini_ensg_df = pd.read_csv(
    "../output/mini_ensg_df.csv", index_col=0
)

In [469]:
subset_genes_ensg_df = pd.read_csv(
    "../output/subset_genes_ensg_df.csv", index_col=[0])

In [470]:
merged_alias_ensg_df = pd.read_csv(
    "../output/merged_alias_ensg_df.csv", index_col=[0])

### <a id='toc1_1_1_'></a>[How many total unique gene records are there in Ensembl](#toc0_)

In [471]:
gene_record_set_ensg = set(mini_ensg_df['ENSG_ID'])
gene_record_count_ensg = len(gene_record_set_ensg)
gene_record_count_ensg

48401

In [472]:
dup_alias = subset_genes_ensg_df.copy()
dup_alias = dup_alias.dropna(subset=["alias_symbol"])
dup_alias["alias_symbol_upper"] = dup_alias["alias_symbol"].str.upper()

#Find alias_symbols that are shared by multiple different gene_symbols
dup_alias = (
    dup_alias.groupby('alias_symbol_upper')['gene_symbol']
    .nunique()
    .reset_index()
)
#Keep only alias_symbols linked to more than one gene
dup_alias = dup_alias[dup_alias['gene_symbol'] > 1]['alias_symbol_upper']
dup_alias

117         2F1
222      60B8AG
255        87U6
264         9G8
276          A1
          ...
54728      ZIP4
54994    ZNF422
55249      ZNT8
55282      ZRC1
55351     ZYG11
Name: alias_symbol_upper, Length: 1615, dtype: object

In [473]:
dup_alias_id = (
    subset_genes_ensg_df.groupby('alias_symbol')["ENSG_ID"]
    .nunique()
    .reset_index()
)

In [474]:
dup_alias_id = dup_alias_id[dup_alias_id['ENSG_ID'] > 1]

In [475]:
dup_alias_id.iloc[1000:1060]

     alias_symbol  ENSG_ID
8728        CIRL1        2
8772         CK20        2
8773         CK23        2
8787        CKB-8        2
8788         CKB1        9
8791        CKB12        2
8793         CKB2        7
8795         CKB7        3
8796         CKB8        2
8827        CKMT1        2
8830        CKR-1        2
8840         CKS1        2
8844     CKTSF1B1        3
8848        CL-11       33
8849         CL-2       32
8851        CL-39       33
8852        CL-42       33
8853        CL-43        3
8854        CL-49       13
8855         CL-5       37
8856         CL-6       32
8867         CLA1        2
8869        CLA20        2
8870        CLAMP        2
8871         CLAN        2
8879       CLAPA2        3
8908         CLC2        2
8913        CLCA3        2
8917       CLCNL1        7
8925       CLDN21        2
8926        CLDNL        2
8956     CLECSF13        2
8967          CLF        2
8970          CLG        2
8987        CLIM1        2
8992         CLIP        4
9010          CLM        2
9013         CLM7        2
9015         CLMF        2
9034          CLP        3
9040         CLPA        2
9043      CLPSMCR        2
9045      CLR11.1        3
9056      CLR19.4       10
9061      CLR19.9       10
9076         CLU1        2
9079         CMAH        2
9103         CMG1        2
9115         CMIR        2
9133       CMKRL1        2
9136         CML2        2
9146        CMPD2        2
9152   CMRF-35-H9        2
9153     CMRF-35A        2
9154       CMRF35        2
9155      CMRF35A        2
9156     CMRF35A4        2
9157      CMRF35H        2
9166         CMT2        2
9211          CN1        2

In [476]:
mini_ensg_df.loc[mini_ensg_df["alias_symbol"] == "ADTAB"]

               ENSG_ID      NCBI_ID   HGNC_ID alias_symbol gene_symbol
31521  ENSG00000281385  GENE ID:161  HGNC:562        ADTAB       AP2A2
31874  ENSG00000280759  GENE ID:161  HGNC:562        ADTAB       AP2A2
91841  ENSG00000183020  GENE ID:161  HGNC:562        ADTAB       AP2A2

In [477]:
a3galnt_example_df = mini_ensg_df.loc[mini_ensg_df["alias_symbol"] == "A3GALNT"]
a3galnt_example_df

               ENSG_ID        NCBI_ID     HGNC_ID alias_symbol gene_symbol
13817  ENSG00000281879     GENE ID:28     HGNC:79      A3GALNT         ABO
36875  ENSG00000148288  GENE ID:26301  HGNC:20460      A3GALNT       GBGT1
37023  ENSG00000175164     GENE ID:28     HGNC:79      A3GALNT         ABO

In [478]:
dup_alias_symbol = (
    subset_genes_ensg_df.groupby('alias_symbol')["gene_symbol"]
    .nunique()
    .reset_index()
)

In [479]:
#Keep only alias_symbols linked to more than one gene
dup_alias_symbol = dup_alias_symbol[dup_alias_symbol['gene_symbol'] > 1]
dup_alias_symbol

      alias_symbol  gene_symbol
117            2F1            2
222         60B8AG            2
255           87U6            2
264            9G8            2
276             A1            4
...            ...          ...
54752         ZIP4            2
55018       ZNF422            2
55273         ZNT8            2
55306         ZRC1            2
55375        ZYG11            2

[1614 rows x 2 columns]

### <a id='toc1_1_2_'></a>[Identify alias-alias collision symbols](#toc0_)

In [480]:
create_aa_collision_df(subset_genes_ensg_df, merged_alias_ensg_df, source="ENSG")

,ENSG_ID,gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000139187,KLRG1,2F1,ENSG,GENE ID:10219,HGNC:6380,"2F1,CLEC15A,MAFA,MAFA-L"
1,ENSG00000005022,SLC25A5,2F1,ENSG,GENE ID:292,HGNC:10991,"2F1,ANT2,T2,T3"
2,ENSG00000163220,S100A9,60B8AG,ENSG,GENE ID:6280,HGNC:10499,"60B8AG,CAGB,CFAG,CGLB,LIAG,MAC387,MIF,MRP-14,M..."
3,ENSG00000143546,S100A8,60B8AG,ENSG,GENE ID:6279,HGNC:10498,"60B8AG,CAGA,CFAG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,ENSG00000206832,RNU6V,87U6,ENSG,NaN,HGNC:10230,"87U6,LH87"

In [481]:
merged_alias_aa_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ensg_df.csv", index_col=[0])
merged_alias_aa_collision_ensg_df

,ENSG_ID,gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000139187,KLRG1,2F1,ENSG,GENE ID:10219,HGNC:6380,"2F1,CLEC15A,MAFA,MAFA-L"
1,ENSG00000005022,SLC25A5,2F1,ENSG,GENE ID:292,HGNC:10991,"2F1,ANT2,T2,T3"
2,ENSG00000163220,S100A9,60B8AG,ENSG,GENE ID:6280,HGNC:10499,"60B8AG,CAGB,CFAG,CGLB,LIAG,MAC387,MIF,MRP-14,M..."
3,ENSG00000143546,S100A8,60B8AG,ENSG,GENE ID:6279,HGNC:10498,"60B8AG,CAGA,CFAG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,ENSG00000206832,RNU6V,87U6,ENSG,NaN,HGNC:10230,"87U6,LH87"
...,...,...,...,...,...,...,...
4727,ENSG00000164756,SLC30A8,ZNT8,ENSG,GENE ID:169026,HGNC:20303,"ZNT-8,ZNT8"
4728,ENSG00000170385,SLC30A1,ZRC1,ENSG,GENE ID:7779,HGNC:11012,"ZNT1,ZRC1"
4729,ENSG00000196660,SLC30A10,ZRC1,ENSG,GENE ID:55532,HGNC:25355,"DKFZP547M236,ZNT-10,ZNT10,ZNT8,ZRC1"
4730,ENSG00000203995,ZYG11A,ZYG11,ENSG,GENE ID:440590,HGNC:32058,ZYG11
4731,ENSG00000162378,ZYG11B,ZYG11,ENSG,GENE ID:79699,HGNC:25820,"FLJ13456,ZYG11"

In [482]:
merged_alias_aa_collision_ensg_df.loc[merged_alias_aa_collision_ensg_df["gene_symbol"] == "ABO"]

,ENSG_ID,gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
19,ENSG00000281879,ABO,A3GALNT,ENSG,GENE ID:28,HGNC:79,"A3GALNT,A3GALT1"
21,ENSG00000175164,ABO,A3GALNT,ENSG,GENE ID:28,HGNC:79,"A3GALNT,A3GALT1"

How many ambiguous symbols result from alias-alias collisions?

In [483]:
aa_collision_ambiguous_symbol_set_ensg = set(merged_alias_aa_collision_ensg_df["collision"])
aa_collision_ambiguous_symbol_count_ensg = len(aa_collision_ambiguous_symbol_set_ensg)
aa_collision_ambiguous_symbol_count_ensg

1615

How many records have at least one alias-alias collision (alias that matches another record's alias gene symbol)?

In [484]:
aa_record_set_ensg = set(merged_alias_aa_collision_ensg_df["ENSG_ID"])
aa_record_count_ensg = len(aa_record_set_ensg)
aa_record_count_ensg

3784

# <a id='toc2_'></a>[HGNC](#toc0_)

In [485]:
mini_hgnc_df = pd.read_csv(
    "../output/mini_hgnc_df.csv"
)

In [486]:
subset_genes_hgnc_df = pd.read_csv(
    "../output/subset_genes_hgnc_df.csv", index_col=[0])

In [487]:
merged_alias_hgnc_df = pd.read_csv(
    "../output/merged_alias_hgnc_df.csv", index_col=[0])

### <a id='toc2_1_2_'></a>[Identify alias-alias collision symbols](#toc0_)

In [488]:
create_aa_collision_df(subset_genes_hgnc_df, merged_alias_hgnc_df, source="HGNC")

,HGNC_ID,gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:10991,SLC25A5,2F1,HGNC,GENE ID:292,ENSG00000005022,"2F1,T2,T3"
1,HGNC:6380,KLRG1,2F1,HGNC,GENE ID:10219,ENSG00000139187,"2F1,CLEC15A,MAFA,MAFA-L"
2,HGNC:10499,S100A9,60B8AG,HGNC,GENE ID:6280,ENSG00000163220,"60B8AG,CGLB,LIAG,MAC387,MIF,MRP-14,MRP14,NIF,P..."
3,HGNC:10498,S100A8,60B8AG,HGNC,GENE ID:6279,ENSG00000143546,"60B8AG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,HGNC:4387,GNAI3,87U6,HGNC,GENE ID:2773,ENSG00000065135,87U6

In [489]:
merged_alias_aa_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_aa_collision_hgnc_df.csv", index_col=[0])
merged_alias_aa_collision_hgnc_df

,HGNC_ID,gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:10991,SLC25A5,2F1,HGNC,GENE ID:292,ENSG00000005022,"2F1,T2,T3"
1,HGNC:6380,KLRG1,2F1,HGNC,GENE ID:10219,ENSG00000139187,"2F1,CLEC15A,MAFA,MAFA-L"
2,HGNC:10499,S100A9,60B8AG,HGNC,GENE ID:6280,ENSG00000163220,"60B8AG,CGLB,LIAG,MAC387,MIF,MRP-14,MRP14,NIF,P..."
3,HGNC:10498,S100A8,60B8AG,HGNC,GENE ID:6279,ENSG00000143546,"60B8AG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,HGNC:4387,GNAI3,87U6,HGNC,GENE ID:2773,ENSG00000065135,87U6
...,...,...,...,...,...,...,...
2817,HGNC:20672,PHF8,ZNF422,HGNC,GENE ID:23133,ENSG00000172943,"JHDM1F,KDM7B,KIAA1111,ZNF422"
2818,HGNC:25355,SLC30A10,ZNT8,HGNC,GENE ID:55532,ENSG00000196660,"DKFZp547M236,ZNT10,ZNT8,ZRC1,ZnT-10"
2819,HGNC:20303,SLC30A8,ZNT8,HGNC,GENE ID:169026,ENSG00000164756,"ZNT8,ZnT-8"
2820,HGNC:11012,SLC30A1,ZRC1,HGNC,GENE ID:7779,ENSG00000170385,ZRC1
2821,HGNC:25355,SLC30A10,ZRC1,HGNC,GENE ID:55532,ENSG00000196660,"DKFZp547M236,ZNT10,ZNT8,ZRC1,ZnT-10"

How many ambiguous symbols result from alias-alias collisions?

In [490]:
aa_collision_ambiguous_symbol_set_hgnc = set(merged_alias_aa_collision_hgnc_df["collision"])
aa_collision_ambiguous_symbol_count_hgnc = len(aa_collision_ambiguous_symbol_set_hgnc)
aa_collision_ambiguous_symbol_count_hgnc

1230

How many records have at least one alias-alias collision (alias that matches another record's alias gene symbol)?

In [491]:
aa_record_set_hgnc = set(merged_alias_aa_collision_hgnc_df["HGNC_ID"])
aa_record_count_hgnc = len(aa_record_set_hgnc)
aa_record_count_hgnc

2482

# <a id='toc3_'></a>[NCBI Info](#toc0_)

In [492]:
mini_ncbi_df = pd.read_csv(
    "../output/mini_ncbi_df.csv", index_col=[0]
)

In [493]:
subset_genes_ncbi_df = pd.read_csv(
    "../output/subset_genes_ncbi_df.csv", index_col=[0])

In [494]:
merged_alias_ncbi_df = pd.read_csv(
    "../output/merged_alias_ncbi_df.csv", index_col=[0])

### <a id='toc3_1_2_'></a>[Identify alias-alias collision symbols](#toc0_)

In [495]:
create_aa_collision_df(subset_genes_ncbi_df, merged_alias_ncbi_df, source="NCBI")

,NCBI_ID,gene_symbol,collision,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:657,BMPR1A,10Q23DEL,NCBI,HGNC:1076,ENSG00000107779,"10q23del,ACVRLK3,ALK-3,ALK3,BMPR-1A,CD292,SKR5"
1,GENE ID:5728,PTEN,10Q23DEL,NCBI,HGNC:9588,ENSG00000171862,"10q23del,BZS,CWS1,DEC,GLM2,MHAM,MMAC1,PTEN1,PT..."
2,GENE ID:239,ALOX12,12-LOX,NCBI,HGNC:429,ENSG00000108839,"12-LOX,12S-LOX,LOG12"
3,GENE ID:246,ALOX15,12-LOX,NCBI,HGNC:433,ENSG00000161905,"12-LOX,15-LOX,15-LOX-1,LOG15"
4,GENE ID:1645,AKR1C1,20-ALPHA-HSD,NCBI,HGNC:384,ENSG00000187134,"2-ALPHA-HSD,20-ALPHA-HSD,C9,DD1,DD1/DD2,DDH,DD..."

In [496]:
merged_alias_aa_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ncbi_df.csv", index_col=[0])
merged_alias_aa_collision_ncbi_df

,NCBI_ID,gene_symbol,collision,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:657,BMPR1A,10Q23DEL,NCBI,HGNC:1076,ENSG00000107779,"10q23del,ACVRLK3,ALK-3,ALK3,BMPR-1A,CD292,SKR5"
1,GENE ID:5728,PTEN,10Q23DEL,NCBI,HGNC:9588,ENSG00000171862,"10q23del,BZS,CWS1,DEC,GLM2,MHAM,MMAC1,PTEN1,PT..."
2,GENE ID:239,ALOX12,12-LOX,NCBI,HGNC:429,ENSG00000108839,"12-LOX,12S-LOX,LOG12"
3,GENE ID:246,ALOX15,12-LOX,NCBI,HGNC:433,ENSG00000161905,"12-LOX,15-LOX,15-LOX-1,LOG15"
4,GENE ID:1645,AKR1C1,20-ALPHA-HSD,NCBI,HGNC:384,ENSG00000187134,"2-ALPHA-HSD,20-ALPHA-HSD,C9,DD1,DD1/DD2,DDH,DD..."
...,...,...,...,...,...,...,...
8792,GENE ID:55532,SLC30A10,ZRC1,NCBI,HGNC:25355,ENSG00000196660,"HMDPC,HMNDYT1,ZNT10,ZNT8,ZRC1,ZnT-10"
8793,GENE ID:5194,PEX13,ZWS,NCBI,HGNC:8855,ENSG00000162928,"NALD,PBD11A,PBD11B,ZWS"
8794,GENE ID:5189,PEX1,ZWS,NCBI,HGNC:8850,ENSG00000127980,"HMLR1,PBD1A,PBD1B,ZWS,ZWS1"
8795,GENE ID:79699,ZYG11B,ZYG11,NCBI,HGNC:25820,ENSG00000162378,ZYG11
8796,GENE ID:440590,ZYG11A,ZYG11,NCBI,HGNC:32058,ENSG00000203995,ZYG11

How many ambiguous symbols result from alias-alias collisions?

In [497]:
aa_collision_ambiguous_symbol_set_ncbi = set(merged_alias_aa_collision_ncbi_df["collision"])
aa_collision_ambiguous_symbol_count_ncbi = len(aa_collision_ambiguous_symbol_set_ncbi)
aa_collision_ambiguous_symbol_count_ncbi

3648

How many records have at least one alias-alias collision (alias that matches another record's alias gene symbol)?

In [498]:
aa_record_set_ncbi = set(merged_alias_aa_collision_ncbi_df["NCBI_ID"])
aa_record_count_ncbi = len(aa_record_set_ncbi)
aa_record_count_ncbi

5964

# <a id='toc4_'></a>[Merge to create Alias-Alias Collision Table- On Primary Gene Symbol](#toc0_)

In [499]:
merged_aa_collision_gene_df = pd.concat(
    [
        merged_alias_aa_collision_hgnc_df[["gene_symbol", "alias_symbol", "ENSG_ID", "collision", "source"]],
        merged_alias_aa_collision_ncbi_df[["gene_symbol", "alias_symbol", "ENSG_ID", "collision", "source"]],
        merged_alias_aa_collision_ensg_df[["gene_symbol", "alias_symbol", "ENSG_ID", "collision", "source"]],
    ]
)
merged_aa_collision_gene_df

,gene_symbol,alias_symbol,ENSG_ID,collision,source
0,SLC25A5,"2F1,T2,T3",ENSG00000005022,2F1,HGNC
1,KLRG1,"2F1,CLEC15A,MAFA,MAFA-L",ENSG00000139187,2F1,HGNC
2,S100A9,"60B8AG,CGLB,LIAG,MAC387,MIF,MRP-14,MRP14,NIF,P...",ENSG00000163220,60B8AG,HGNC
3,S100A8,"60B8AG,CGLA,MRP-8,MRP8,P8,S100-A8",ENSG00000143546,60B8AG,HGNC
4,GNAI3,87U6,ENSG00000065135,87U6,HGNC
...,...,...,...,...,...
4727,SLC30A8,"ZNT-8,ZNT8",ENSG00000164756,ZNT8,ENSG
4728,SLC30A1,"ZNT1,ZRC1",ENSG00000170385,ZRC1,ENSG
4729,SLC30A10,"DKFZP547M236,ZNT-10,ZNT10,ZNT8,ZRC1",ENSG00000196660,ZRC1,ENSG
4730,ZYG11A,ZYG11,ENSG00000203995,ZYG11,ENSG
4731,ZYG11B,"FLJ13456,ZYG11",ENSG00000162378,ZYG11,ENSG

In [500]:
merged_aa_collision_gene_df.to_csv(
    "../output/merged_aa_collision_gene_df.csv", index=False
)

In [501]:
merged_aa_collision_gene_df.loc[merged_aa_collision_gene_df.collision == "ALP"]

,gene_symbol,alias_symbol,ENSG_ID,collision,source
84,ATRNL1,"ALP,FLJ45344,KIAA0534",ENSG00000107518,ALP,HGNC
85,PDLIM3,ALP,ENSG00000154553,ALP,HGNC
86,SLPI,"ALK1,ALP,BLPI,HUSI,HUSI-I,WAP4,WFDC4",ENSG00000124107,ALP,HGNC
87,ASRGL1,"ALP,ALP1,FLJ22316",ENSG00000162174,ALP,HGNC
88,CCL27,"ALP,CTACK,CTAK,ESkine,ILC,PESKY,skinkine",ENSG00000213927,ALP,HGNC
263,ASRGL1,"ALP,ALP1,CRASH",ENSG00000162174,ALP,NCBI
264,SLPI,"ALK1,ALP,BLPI,HUSI,HUSI-I,MPI,WAP4,WFDC4",ENSG00000124107,ALP,NCBI
265,PDLIM3,ALP,ENSG00000154553,ALP,NCBI
266,NAT10,"ALP,Kre33,NET43",ENSG00000135372,ALP,NCBI
267,ALPP,"ALP,ALPI,IAP,PALP,PLAP,PLAP-1",ENSG00000163283,ALP,NCBI
268,CCL27,"ALP,CTACK,CTAK,ESKINE,ILC,PESKY,SCYA27",ENSG00000213927,ALP,NCBI
269,ATRNL1,"ALP,bA338L11.1,bA454H24.1",ENSG00000107518,ALP,NCBI
141,ASRGL1,"ALP,ALP1,FLJ22316",ENSG00000162174,ALP,ENSG
142,CCL27,"ALP,CTACK,CTAK,ESKINE,ILC,PESKY,SCYA27,SKINKINE",ENSG00000213927,ALP,ENSG
143,SLPI,"ALK1,ALP,BLPI,HUSI,HUSI-I,WAP4,WFDC4",ENSG00000124107,ALP,ENSG
144,ATRNL1,"ALP,FLJ45344,KIAA0534",ENSG00000107518,ALP,ENSG
145,PDLIM3,ALP,ENSG00000154553,ALP,ENSG