**Table of contents**<a id='toc0_'></a>    
- [What is the set of ambiguous symbols per source?](#toc1_1_)    
    - [Define Functions](#toc1_1_1_)    
    - [ENSG](#toc1_1_2_)    
    - [HGNC](#toc1_1_3_)    
    - [NCBI](#toc1_1_4_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## <a id='toc1_1_'></a>[What is the set of ambiguous symbols per source?](#toc0_)

Need this to create a better histogram figure. Current one only shows the distribution of ambiguous symbols created by alias-alias collisions by source. I want to be able to illustrate how the ambiguous symbols in each source (created by alias-alias and alias-primary collisions) are shared.

In [1]:
import pandas as pd
import plotly.express as px
from collections import Counter

### <a id='toc1_1_1_'></a>[Define Functions](#toc0_)

In [2]:
def combine_columns(df, columns_to_combine, columns_to_keep, new_name, columns_to_drop):
    """Combine multiple columns into one while keeping associated data attached.
    Use this function when the columns to combine are easier to list 
    than the columns not to combine.
    
    :param df: The DataFrame containing the columns to be combined
    :param columns_to_combine: List of column names to combine into one
    :param columns_to_keep: List of columns to keep in the final DataFrame
    :param new_name: The name of the new combined column
    :param columns_to_drop: List of columns to drop from the final DataFrame
    :return: A new DataFrame with combined columns and selected columns retained
    """
    og_df = df.copy()

    combined_dfs = []

    # Loop through each column in columns_to_combine and create a new DataFrame
    for col in columns_to_combine:
        temp_df = og_df[list(set([col] + columns_to_keep))].copy()
        temp_df[new_name] = temp_df[col]
        combined_dfs.append(temp_df)

    df_combined = pd.concat(combined_dfs, ignore_index=True)
    df_combined.drop(columns_to_drop, axis=1, inplace=True)
    df_combined.drop_duplicates(inplace=True)
    
    return df_combined

In [3]:
def create_ambiguous_symbol_histogram(XXXX_ambiguous_symbol_counts: pd.DataFrame, source: str, XXXX_ambiguous_symbol_set_count: int):
    """Create a histogram of the frequencies at which aliases are shared

    :param aa_collision_gene_xxxx_df: A df of alias-alias collisions organized by primary gene symbol
    :param source: Representation of the source of the gene records
    :param xxxx_alias_count: Number of aliases total in the source
    :return: A histogram of the percentage of aliases that are shared between 2 genes, 3 genes, and so on
    """

    #Count the frequency at which aliases are shared 
    XXXX_ambiguous_symbol_counts_distribution_df = XXXX_ambiguous_symbol_counts.pivot_table(
    index=["symbol_counts"], aggfunc="size"
    )
    XXXX_ambiguous_symbol_counts_distribution_df = XXXX_ambiguous_symbol_counts_distribution_df.reset_index()
    XXXX_ambiguous_symbol_counts_distribution_df.rename(columns={0: "num_collision_symbol"}, inplace=True)
    XXXX_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"] = (
        XXXX_ambiguous_symbol_counts_distribution_df["num_collision_symbol"] / XXXX_ambiguous_symbol_set_count
    ) * 100

    #Convert to csv
    XXXX_ambiguous_symbol_counts_distribution_df.to_csv(f'../output/ambiguous_symbol_{source}_distribution_df.csv',index=False)

    #Create histogram df 
    
    xxxx_symbol_count_histogram_df = XXXX_ambiguous_symbol_counts_distribution_df.drop(
    "num_collision_symbol", axis=1)

    #Convert to csv
    xxxx_symbol_count_histogram_df.to_csv(f'../output/{source}_ambiguous_symbol_count_histogram_df.csv',index=False)

    return px.bar(xxxx_symbol_count_histogram_df, x="symbol_counts", y="percent_collision_symbol")

### <a id='toc1_1_2_'></a>[ENSG](#toc0_)

import file with ambiguous symbols resulting from alias-alias collisions

In [4]:
merged_alias_aa_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ensg_df.csv")
merged_alias_aa_collision_ensg_df

,ENSG_ID,collision,primary_gene_symbol,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000139187,2F1,KLRG1,ENSG,GENE ID:10219,HGNC:6380,"2F1,CLEC15A,MAFA,MAFA-L"
1,ENSG00000005022,2F1,SLC25A5,ENSG,GENE ID:292,HGNC:10991,"2F1,ANT2,T2,T3"
2,ENSG00000163220,60B8AG,S100A9,ENSG,GENE ID:6280,HGNC:10499,"60B8AG,CAGB,CFAG,CGLB,LIAG,MAC387,MIF,MRP-14,M..."
3,ENSG00000143546,60B8AG,S100A8,ENSG,GENE ID:6279,HGNC:10498,"60B8AG,CAGA,CFAG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,ENSG00000206832,87U6,RNU6V,ENSG,NaN,HGNC:10230,"87U6,LH87"
...,...,...,...,...,...,...,...
4727,ENSG00000164756,ZNT8,SLC30A8,ENSG,GENE ID:169026,HGNC:20303,"ZNT-8,ZNT8"
4728,ENSG00000170385,ZRC1,SLC30A1,ENSG,GENE ID:7779,HGNC:11012,"ZNT1,ZRC1"
4729,ENSG00000196660,ZRC1,SLC30A10,ENSG,GENE ID:55532,HGNC:25355,"DKFZP547M236,ZNT-10,ZNT10,ZNT8,ZRC1"
4730,ENSG00000203995,ZYG11,ZYG11A,ENSG,GENE ID:440590,HGNC:32058,ZYG11
4731,ENSG00000162378,ZYG11,ZYG11B,ENSG,GENE ID:79699,HGNC:25820,"FLJ13456,ZYG11"

In [5]:
aa_collision_alias_ensg_set = set(
    merged_alias_aa_collision_ensg_df["collision"]
)
len(aa_collision_alias_ensg_set)

1617

import file with ambiguous symbols resulting from alias-primary collisions

In [6]:
ap_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ensg_df.csv")
ap_collision_ensg_df

,ENSG_ID,primary_gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000283293,RN7SK,7SK,ENSG,GENE ID:125050,HGNC:10037,7SK
1,ENSG00000057252,SOAT1,ACAT1,ENSG,GENE ID:6646,HGNC:11177,"ACAT,ACAT1,SOAT,STAT"
2,ENSG00000167780,SOAT2,ACAT2,ENSG,GENE ID:8435,HGNC:11178,ACAT2
3,ENSG00000004779,NDUFAB1,ACP1,ENSG,GENE ID:4706,HGNC:7694,"ACP,ACP1,FASN2A,SDAP"
4,ENSG00000220267,ACTBP8,ACTBP2,ENSG,NaN,HGNC:141,ACTBP2
...,...,...,...,...,...,...,...
762,ENSG00000197961,ZNF121,ZNF20,ENSG,GENE ID:7675,HGNC:12904,"D19S204,ZHC32,ZNF20"
763,ENSG00000110315,RNF141,ZNF230,ENSG,GENE ID:50862,HGNC:21159,"ZFP26,ZNF230"
764,ENSG00000188801,ZNF322P1,ZNF322,ENSG,NaN,HGNC:14003,"ZNF322,ZNF322B"
765,ENSG00000103994,ZNF106,ZNF474,ENSG,GENE ID:64397,HGNC:12886,"SH3BP3,ZFP106,ZNF474"
766,ENSG00000184517,ZFP1,ZNF475,ENSG,GENE ID:162239,HGNC:23328,"FLJ34243,ZNF475"

In [7]:
ap_collision_ensg_df.loc[ap_collision_ensg_df["collision"] == "SKI"]

,ENSG_ID,primary_gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
635,ENSG00000054392,HHAT,SKI,ENSG,GENE ID:55733,HGNC:18270,"FLJ10724,GUP2,MART-2,MART2,RASP,SIT,SKI,SKN"
636,ENSG00000280680,HHAT,SKI,ENSG,GENE ID:55733,HGNC:18270,"FLJ10724,GUP2,MART-2,MART2,RASP,SIT,SKI,SKN"

In [8]:
ap_collision_alias_ensg_set = set(
    ap_collision_ensg_df["collision"]
)
len(ap_collision_alias_ensg_set)

606

combine sets to create set of ambiguous symbols for ENSG

In [9]:
ensg_ambiguous_symbol_set = aa_collision_alias_ensg_set.union(
    ap_collision_alias_ensg_set
)
ensg_ambiguous_symbol_set_count = len(ensg_ambiguous_symbol_set)
ensg_ambiguous_symbol_set_count

2165

In [10]:
lowercased = [s.lower() for s in ensg_ambiguous_symbol_set]

duplicates = {k: v for k, v in Counter(lowercased).items() if v > 1}

print(duplicates)

{'feta': 2, 'c2orf27b': 2}

In [11]:
both_collision_ensg_set = aa_collision_alias_ensg_set & ap_collision_alias_ensg_set
len(both_collision_ensg_set)

58

In [12]:
only_aa_collision_alias_ensg_set = aa_collision_alias_ensg_set - both_collision_ensg_set
len(only_aa_collision_alias_ensg_set)

1559

In [13]:
only_ap_collision_alias_ensg_set = ap_collision_alias_ensg_set - both_collision_ensg_set
len(only_ap_collision_alias_ensg_set)

548

In [14]:
subset_genes_ensg_df = pd.read_csv(
        ("../output/subset_genes_ensg_df.csv"),dtype={"NCBI_ID": str,"HGNC_ID":str})

In [15]:
ensg_df = subset_genes_ensg_df.copy()
ensg_df['primary_gene_symbol_upper'] = ensg_df['primary_gene_symbol'].str.upper()
ensg_df.drop(["primary_gene_symbol"], axis=1, inplace=True)
ensg_df['alias_symbol'] = ensg_df['alias_symbol'].str.upper()
ensg_df = ensg_df.drop_duplicates(subset=['primary_gene_symbol_upper', 'alias_symbol'], keep='first')
ensg_df

,ENSG_ID,NCBI_ID,HGNC_ID,alias_symbol,primary_gene_symbol_upper
0,ENSG00000210049,NaN,HGNC:7481,MTTF,MT-TF
1,ENSG00000210049,NaN,HGNC:7481,TRNF,MT-TF
2,ENSG00000211459,NaN,HGNC:7470,12S,MT-RNR1
3,ENSG00000211459,NaN,HGNC:7470,MOTS-C,MT-RNR1
4,ENSG00000211459,NaN,HGNC:7470,MTRNR1,MT-RNR1
...,...,...,...,...,...
95019,ENSG00000197989,GENE ID:85028,HGNC:30062,LINC00100,SNHG12
95020,ENSG00000197989,GENE ID:85028,HGNC:30062,PNAS-123,SNHG12
95021,ENSG00000229388,NaN,HGNC:52502,LINC01715,TAF12-DT
95022,ENSG00000274978,GENE ID:26824,HGNC:10108,RNU11-1,RNU11
95023,ENSG00000274978,GENE ID:26824,HGNC:10108,U11,RNU11

In [16]:
ensg_df.loc[ensg_df["alias_symbol"] == "MTTF"]

           ENSG_ID NCBI_ID    HGNC_ID alias_symbol primary_gene_symbol_upper
0  ENSG00000210049     NaN  HGNC:7481         MTTF                     MT-TF

make a general symbol column with primary and alias symbols

In [17]:
ensg_df = combine_columns(ensg_df, ["primary_gene_symbol_upper", "alias_symbol"], ["primary_gene_symbol_upper", "ENSG_ID", "HGNC_ID","NCBI_ID"], "symbol", "alias_symbol")
ensg_df

,HGNC_ID,ENSG_ID,primary_gene_symbol_upper,NCBI_ID,symbol
0,HGNC:7481,ENSG00000210049,MT-TF,NaN,MT-TF
2,HGNC:7470,ENSG00000211459,MT-RNR1,NaN,MT-RNR1
5,HGNC:7500,ENSG00000210077,MT-TV,NaN,MT-TV
7,HGNC:7471,ENSG00000210082,MT-RNR2,NaN,MT-RNR2
10,HGNC:7490,ENSG00000209082,MT-TL1,NaN,MT-TL1
...,...,...,...,...,...
147837,HGNC:30062,ENSG00000197989,SNHG12,GENE ID:85028,LINC00100
147838,HGNC:30062,ENSG00000197989,SNHG12,GENE ID:85028,PNAS-123
147839,HGNC:52502,ENSG00000229388,TAF12-DT,NaN,LINC01715
147840,HGNC:10108,ENSG00000274978,RNU11,GENE ID:26824,RNU11-1
147841,HGNC:10108,ENSG00000274978,RNU11,GENE ID:26824,U11

In [18]:
ensg_df.loc[ensg_df["primary_gene_symbol_upper"] == "MT-TF"]

         HGNC_ID          ENSG_ID primary_gene_symbol_upper NCBI_ID symbol
0      HGNC:7481  ENSG00000210049                     MT-TF     NaN  MT-TF
73921  HGNC:7481  ENSG00000210049                     MT-TF     NaN   MTTF
73922  HGNC:7481  ENSG00000210049                     MT-TF     NaN   TRNF

use list of ambiguous symbols and ensg_combined_concept_ids_df to create a histogram of how many genes share ambiguous symbols

In [19]:
ensg_symbol_value_counts = ensg_df["symbol"].value_counts()

ensg_ambiguous_symbol_counts = ensg_symbol_value_counts[ensg_symbol_value_counts.index.isin(ensg_ambiguous_symbol_set)]
ensg_ambiguous_symbol_counts = ensg_ambiguous_symbol_counts.reset_index()
ensg_ambiguous_symbol_counts.columns = ["symbols", "symbol_counts"]
ensg_ambiguous_symbol_counts

     symbols  symbol_counts
0        MT1             11
1       HOX1             10
2        P40             10
3       HOX2              9
4        P14              9
...      ...            ...
2158   CDK4I              2
2159    G6PT              2
2160     L30              2
2161     PRP              2
2162     CNP              2

[2163 rows x 2 columns]

In [20]:
len(set(ensg_ambiguous_symbol_counts["symbols"]))

2163

In [21]:
ensg_ambiguous_symbol_set_count

2165

In [22]:
create_ambiguous_symbol_histogram(ensg_ambiguous_symbol_counts, "ENSG", ensg_ambiguous_symbol_set_count)

made in the create_ambiguous_symbol_histogram function

In [23]:
ensg_ambiguous_symbol_counts_distribution_df = pd.read_csv(
    "../output/ambiguous_symbol_ensg_distribution_df.csv")
ensg_ambiguous_symbol_counts_distribution_df

   symbol_counts  num_collision_symbol  percent_collision_symbol
0              2                  1837                 84.849885
1              3                   237                 10.946882
2              4                    49                  2.263279
3              5                    16                  0.739030
4              6                    13                  0.600462
5              7                     4                  0.184758
6              8                     2                  0.092379
7              9                     2                  0.092379
8             10                     2                  0.092379
9             11                     1                  0.046189

In [24]:
ensg_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"].sum()

99.90762124711317

In [25]:
# Filter out rows with symbol_counts < 6
less_than_six_ensg_ambiguous_symbol_counts_distribution_df = ensg_ambiguous_symbol_counts_distribution_df[ensg_ambiguous_symbol_counts_distribution_df["symbol_counts"] < 6].copy()

# Group all rows where symbol_counts >= 6
equal_more_than_six_ensg_ambiguous_symbol_counts_distribution_df = ensg_ambiguous_symbol_counts_distribution_df[ensg_ambiguous_symbol_counts_distribution_df["symbol_counts"] >= 6].agg({
    'num_collision_symbol': 'sum',
    'percent_collision_symbol': 'sum'
})

# Create a new row for '6+'
agg_row = pd.DataFrame({
    'symbol_counts': ['6+'],
    'num_collision_symbol': [equal_more_than_six_ensg_ambiguous_symbol_counts_distribution_df['num_collision_symbol']],
    'percent_collision_symbol': [equal_more_than_six_ensg_ambiguous_symbol_counts_distribution_df['percent_collision_symbol']]
})

# Concatenate and reset index
limited_ensg_ambiguous_symbol_counts_distribution_df = pd.concat([less_than_six_ensg_ambiguous_symbol_counts_distribution_df, agg_row], ignore_index=True)
limited_ensg_ambiguous_symbol_counts_distribution_df

  symbol_counts  num_collision_symbol  percent_collision_symbol
0             2                1837.0                 84.849885
1             3                 237.0                 10.946882
2             4                  49.0                  2.263279
3             5                  16.0                  0.739030
4            6+                  24.0                  1.108545

### <a id='toc1_1_3_'></a>[HGNC](#toc0_)

import file with ambiguous symbols resulting from alias-alias collisions

In [26]:
merged_alias_aa_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_aa_collision_hgnc_df.csv")
merged_alias_aa_collision_hgnc_df

,HGNC_ID,primary_gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:10991,SLC25A5,2F1,HGNC,GENE ID:292,ENSG00000005022,"2F1,T2,T3"
1,HGNC:6380,KLRG1,2F1,HGNC,GENE ID:10219,ENSG00000139187,"2F1,CLEC15A,MAFA,MAFA-L"
2,HGNC:10499,S100A9,60B8AG,HGNC,GENE ID:6280,ENSG00000163220,"60B8AG,CGLB,LIAG,MAC387,MIF,MRP-14,MRP14,NIF,P..."
3,HGNC:10498,S100A8,60B8AG,HGNC,GENE ID:6279,ENSG00000143546,"60B8AG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,HGNC:10230,RNU6V,87U6,HGNC,GENE ID:6071,ENSG00000206832,"87U6,LH87"
...,...,...,...,...,...,...,...
2817,HGNC:28393,SPATA2L,tamo,HGNC,GENE ID:124044,ENSG00000158792,"MGC26885,tamo"
2818,HGNC:1132,BTG3,tob55,HGNC,GENE ID:10950,ENSG00000154640,"ANA,ANA/BTG3,APRO4,tob55"
2819,HGNC:3818,FOXM1,trident,HGNC,GENE ID:2305,ENSG00000111206,"HFH-11,HNF-3,INS-1,MPHOSPH2,MPP2,TGT3,trident"
2820,HGNC:7494,MT-TP,trnP,HGNC,GENE ID:4571,ENSG00000210196,trnP
2821,HGNC:22197,AP5Z1,zeta,HGNC,GENE ID:9907,ENSG00000242802,"SPG48,zeta"

In [27]:
aa_collision_alias_hgnc_set = set(
    merged_alias_aa_collision_hgnc_df["collision"]
)
len(aa_collision_alias_hgnc_set)

1458

import file with ambiguous symbols resulting from alias-primary collisions

In [28]:
ap_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_ap_collision_hgnc_df.csv")
ap_collision_hgnc_df

,HGNC_ID,primary_gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:14947,PPP1R12C,AAVS1,HGNC,GENE ID:54776,ENSG00000125503,"AAVS1,DKFZP434D0412,MBS85,p84,p85"
1,HGNC:11177,SOAT1,ACAT1,HGNC,GENE ID:6646,ENSG00000057252,"ACAT,ACAT1"
2,HGNC:11178,SOAT2,ACAT2,HGNC,GENE ID:8435,ENSG00000167780,ACAT2
3,HGNC:1612,CCRL2,ACKR5,HGNC,GENE ID:9034,ENSG00000121797,"ACKR5,CKRX,CRAM-A,CRAM-B,HCR"
4,HGNC:7694,NDUFAB1,ACP1,HGNC,GENE ID:4706,ENSG00000004779,"ACP,ACP1,FASN2A,SDAP"
...,...,...,...,...,...,...,...
541,HGNC:3147,ECEL1,XCE,HGNC,GENE ID:9427,ENSG00000171551,"DINE,XCE"
542,HGNC:12904,ZNF121,ZNF20,HGNC,GENE ID:7675,ENSG00000197961,"ZHC32,ZNF20"
543,HGNC:21159,RNF141,ZNF230,HGNC,GENE ID:50862,ENSG00000110315,"ZFP26,ZNF230"
544,HGNC:12886,ZNF106,ZNF474,HGNC,GENE ID:64397,ENSG00000103994,"SH3BP3,ZNF474"
545,HGNC:23328,ZFP1,ZNF475,HGNC,GENE ID:162239,ENSG00000184517,"FLJ34243,ZNF475"

In [29]:
ap_collision_alias_hgnc_set = set(
    ap_collision_hgnc_df["collision"]
)
len(ap_collision_alias_hgnc_set)

492

combine lists without duplicates to create list of ambiguous symbols for HGNC

In [30]:
hgnc_ambiguous_symbol_set = aa_collision_alias_hgnc_set.union(
    ap_collision_alias_hgnc_set
)
hgnc_ambiguous_symbol_set_count = len(hgnc_ambiguous_symbol_set)
hgnc_ambiguous_symbol_set_count

1901

In [31]:
lowercased = [s.lower() for s in hgnc_ambiguous_symbol_set]

duplicates = {k: v for k, v in Counter(lowercased).items() if v > 1}

print(duplicates)

{'p105': 2, 'strap': 2, 'msp': 2, 'hcap': 2, 'nbr': 2, 'p150': 2, 'dsk2': 2, 'mal': 2, 'rts': 2, 'tasp': 2, 'p27': 2, 'ckb1': 2, 'pip1': 2, 'hb6': 2, 'p37': 2, 'p14': 2, 'galnac-t10': 2, 'feta': 2, 'chif': 2, 'srp40': 2, 'hsk1': 2, 'cx30.2': 2, 'p5': 2, 'rtp': 2, 'p58': 2, 'trnp': 2, 'p31': 2, 'zeta': 2, 'p63': 2, 'p34': 2, 'asc-1': 2, 'diva': 2, 'prp4': 2, 'p84': 2, 'p130': 2, 'p56': 2, 'sno': 2, 'ppiase': 2, 'p85': 2, 'aibp': 2, 'a2': 2, 'p18': 2, 'rcd1': 2, 'hcc-2': 2, 'gda': 2, 'wwp4': 2, 'pp1c': 2, 'sgt2': 2, 'p66': 2, 'cst': 3, 'cps1': 2, 'cl-11': 2, 'ac1': 2, 'cmg1': 2, 'vps55': 2, 'p19': 2, 'pad1': 2, 'dlc2': 2, 'arp11': 2, 'solo': 2, 'dcr2': 2, 'p97': 2, 'car2': 2, 'oat6': 2, 'cl-6': 2, 'hcg1': 2, 'ps2': 2, 'g16': 2, 'ha-2': 2, 'las1': 2, 'p24': 2, 'el32': 2, 'fbx30': 2, 'mink': 2, 'cdh7': 2, 'nip': 2, 'pr': 2, 'sara': 2, 'p62': 2, 'gp135': 2, 'p8mtcp1': 2, 'pit-1': 2, 'p35': 2, 'hbp': 2, 'mtr1': 2, 'inos': 2, 'sgii': 2, 'vma4': 2, 'car1': 2, 'p21': 2, 'igsf13': 2, 'kdap': 2, 'san': 2, 'fal1': 2, 'chp': 2, 'p1': 2, 'glut9': 2, 'arp10': 2, 'p48': 2, 'pcp': 2, 'mart2': 2, 'ap2': 2, 'dgk': 2, 'hed': 2, 'slt': 2, 'eos': 2, 'pseudo-ice': 2, 'p54': 2, 'csl': 2, 'orf26': 2, 'nap1': 2, 'cas1': 2, 'trident': 2, 'p76': 2, 'ang1': 2, 'p90': 2, 'h-plk': 2, 'mtr2': 2, 'prox': 2, 'p50': 2, 'mum2': 2, 'trbp': 2, 'eeg1': 2, 'esg1': 2, 'hpc2': 2, 'hrs': 2, 'cv2': 2, 'trad': 2, 'es1': 2, 'cnil': 2, 'nip1': 2, 'hb-1': 2, 'p60': 2, 'a1': 2, 'nabc1': 2, 'lgl1': 2, 'p40': 2, 'pc-1': 2, 'hcc-1': 2, 'ignt': 2, 'erf1': 2, 'trip': 2, 'smap': 2, 'arp4': 2, 'imp4': 2, 'p57': 2, 'beta2': 2, 'c5a': 2, 'npl3': 2, 'mast': 2, 'cd158k': 2, 'p28': 2, 'ctr1': 2, 'spp2': 2, 'pnutl3': 2, 'pac2': 2, 'nkx6.1': 2, 'cat1': 2, 'edg-2': 2, 'p51': 2, 'spc7': 2, 'zip2': 2, 'p29': 2, 'gig1': 2, 'p11': 2, 'pa': 2, 'p52': 2, 'cad': 2, 'vma5': 2, 'p600': 2, 'ang2': 2, 'mip1': 2, 'ha-1': 2, 'mss4': 2, 'prp2': 2, 'sps': 2, 'sep': 2, 'spn': 2, 'mtf': 3, 'cdc14b2': 2, 'p68': 2, 'miz': 2, 'a4': 2, 'lak': 2, 'fbl2': 2, 'sur2': 2, 'stx': 2, 'p15': 2, 'mip-2a': 2, 'doc-1': 2, 'sit': 2, 'vma6': 2, 'mint': 2, 'ubch8': 2, 'ccp1': 2, 'nag': 2, 'p47': 2, 'dip2': 2, 'p2': 2, 'p3': 2, 'ssc1': 2, 'gp39': 2, 'trif': 2, 'es31': 2, 'p8': 2, 'bub1a': 2, 'tob55': 2, 'hnrnp-g': 2, 'hspc105': 2, 'atx': 2, 'arp5': 2, 'p65': 2, 'lin-10': 2, 'arp1': 2, 'aha1': 2, 'ice': 2, 'minerva': 2, 'par-4': 2, 'fritz': 2, 'has1': 2, 'dkfzp434b204': 2, 'sema': 2, 'pop3': 2, 'pta1': 2, 'beta-4': 2, 'lca': 2}

In [32]:
both_collision_hgnc_set = aa_collision_alias_hgnc_set & ap_collision_alias_hgnc_set
len(both_collision_hgnc_set)

49

In [33]:
only_aa_collision_alias_hgnc_set = aa_collision_alias_hgnc_set - both_collision_hgnc_set
len(only_aa_collision_alias_hgnc_set)

1409

In [34]:
only_ap_collision_alias_hgnc_set = ap_collision_alias_hgnc_set - both_collision_hgnc_set
len(only_ap_collision_alias_hgnc_set)

443

In [35]:
subset_genes_hgnc_df = pd.read_csv(
        ("../output/subset_genes_hgnc_df.csv"),dtype={"NCBI_ID": str,"HGNC_ID":str})

In [36]:
hgnc_df = subset_genes_hgnc_df.copy()
hgnc_df['primary_gene_symbol_upper'] = hgnc_df['primary_gene_symbol'].str.upper()
hgnc_df.drop(["primary_gene_symbol"], axis=1, inplace=True)
hgnc_df['alias_symbol'] = hgnc_df['alias_symbol'].str.upper()
hgnc_df = hgnc_df.drop_duplicates(subset=['primary_gene_symbol_upper', 'alias_symbol'], keep='first')
hgnc_df

,HGNC_ID,alias_symbol,NCBI_ID,ENSG_ID,primary_gene_symbol_upper
0,HGNC:100,BNAC2,GENE ID:41,ENSG00000110881,ASIC1
1,HGNC:100,HBNAC2,GENE ID:41,ENSG00000110881,ASIC1
2,HGNC:10000,NaN,GENE ID:5999,ENSG00000117152,RGS4
3,HGNC:10001,NaN,GENE ID:8490,ENSG00000143248,RGS5
4,HGNC:10002,NaN,GENE ID:9628,ENSG00000182732,RGS6
...,...,...,...,...,...
66194,HGNC:9997,RGS-R,GENE ID:6004,ENSG00000143333,RGS16
66195,HGNC:9998,NaN,GENE ID:5997,ENSG00000116741,RGS2
66196,HGNC:9999,C2PA,GENE ID:5998,ENSG00000138835,RGS3
66197,HGNC:9999,FLJ20370,GENE ID:5998,ENSG00000138835,RGS3
66198,HGNC:9999,PDZ-RGS3,GENE ID:5998,ENSG00000138835,RGS3

make a general column with primary and alias symbols

In [37]:
hgnc_df = combine_columns(hgnc_df, ["primary_gene_symbol_upper", "alias_symbol"], ["primary_gene_symbol_upper", "ENSG_ID", "HGNC_ID","NCBI_ID"], "symbol", "alias_symbol")
hgnc_df

,HGNC_ID,ENSG_ID,primary_gene_symbol_upper,NCBI_ID,symbol
0,HGNC:100,ENSG00000110881,ASIC1,GENE ID:41,ASIC1
2,HGNC:10000,ENSG00000117152,RGS4,GENE ID:5999,RGS4
3,HGNC:10001,ENSG00000143248,RGS5,GENE ID:8490,RGS5
4,HGNC:10002,ENSG00000182732,RGS6,GENE ID:9628,RGS6
5,HGNC:10003,ENSG00000182901,RGS7,GENE ID:6000,RGS7
...,...,...,...,...,...
132325,HGNC:9997,ENSG00000143333,RGS16,GENE ID:6004,RGS-R
132326,HGNC:9998,ENSG00000116741,RGS2,GENE ID:5997,NaN
132327,HGNC:9999,ENSG00000138835,RGS3,GENE ID:5998,C2PA
132328,HGNC:9999,ENSG00000138835,RGS3,GENE ID:5998,FLJ20370
132329,HGNC:9999,ENSG00000138835,RGS3,GENE ID:5998,PDZ-RGS3

use list of ambiguous symbols and hgnc_combined_concept_ids_df to create a histogram of how many genes share ambiguous symbols

In [38]:
hgnc_symbol_value_counts = hgnc_df["symbol"].value_counts()

hgnc_ambiguous_symbol_counts = hgnc_symbol_value_counts[hgnc_symbol_value_counts.index.isin(hgnc_ambiguous_symbol_set)]
hgnc_ambiguous_symbol_counts = hgnc_ambiguous_symbol_counts.reset_index()
hgnc_ambiguous_symbol_counts.columns = ["symbols", "symbol_counts"]
hgnc_ambiguous_symbol_counts

       symbols  symbol_counts
0          P40             10
1          P14              9
2          P18              7
3          PAP              7
4          ASP              7
...        ...            ...
1600  IGFBP-3R              2
1601       SIN              2
1602       RHO              2
1603       MIO              2
1604      LAS1              2

[1605 rows x 2 columns]

In [39]:
len(set(hgnc_ambiguous_symbol_counts["symbols"]))

1605

In [40]:
hgnc_ambiguous_symbol_set_count

1901

In [41]:
create_ambiguous_symbol_histogram(hgnc_ambiguous_symbol_counts, "HGNC", hgnc_ambiguous_symbol_set_count)

In [42]:
hgnc_ambiguous_symbol_counts_distribution_df = pd.read_csv(
    "../output/ambiguous_symbol_hgnc_distribution_df.csv")
hgnc_ambiguous_symbol_counts_distribution_df

   symbol_counts  num_collision_symbol  percent_collision_symbol
0              2                  1347                 70.857443
1              3                   186                  9.784324
2              4                    40                  2.104156
3              5                    17                  0.894266
4              6                     9                  0.473435
5              7                     4                  0.210416
6              9                     1                  0.052604
7             10                     1                  0.052604

In [43]:
hgnc_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"].sum()

84.42924776433458

In [44]:
# Filter out rows with symbol_counts < 6
less_than_six_hgnc_ambiguous_symbol_counts_distribution_df = hgnc_ambiguous_symbol_counts_distribution_df[hgnc_ambiguous_symbol_counts_distribution_df["symbol_counts"] < 6].copy()

# Group all rows where symbol_counts >= 6
equal_more_than_six_hgnc_ambiguous_symbol_counts_distribution_df = hgnc_ambiguous_symbol_counts_distribution_df[hgnc_ambiguous_symbol_counts_distribution_df["symbol_counts"] >= 6].agg({
    'num_collision_symbol': 'sum',
    'percent_collision_symbol': 'sum'
})

# Create a new row for '6+'
agg_row = pd.DataFrame({
    'symbol_counts': ['6+'],
    'num_collision_symbol': [equal_more_than_six_hgnc_ambiguous_symbol_counts_distribution_df['num_collision_symbol']],
    'percent_collision_symbol': [equal_more_than_six_hgnc_ambiguous_symbol_counts_distribution_df['percent_collision_symbol']]
})

# Concatenate and reset index
limited_hgnc_ambiguous_symbol_counts_distribution_df = pd.concat([less_than_six_hgnc_ambiguous_symbol_counts_distribution_df, agg_row], ignore_index=True)
limited_hgnc_ambiguous_symbol_counts_distribution_df

  symbol_counts  num_collision_symbol  percent_collision_symbol
0             2                1347.0                 70.857443
1             3                 186.0                  9.784324
2             4                  40.0                  2.104156
3             5                  17.0                  0.894266
4            6+                  15.0                  0.789058

### <a id='toc1_1_4_'></a>[NCBI](#toc0_)

import file with ambiguous symbols resulting from alias-alias collisions

In [45]:
merged_alias_aa_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ncbi_df.csv")
merged_alias_aa_collision_ncbi_df

,NCBI_ID,primary_gene_symbol,collision,gene_type,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:657,BMPR1A,10q23del,protein-coding,NCBI,HGNC:1076,ENSG00000107779,"10q23del,ACVRLK3,ALK-3,ALK3,BMPR-1A,CD292,SKR5"
1,GENE ID:5728,PTEN,10q23del,protein-coding,NCBI,HGNC:9588,ENSG00000171862,"10q23del,BZS,CWS1,DEC,GLM2,MHAM,MMAC1,PTEN1,PT..."
2,GENE ID:239,ALOX12,12-LOX,protein-coding,NCBI,HGNC:429,ENSG00000108839,"12-LOX,12S-LOX,LOG12"
3,GENE ID:246,ALOX15,12-LOX,protein-coding,NCBI,HGNC:433,ENSG00000161905,"12-LOX,15-LOX,15-LOX-1,LOG15"
4,GENE ID:1645,AKR1C1,20-ALPHA-HSD,protein-coding,NCBI,HGNC:384,ENSG00000187134,"2-ALPHA-HSD,20-ALPHA-HSD,C9,DD1,DD1/DD2,DDH,DD..."
...,...,...,...,...,...,...,...,...
8792,GENE ID:100874116,EGFLAM-AS3,tbp1,ncRNA,NCBI,HGNC:41167,NaN,tbp1
8793,GENE ID:80222,TARS2,thrRS,protein-coding,NCBI,HGNC:30740,ENSG00000143374,"COXPD21,TARSL1,thrRS"
8794,GENE ID:3921,RPSA,uS2,protein-coding,NCBI,HGNC:6502,ENSG00000168028,"37LRP,67LR,ICAS,LAMBR,LAMR1,LBP,LBP/p40,LRP,LR..."
8795,GENE ID:9113,LATS1,wts,protein-coding,NCBI,HGNC:6514,ENSG00000131023,"WARTS,wts"
8796,GENE ID:9907,AP5Z1,zeta,protein-coding,NCBI,HGNC:22197,ENSG00000242802,"KIAA0415,SPG48,zeta"

In [46]:
aa_collision_alias_ncbi_set = set(
    merged_alias_aa_collision_ncbi_df["collision"]
)
len(aa_collision_alias_ncbi_set)

4031

import file with ambiguous symbols resulting from alias-primary collisions

In [47]:
ap_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ncbi_df.csv")
ap_collision_ncbi_df

,NCBI_ID,primary_gene_symbol,gene_type,collision,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:3494,IGHA2,other,A2M,NCBI,HGNC:5479,ENSG00000211890,A2M
1,GENE ID:54776,PPP1R12C,protein-coding,AAVS1,NCBI,HGNC:14947,ENSG00000125503,"AAVS1,LENG3,MBS85,p84,p85"
2,GENE ID:6646,SOAT1,protein-coding,ACAT1,NCBI,HGNC:11177,ENSG00000057252,"ACACT,ACAT,ACAT-1,ACAT1,SOAT,STAT"
3,GENE ID:8435,SOAT2,protein-coding,ACAT2,NCBI,HGNC:11178,ENSG00000167780,"ACACT2,ACAT2,ARGP2"
4,GENE ID:9034,CCRL2,protein-coding,ACKR5,NCBI,HGNC:1612,ENSG00000121797,"ACKR5,CKRX,CRAM,CRAM-A,CRAM-B,HCR"
...,...,...,...,...,...,...,...,...
1608,GENE ID:29903,CCDC106,protein-coding,ZNF581,NCBI,HGNC:30181,ENSG00000173581,"HSU79303,ZNF581"
1609,GENE ID:146540,ZNF785,protein-coding,ZNF688,NCBI,HGNC:26496,ENSG00000197162,ZNF688
1610,GENE ID:57829,ZP4,protein-coding,ZP1,NCBI,HGNC:15770,ENSG00000116996,"ZBP,ZP1,ZP1B,ZPB,ZPB2,Zp-4"
1611,GENE ID:55663,ZNF446,protein-coding,ZSCAN30,NCBI,HGNC:21036,ENSG00000083838,"ZKSCAN20,ZSCAN30,ZSCAN52"
1612,GENE ID:342357,ZKSCAN2,protein-coding,ZSCAN31,NCBI,HGNC:25677,ENSG00000155592,"ZNF694,ZSCAN31,ZSCAN34"

In [48]:
ap_collision_alias_ncbi_set = set(
    ap_collision_ncbi_df["collision"]
)
len(ap_collision_alias_ncbi_set)

1394

combine lists without duplicates to create list of ambiguous symbols for NCBI

In [49]:
ncbi_ambiguous_symbol_set = aa_collision_alias_ncbi_set.union(
    ap_collision_alias_ncbi_set
)
ncbi_ambiguous_symbol_set_count = len(ncbi_ambiguous_symbol_set)
ncbi_ambiguous_symbol_set_count

5256

In [50]:
lowercased = [s.lower() for s in ncbi_ambiguous_symbol_set]

duplicates = {k: v for k, v in Counter(lowercased).items() if v > 1}

print(duplicates)

{'p120(cas)': 2, 'hcap': 2, 'hc': 2, 'p150': 2, 'mic-1': 2, 'fbs1': 2, 'hp': 2, 'pap-alpha': 2, 'cx30.2': 2, 'galnac-t4': 2, 'not': 2, 'p160': 2, 'doc2': 2, 'camiii': 2, 'fceri': 2, 'p56': 2, 'sno': 2, 'h2b/s': 2, 'wwp4': 2, 'thrrs': 2, '5ptase': 2, 'hd6': 2, 'slim': 2, 'smt3a': 2, 'caf1b': 2, 'p125': 2, 'p39': 2, 'el32': 2, 'op2': 2, 'foxd4b': 2, 'p7': 2, 'mtr1': 2, 'camk': 2, 'vma4': 2, 'semg': 2, 'pk3': 2, 'c16orf15': 2, 'wts': 2, 'hos': 2, 'ccat': 2, 'p48': 2, 'p67': 2, 'natd': 2, 'hsp70': 2, 'osr1': 2, 'pseudo-ice': 2, 'c17orf1': 2, 'mib': 2, 'cas1': 2, 'p90': 2, 'hmr': 2, 'tan1': 2, 'lamr': 3, 'p49': 2, 'tar-5': 2, 'tasp': 2, 'ap2': 2, 'cn-ib': 2, 'p59': 2, 'tp55': 2, 'lgl1': 2, 'p40': 2, 'pact': 2, 'zeta': 2, 'hsp40': 2, 'crn7': 2, 'mona': 2, 'gda': 2, 'cacc': 2, 'us2': 2, 'npl3': 2, 'mast': 2, 'smap': 2, 'kdap': 2, 'mrd1': 2, 'pac2': 2, 'kv11.1': 2, 'spla2': 2, 'ckb1': 2, 'p51': 2, 'tra1': 2, 'spc7': 2, 'p29': 2, 'gig1': 2, 'imp4': 2, 'prp': 2, 'asprs': 2, 'ha-1': 2, 'stv1': 2, 'mink': 2, 'arb1': 2, 'cd158a': 2, 'sph1': 2, 'cnil': 2, 'apoc-iv': 2, 'p14': 2, 'hug-br1': 2, 'sara': 2, 'oat6': 2, 'cx59': 2, 'ccp1': 2, 'trb': 2, 'ranbp2l2': 2, 'gp39': 2, 'vma5': 2, 'serrs': 2, 'mtf': 2, 'p85': 2, 'mic10': 2, 'hn1': 2, 'nag': 2, 'kv10.1': 2, 'hspc105': 2, 'metrs': 2, 'arsb': 2, 'fib2': 2, 'p65': 2, 'hnrnp-g': 2, 'pit-1': 2, 'p64': 2, 'ses2': 2, 'bhlhb9': 2, 'apo-civ': 2, 'mer': 2, 'hk1': 2, 'cst': 2, 'a3a': 2, 'minerva': 2, 'sof1': 2, 'mena': 2, 'cypd': 2, 'dap1': 2, 'p11': 2, 'cps1': 2, 'tbp1': 2, 'gp135': 2, 'p45': 2, 'era': 2, 'sema': 2, 'nip': 2, 'mrp-2b': 2, 'mad3': 2, 'rpl7a': 2, 'leu2': 2, 'ppiase': 2, 'ranbp2l1': 2, 'vph1': 2, 'syn1a': 2, 'spn': 2, 'p50': 2, 'msr': 2, 'sen1': 2, 'mint': 2, 'fbl2': 2, 'hn2': 2, 'rhe': 2, 'gpibb': 2, 'mam-2': 2, 'hk3': 2, 'enh1': 2, 'eif-5a': 2, 'ac1': 2, 'met': 2, 'asc-1': 2, 'p120(ctn)': 2, 'cep110': 2, 'ssf-1': 2, 'htr': 2, 'p220': 2, 'hk2': 2, 'gp200-mr6': 2, 'gcom2': 2, 'p21': 2, 'p115': 2, 'p54': 2, 'stx': 2, 'pr1/pr2': 2, 'qps1': 2, 'p27': 2, 'p200': 2, 'vh': 2, 'mam-3': 2, 'rhogap2': 2, 'sodf': 2, 'srp40': 2, 'ngbr': 2, 'cx58': 2, 'p58': 2, 'p31': 2, 'enos': 2, 'fcri': 2, 'rnah': 2, 'p18': 2, 'lpcat': 2, 'vps55': 2, 'p19': 2, 'car2': 2, 'ps2': 2, 'cam': 4, 'pr': 2, 'mig-2': 2, 'solo': 2, 'p35': 2, 'feta': 2, 'car1': 2, 'lst-2': 2, 'el': 2, 'cn1b': 2, 'p73': 2, 'fal1': 2, 'hclp1': 2, 'eloa3c': 2, 'hsmad2': 2, 'cmg1': 2, 'mart2': 2, 'slt': 2, 'mrx15': 2, 'lysopafat': 2, 'cach': 2, 'dtr': 2, 'p33': 2, 'ccta': 2, 'hb-1': 2, 'sws': 2, 'ct12.1b': 2, 'vma10': 2, 'prox': 2, 'hsk1': 2, 'k-rev': 2, 'c5a': 2, 'p42': 2, 'ly-75': 2, 'spp2': 2, 'pnutl3': 2, 'edg-2': 2, 'bos1': 2, 'hapip': 2, 'pk': 2, 'p52': 2, 'p600': 2, 'mip1': 2, 'prp2': 2, 'retsdr2': 2, 'cdc14b2': 2, 'pxr1': 2, 'neu': 2, 'ced5': 2, 'kop': 2, 'sps': 2, 'a3': 2, 'dlc2': 2, 'p34': 2, 'p2': 2, 'ag3': 2, 'trif': 2, 'murf2': 2, 'bub1a': 2, 'par-4': 2, 'doc-1': 2, 'arp5': 2, 'p36': 2, 'lin-10': 2, 'mtr2': 2, 'arp1': 2, 'hed': 2, 'a3b': 2, 'sep': 2, 'p8': 2, 'gal-nac6s': 2, 'eif3-p110': 2, 'has1': 2, 'tctex4': 2, 'tah1': 2, 'lmo7b': 2, 'l1ag': 2, 'rcd1': 2, 'sgii': 2, 'tag': 2, 'rrp': 2, 'e1b': 2, 'p47': 2, 'p68': 2, 'rhpi': 2, 'pc-1': 2, 'h4f5': 2, 'imp5': 2, 'p23': 2, 'dnaj': 2, 'strap': 2, 'mal': 2, 'p37': 2, 'nac3': 2, 'p38': 2, 'p5': 2, 'rtp': 2, 'p140': 2, 'hies2': 2, 'zfp-91': 2, 'cdw32': 2, 'p84': 2, 'p100': 2, 'pp1c': 2, 'spt2': 2, 'p97': 2, 'hcg1': 2, 'fbx30': 2, 'cdh7': 2, 'l23a': 2, 'hbp': 2, 'p4': 2, 'nbr': 2, 'ep': 2, 'l10a': 2, 'hies6': 2, 'dgk': 2, 'csl': 3, 'orf26': 2, 'mum2': 2, 'lsk': 2, 'es1': 2, 'nifu': 2, 'a1': 2, 'p250': 2, 'hb1': 2, 'ranbp7': 2, 'arp4': 2, 'beta2': 2, 'ctr1': 2, 'delta': 2, 'pcp': 2, 'vma2': 2, 'caf1a': 2, 'rpl10p': 2, 'smt3b': 2, 'rbpi': 2, 'p62': 2, 'diva': 2, 'ignt': 2, 'p15': 2, 'gep': 2, 'mip-2a': 2, 'es31': 2, 'p16': 2, 'igsf13': 2, 'ssc1': 2, 'ice': 2, 'delta1': 2, 'atx': 2, 'dct1': 2, 'asnrs': 2, 'trip': 2, 'stip': 2, 'nsr1': 2, 'pta1': 2, 'h-plk': 2, 'pgs2': 2, 'pius': 2, 'ryr': 2, 'hoat4': 2, 'cyp-m': 2, 'p20-arc': 2, 'arp11': 2, 'las1': 2, 'il-1ra': 2, 'harc': 2, 'p1': 2, 'arp10': 2, 'nact': 2, 'cysrs': 2, 'p60': 2, 'p43': 2, 'p28': 2, 'acecs1': 2, 'efg': 2, 'mlt1': 2, 'p3': 2, 'env': 2, 'rpl17': 2, '20-alpha-hsd': 2, 'beta-4': 2}

In [51]:
both_collision_ncbi_set = aa_collision_alias_ncbi_set & ap_collision_alias_ncbi_set
len(both_collision_ncbi_set)

169

In [52]:
only_aa_collision_alias_ncbi_set = aa_collision_alias_ncbi_set - both_collision_ncbi_set
len(only_aa_collision_alias_ncbi_set)

3862

In [53]:
only_ap_collision_alias_ncbi_set = ap_collision_alias_ncbi_set - both_collision_ncbi_set
len(only_ap_collision_alias_ncbi_set)

1225

In [54]:
subset_genes_ncbi_df = pd.read_csv(
        ("../output/subset_genes_ncbi_df.csv"),dtype={"NCBI_ID": str,"HGNC_ID":str})

In [55]:
ncbi_df = subset_genes_ncbi_df.copy()
ncbi_df['primary_gene_symbol_upper'] = ncbi_df['primary_gene_symbol'].str.upper()
ncbi_df.drop(["primary_gene_symbol"], axis=1, inplace=True)
ncbi_df['alias_symbol'] = ncbi_df['alias_symbol'].str.upper()
ncbi_df = ncbi_df.drop_duplicates(subset=['primary_gene_symbol_upper', 'alias_symbol'], keep='first')
ncbi_df

,NCBI_ID,alias_symbol,gene_type,HGNC_ID,ENSG_ID,primary_gene_symbol_upper
0,GENE ID:1,A1B,protein-coding,HGNC:5,ENSG00000121410,A1BG
1,GENE ID:1,ABG,protein-coding,HGNC:5,ENSG00000121410,A1BG
2,GENE ID:1,GAB,protein-coding,HGNC:5,ENSG00000121410,A1BG
3,GENE ID:1,HYST2477,protein-coding,HGNC:5,ENSG00000121410,A1BG
4,GENE ID:2,A2MD,protein-coding,HGNC:7,ENSG00000175899,A2M
...,...,...,...,...,...,...
91350,GENE ID:141732005,NaN,ncRNA,HGNC:40064,NaN,ADCY2-AS1
91351,GENE ID:141732006,NaN,ncRNA,HGNC:41074,NaN,NSG2-AS1
91352,GENE ID:141732007,NaN,ncRNA,HGNC:58430,NaN,ST18-AS1
91353,GENE ID:141732008,NaN,ncRNA,HGNC:58437,NaN,MICAL2-AS1
91354,GENE ID:141732009,NaN,ncRNA,HGNC:40863,NaN,TRIM41-AS1

make a general symbol column with primary and alias symbols

In [56]:
ncbi_df = combine_columns(ncbi_df, ["primary_gene_symbol_upper", "alias_symbol"], ["primary_gene_symbol_upper", "ENSG_ID", "HGNC_ID","NCBI_ID"], "symbol", "alias_symbol")
ncbi_df

,HGNC_ID,ENSG_ID,primary_gene_symbol_upper,NCBI_ID,symbol
0,HGNC:5,ENSG00000121410,A1BG,GENE ID:1,A1BG
4,HGNC:7,ENSG00000175899,A2M,GENE ID:2,A2M
8,HGNC:7645,ENSG00000171428,NAT1,GENE ID:9,NAT1
12,HGNC:7646,ENSG00000156006,NAT2,GENE ID:10,NAT2
15,HGNC:15,NaN,NATP,GENE ID:11,NATP
...,...,...,...,...,...
182509,HGNC:40064,NaN,ADCY2-AS1,GENE ID:141732005,NaN
182510,HGNC:41074,NaN,NSG2-AS1,GENE ID:141732006,NaN
182511,HGNC:58430,NaN,ST18-AS1,GENE ID:141732007,NaN
182512,HGNC:58437,NaN,MICAL2-AS1,GENE ID:141732008,NaN
182513,HGNC:40863,NaN,TRIM41-AS1,GENE ID:141732009,NaN

use list of ambiguous symbols and ncbi_combined_concept_ids_df to create a histogram of how many genes share ambiguous symbols

In [57]:
ncbi_symbol_value_counts = ncbi_df["symbol"].value_counts()

ncbi_ambiguous_symbol_counts = ncbi_symbol_value_counts[ncbi_symbol_value_counts.index.isin(ncbi_ambiguous_symbol_set)]
ncbi_ambiguous_symbol_counts = ncbi_ambiguous_symbol_counts.reset_index()
ncbi_ambiguous_symbol_counts.columns = ["symbols", "symbol_counts"]
ncbi_ambiguous_symbol_counts

         symbols  symbol_counts
0             VH             37
1           H4C1             14
2           H4C3             14
3           H4C8             14
4          H4C12             14
...          ...            ...
4691      ACECS1              2
4692  TRY-GTA5-1              2
4693         IA4              2
4694  TRP-TGG3-4              2
4695  TRW-CCA3-1              2

[4696 rows x 2 columns]

In [58]:
create_ambiguous_symbol_histogram(ncbi_ambiguous_symbol_counts, "NCBI", ncbi_ambiguous_symbol_set_count)

In [59]:
ncbi_ambiguous_symbol_counts_distribution_df = pd.read_csv(
    "../output/ambiguous_symbol_ncbi_distribution_df.csv")
ncbi_ambiguous_symbol_counts_distribution_df

    symbol_counts  num_collision_symbol  percent_collision_symbol
0               2                  3858                 73.401826
1               3                   538                 10.235921
2               4                   141                  2.682648
3               5                    69                  1.312785
4               6                    31                  0.589802
5               7                    16                  0.304414
6               8                     5                  0.095129
7               9                     5                  0.095129
8              10                    12                  0.228311
9              11                     3                  0.057078
10             12                     2                  0.038052
11             14                    15                  0.285388
12             37                     1                  0.019026

In [60]:
ncbi_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"].sum()

89.34550989345506

In [61]:
# Filter out rows with symbol_counts < 6
less_than_six_ncbi_ambiguous_symbol_counts_distribution_df = ncbi_ambiguous_symbol_counts_distribution_df[ncbi_ambiguous_symbol_counts_distribution_df["symbol_counts"] < 6].copy()

# Group all rows where symbol_counts >= 6
equal_more_than_six_ncbi_ambiguous_symbol_counts_distribution_df = ncbi_ambiguous_symbol_counts_distribution_df[ncbi_ambiguous_symbol_counts_distribution_df["symbol_counts"] >= 6].agg({
    'num_collision_symbol': 'sum',
    'percent_collision_symbol': 'sum'
})

# Create a new row for '6+'
agg_row = pd.DataFrame({
    'symbol_counts': ['6+'],
    'num_collision_symbol': [equal_more_than_six_ncbi_ambiguous_symbol_counts_distribution_df['num_collision_symbol']],
    'percent_collision_symbol': [equal_more_than_six_ncbi_ambiguous_symbol_counts_distribution_df['percent_collision_symbol']]
})

# Concatenate and reset index
limited_ncbi_ambiguous_symbol_counts_distribution_df = pd.concat([less_than_six_ncbi_ambiguous_symbol_counts_distribution_df, agg_row], ignore_index=True)
limited_ncbi_ambiguous_symbol_counts_distribution_df

  symbol_counts  num_collision_symbol  percent_collision_symbol
0             2                3858.0                 73.401826
1             3                 538.0                 10.235921
2             4                 141.0                  2.682648
3             5                  69.0                  1.312785
4            6+                  90.0                  1.712329

In [62]:
ncbi_ensg_ambiguous_symbol_set = ncbi_ambiguous_symbol_set.union(
    ensg_ambiguous_symbol_set
)

In [63]:
ncbi_ensg_hgnc_ambiguous_symbol_set = ncbi_ensg_ambiguous_symbol_set.union(
    hgnc_ambiguous_symbol_set
)

In [64]:
ambiguous_symbol_set = ncbi_ensg_hgnc_ambiguous_symbol_set
len(ambiguous_symbol_set)

5525