**Table of contents**<a id='toc0_'></a>    
- [What is the set of ambiguous symbols per source?](#toc1_1_)    
    - [Define Functions](#toc1_1_1_)    
    - [ENSG](#toc1_1_2_)    
    - [HGNC](#toc1_1_3_)    
    - [NCBI](#toc1_1_4_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## <a id='toc1_1_'></a>[What is the set of ambiguous symbols per source?](#toc0_)

Need this to create a better histogram figure. Current one only shows the distribution of ambiguous symbols created by alias-alias collisions by source. I want to be able to illustrate how the ambiguous symbols in each source (created by alias-alias and alias-primary collisions) are shared.

In [420]:
import pandas as pd
import plotly.express as px
from collections import Counter

### <a id='toc1_1_1_'></a>[Define Functions](#toc0_)

In [421]:
def combine_columns(df, columns_to_combine, columns_to_keep, new_name, columns_to_drop):
    """Combine multiple columns into one while keeping associated data attached.
    Use this function when the columns to combine are easier to list 
    than the columns not to combine.
    
    :param df: The DataFrame containing the columns to be combined
    :param columns_to_combine: List of column names to combine into one
    :param columns_to_keep: List of columns to keep in the final DataFrame
    :param new_name: The name of the new combined column
    :param columns_to_drop: List of columns to drop from the final DataFrame
    :return: A new DataFrame with combined columns and selected columns retained
    """
    og_df = df.copy()

    combined_dfs = []

    # Loop through each column in columns_to_combine and create a new DataFrame
    for col in columns_to_combine:
        temp_df = og_df[list(set([col] + columns_to_keep))].copy()
        temp_df[new_name] = temp_df[col]
        combined_dfs.append(temp_df)

    df_combined = pd.concat(combined_dfs, ignore_index=True)
    df_combined.drop(columns_to_drop, axis=1, inplace=True)
    df_combined.drop_duplicates(inplace=True)
    
    return df_combined

In [422]:
def create_ambiguous_symbol_histogram(XXXX_ambiguous_symbol_counts: pd.DataFrame, source: str, XXXX_ambiguous_symbol_set_count: int):
    """Create a histogram of the frequencies at which aliases are shared

    :param aa_collision_gene_xxxx_df: A df of alias-alias collisions organized by primary gene symbol
    :param source: Representation of the source of the gene records
    :param xxxx_alias_count: Number of aliases total in the source
    :return: A histogram of the percentage of aliases that are shared between 2 genes, 3 genes, and so on
    """

    #Count the frequency at which aliases are shared 
    XXXX_ambiguous_symbol_counts_distribution_df = XXXX_ambiguous_symbol_counts.pivot_table(
    index=["symbol_counts"], aggfunc="size"
    )
    XXXX_ambiguous_symbol_counts_distribution_df = XXXX_ambiguous_symbol_counts_distribution_df.reset_index()
    XXXX_ambiguous_symbol_counts_distribution_df.rename(columns={0: "num_collision_symbol"}, inplace=True)
    XXXX_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"] = (
        XXXX_ambiguous_symbol_counts_distribution_df["num_collision_symbol"] / XXXX_ambiguous_symbol_set_count
    ) * 100

    #Convert to csv
    XXXX_ambiguous_symbol_counts_distribution_df.to_csv(f'../output/ambiguous_symbol_{source}_distribution_df.csv', index=True)

    #Create histogram df 
    
    xxxx_symbol_count_histogram_df = XXXX_ambiguous_symbol_counts_distribution_df.drop(
    "num_collision_symbol", axis=1)

    #Convert to csv
    xxxx_symbol_count_histogram_df.to_csv(f'../output/{source}_ambiguous_symbol_count_histogram_df.csv', index=True)

    return px.bar(xxxx_symbol_count_histogram_df, x="symbol_counts", y="percent_collision_symbol")

### <a id='toc1_1_2_'></a>[ENSG](#toc0_)

import file with ambiguous symbols resulting from alias-alias collisions

In [423]:
merged_alias_aa_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ensg_df.csv", index_col=[0])
merged_alias_aa_collision_ensg_df

,ENSG_ID,collision,gene_symbol,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000139187,2F1,KLRG1,ENSG,GENE ID:10219,HGNC:6380,"2F1,CLEC15A,MAFA,MAFA-L"
1,ENSG00000005022,2F1,SLC25A5,ENSG,GENE ID:292,HGNC:10991,"2F1,ANT2,T2,T3"
2,ENSG00000163220,60B8AG,S100A9,ENSG,GENE ID:6280,HGNC:10499,"60B8AG,CAGB,CFAG,CGLB,LIAG,MAC387,MIF,MRP-14,M..."
3,ENSG00000143546,60B8AG,S100A8,ENSG,GENE ID:6279,HGNC:10498,"60B8AG,CAGA,CFAG,CGLA,MRP-8,MRP8,P8,S100-A8"
4,ENSG00000065135,87U6,GNAI3,ENSG,GENE ID:2773,HGNC:4387,87U6
...,...,...,...,...,...,...,...
4721,ENSG00000164756,ZNT8,SLC30A8,ENSG,GENE ID:169026,HGNC:20303,"ZNT-8,ZNT8"
4722,ENSG00000196660,ZRC1,SLC30A10,ENSG,GENE ID:55532,HGNC:25355,"DKFZP547M236,ZNT-10,ZNT10,ZNT8,ZRC1"
4723,ENSG00000170385,ZRC1,SLC30A1,ENSG,GENE ID:7779,HGNC:11012,"ZNT1,ZRC1"
4724,ENSG00000162378,ZYG11,ZYG11B,ENSG,GENE ID:79699,HGNC:25820,"FLJ13456,ZYG11"
4725,ENSG00000203995,ZYG11,ZYG11A,ENSG,GENE ID:440590,HGNC:32058,ZYG11

In [424]:
aa_collision_alias_ensg_set = set(
    merged_alias_aa_collision_ensg_df["collision"]
)
len(aa_collision_alias_ensg_set)

1614

import file with ambiguous symbols resulting from alias-primary collisions

In [425]:
ap_collision_ensg_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ensg_df.csv", index_col=[0])
ap_collision_ensg_df

,ENSG_ID,gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
0,ENSG00000283293,RN7SK,7SK,ENSG,GENE ID:125050,HGNC:10037,7SK
1,ENSG00000057252,SOAT1,ACAT1,ENSG,GENE ID:6646,HGNC:11177,"ACAT,ACAT1,SOAT,STAT"
2,ENSG00000167780,SOAT2,ACAT2,ENSG,GENE ID:8435,HGNC:11178,ACAT2
3,ENSG00000004779,NDUFAB1,ACP1,ENSG,GENE ID:4706,HGNC:7694,"ACP,ACP1,FASN2A,SDAP"
4,ENSG00000220267,ACTBP8,ACTBP2,ENSG,NaN,HGNC:141,ACTBP2
...,...,...,...,...,...,...,...
806,ENSG00000197961,ZNF121,ZNF20,ENSG,GENE ID:7675,HGNC:12904,"D19S204,ZHC32,ZNF20"
807,ENSG00000110315,RNF141,ZNF230,ENSG,GENE ID:50862,HGNC:21159,"ZFP26,ZNF230"
808,ENSG00000188801,ZNF322P1,ZNF322,ENSG,NaN,HGNC:14003,"ZNF322,ZNF322B"
809,ENSG00000103994,ZNF106,ZNF474,ENSG,GENE ID:64397,HGNC:12886,"SH3BP3,ZFP106,ZNF474"
810,ENSG00000184517,ZFP1,ZNF475,ENSG,GENE ID:162239,HGNC:23328,"FLJ34243,ZNF475"

In [426]:
ap_collision_ensg_df.loc[ap_collision_ensg_df["collision"] == "SKI"]

,ENSG_ID,gene_symbol,collision,source,NCBI_ID,HGNC_ID,alias_symbol
662,ENSG00000054392,HHAT,SKI,ENSG,GENE ID:55733,HGNC:18270,"FLJ10724,GUP2,MART-2,MART2,RASP,SIT,SKI,SKN"
663,ENSG00000280680,HHAT,SKI,ENSG,GENE ID:55733,HGNC:18270,"FLJ10724,GUP2,MART-2,MART2,RASP,SIT,SKI,SKN"

In [427]:
ap_collision_alias_ensg_set = set(
    ap_collision_ensg_df["collision"]
)
len(ap_collision_alias_ensg_set)

606

combine sets to create set of ambiguous symbols for ENSG

In [428]:
ensg_ambiguous_symbol_set = aa_collision_alias_ensg_set.union(
    ap_collision_alias_ensg_set
)
ensg_ambiguous_symbol_set_count = len(ensg_ambiguous_symbol_set)
ensg_ambiguous_symbol_set_count

2162

In [487]:
lowercased = [s.lower() for s in ensg_ambiguous_symbol_set]

duplicates = {k: v for k, v in Counter(lowercased).items() if v > 1}

print(duplicates)

{}

In [429]:
both_collision_ensg_set = aa_collision_alias_ensg_set & ap_collision_alias_ensg_set
len(both_collision_ensg_set)

58

In [430]:
only_aa_collision_alias_ensg_set = aa_collision_alias_ensg_set - both_collision_ensg_set
len(only_aa_collision_alias_ensg_set)

1556

In [431]:
only_ap_collision_alias_ensg_set = ap_collision_alias_ensg_set - both_collision_ensg_set
len(only_ap_collision_alias_ensg_set)

548

In [432]:
subset_genes_ensg_df = pd.read_csv(
        ("../output/subset_genes_ensg_df.csv"), index_col=[0],dtype={"NCBI_ID": str,"HGNC_ID":str})

In [433]:
ensg_df = subset_genes_ensg_df.copy()
ensg_df['primary_gene_symbol'] = ensg_df['gene_symbol'].str.upper()
ensg_df.drop(["gene_symbol"], axis=1, inplace=True)
ensg_df['alias_symbol'] = ensg_df['alias_symbol'].str.upper()
ensg_df = ensg_df.drop_duplicates(subset=['primary_gene_symbol', 'alias_symbol'], keep='first')
ensg_df

,ENSG_ID,NCBI_ID,HGNC_ID,alias_symbol,primary_gene_symbol
0,ENSG00000210049,NaN,HGNC:7481,MTTF,MT-TF
1,ENSG00000210049,NaN,HGNC:7481,TRNF,MT-TF
2,ENSG00000211459,NaN,HGNC:7470,12S,MT-RNR1
3,ENSG00000211459,NaN,HGNC:7470,MOTS-C,MT-RNR1
4,ENSG00000211459,NaN,HGNC:7470,MTRNR1,MT-RNR1
...,...,...,...,...,...
133058,ENSG00000197989,GENE ID:85028,HGNC:30062,LINC00100,SNHG12
133059,ENSG00000197989,GENE ID:85028,HGNC:30062,PNAS-123,SNHG12
133060,ENSG00000229388,NaN,HGNC:52502,LINC01715,TAF12-DT
133062,ENSG00000274978,GENE ID:26824,HGNC:10108,RNU11-1,RNU11
133063,ENSG00000274978,GENE ID:26824,HGNC:10108,U11,RNU11

In [434]:
ensg_df.loc[ensg_df["alias_symbol"] == "MTTF"]

           ENSG_ID NCBI_ID    HGNC_ID alias_symbol primary_gene_symbol
0  ENSG00000210049     NaN  HGNC:7481         MTTF               MT-TF

make a general symbol column with primary and alias symbols

In [435]:
ensg_df = combine_columns(ensg_df, ["primary_gene_symbol", "alias_symbol"], ["primary_gene_symbol", "ENSG_ID", "HGNC_ID","NCBI_ID"], "symbol", "alias_symbol")
ensg_df

,primary_gene_symbol,NCBI_ID,HGNC_ID,ENSG_ID,symbol
0,MT-TF,NaN,HGNC:7481,ENSG00000210049,MT-TF
2,MT-RNR1,NaN,HGNC:7470,ENSG00000211459,MT-RNR1
5,MT-TV,NaN,HGNC:7500,ENSG00000210077,MT-TV
7,MT-RNR2,NaN,HGNC:7471,ENSG00000210082,MT-RNR2
10,MT-TL1,NaN,HGNC:7490,ENSG00000209082,MT-TL1
...,...,...,...,...,...
147837,SNHG12,GENE ID:85028,HGNC:30062,ENSG00000197989,LINC00100
147838,SNHG12,GENE ID:85028,HGNC:30062,ENSG00000197989,PNAS-123
147839,TAF12-DT,NaN,HGNC:52502,ENSG00000229388,LINC01715
147840,RNU11,GENE ID:26824,HGNC:10108,ENSG00000274978,RNU11-1
147841,RNU11,GENE ID:26824,HGNC:10108,ENSG00000274978,U11

In [436]:
ensg_df.loc[ensg_df["primary_gene_symbol"] == "MT-TF"]

      primary_gene_symbol NCBI_ID    HGNC_ID          ENSG_ID symbol
0                   MT-TF     NaN  HGNC:7481  ENSG00000210049  MT-TF
73921               MT-TF     NaN  HGNC:7481  ENSG00000210049   MTTF
73922               MT-TF     NaN  HGNC:7481  ENSG00000210049   TRNF

use list of ambiguous symbols and ensg_combined_concept_ids_df to create a histogram of how many genes share ambiguous symbols

In [437]:
ensg_symbol_value_counts = ensg_df["symbol"].value_counts()

ensg_ambiguous_symbol_counts = ensg_symbol_value_counts[ensg_symbol_value_counts.index.isin(ensg_ambiguous_symbol_set)]
ensg_ambiguous_symbol_counts = ensg_ambiguous_symbol_counts.reset_index()
ensg_ambiguous_symbol_counts.columns = ["symbols", "symbol_counts"]
ensg_ambiguous_symbol_counts

     symbols  symbol_counts
0        MT1             11
1       HOX1             10
2        P40             10
3       HOX2              9
4        P14              9
...      ...            ...
2157   CDK4I              2
2158    G6PT              2
2159     L30              2
2160     PRP              2
2161     CNP              2

[2162 rows x 2 columns]

In [480]:
len(set(ensg_ambiguous_symbol_counts["symbols"]))

2162

In [478]:
ensg_ambiguous_symbol_set_count

2162

In [438]:
create_ambiguous_symbol_histogram(ensg_ambiguous_symbol_counts, "ENSG", ensg_ambiguous_symbol_set_count)

In [439]:
ensg_ambiguous_symbol_counts_distribution_df = pd.read_csv(
    "../output/ambiguous_symbol_ensg_distribution_df.csv", index_col=[0])
ensg_ambiguous_symbol_counts_distribution_df

   symbol_counts  num_collision_symbol  percent_collision_symbol
0              2                  1836                 84.921369
1              3                   237                 10.962072
2              4                    49                  2.266420
3              5                    16                  0.740056
4              6                    13                  0.601295
5              7                     4                  0.185014
6              8                     2                  0.092507
7              9                     2                  0.092507
8             10                     2                  0.092507
9             11                     1                  0.046253

In [440]:
ensg_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"].sum()

100.00000000000001

In [441]:
# Filter out rows with symbol_counts < 6
less_than_six_ensg_ambiguous_symbol_counts_distribution_df = ensg_ambiguous_symbol_counts_distribution_df[ensg_ambiguous_symbol_counts_distribution_df["symbol_counts"] < 6].copy()

# Group all rows where symbol_counts >= 6
equal_more_than_six_ensg_ambiguous_symbol_counts_distribution_df = ensg_ambiguous_symbol_counts_distribution_df[ensg_ambiguous_symbol_counts_distribution_df["symbol_counts"] >= 6].agg({
    'num_collision_symbol': 'sum',
    'percent_collision_symbol': 'sum'
})

# Create a new row for '6+'
agg_row = pd.DataFrame({
    'symbol_counts': ['6+'],
    'num_collision_symbol': [equal_more_than_six_ensg_ambiguous_symbol_counts_distribution_df['num_collision_symbol']],
    'percent_collision_symbol': [equal_more_than_six_ensg_ambiguous_symbol_counts_distribution_df['percent_collision_symbol']]
})

# Concatenate and reset index
limited_ensg_ambiguous_symbol_counts_distribution_df = pd.concat([less_than_six_ensg_ambiguous_symbol_counts_distribution_df, agg_row], ignore_index=True)
limited_ensg_ambiguous_symbol_counts_distribution_df

  symbol_counts  num_collision_symbol  percent_collision_symbol
0             2                1836.0                 84.921369
1             3                 237.0                 10.962072
2             4                  49.0                  2.266420
3             5                  16.0                  0.740056
4            6+                  24.0                  1.110083

### <a id='toc1_1_3_'></a>[HGNC](#toc0_)

import file with ambiguous symbols resulting from alias-alias collisions

In [442]:
merged_alias_aa_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_aa_collision_hgnc_df.csv", index_col=[0])
merged_alias_aa_collision_hgnc_df

,HGNC_ID,gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:10991,SLC25A5,2F1,HGNC,GENE ID:292,ENSG00000005022,"2F1,T2,T3"
1,HGNC:6380,KLRG1,2F1,HGNC,GENE ID:10219,ENSG00000139187,"2F1,CLEC15A,MAFA,MAFA-L"
2,HGNC:10498,S100A8,60B8AG,HGNC,GENE ID:6279,ENSG00000143546,"60B8AG,CGLA,MRP-8,MRP8,P8,S100-A8"
3,HGNC:10499,S100A9,60B8AG,HGNC,GENE ID:6280,ENSG00000163220,"60B8AG,CGLB,LIAG,MAC387,MIF,MRP-14,MRP14,NIF,P..."
4,HGNC:10230,RNU6V,87U6,HGNC,GENE ID:6071,ENSG00000206832,"87U6,LH87"
...,...,...,...,...,...,...,...
2441,HGNC:33356,TEX28P1,pTEX,HGNC,GENE ID:728447,ENSG00000274962,pTEX
2442,HGNC:20219,PPP4R3A,smk1,HGNC,GENE ID:55671,ENSG00000100796,"FLFL1,FLJ20707,MSTP033,PP4R3,smk-1,smk1"
2443,HGNC:33146,PPP4R3C,smk1,HGNC,GENE ID:139420,ENSG00000224960,"FLFL3P,FLJ32867,smk1"
2444,HGNC:14681,SPATA2,tamo,HGNC,GENE ID:9825,ENSG00000158480,"KIAA0757,PD1,PPP1R145,tamo"
2445,HGNC:28393,SPATA2L,tamo,HGNC,GENE ID:124044,ENSG00000158792,"MGC26885,tamo"

In [443]:
aa_collision_alias_hgnc_set = set(
    merged_alias_aa_collision_hgnc_df["collision"]
)
len(aa_collision_alias_hgnc_set)

1082

import file with ambiguous symbols resulting from alias-primary collisions

In [444]:
ap_collision_hgnc_df = pd.read_csv(
    "../output/merged_alias_ap_collision_hgnc_df.csv", index_col=[0])
ap_collision_hgnc_df

,HGNC_ID,gene_symbol,collision,source,NCBI_ID,ENSG_ID,alias_symbol
0,HGNC:14947,PPP1R12C,AAVS1,HGNC,GENE ID:54776,ENSG00000125503,"AAVS1,DKFZP434D0412,MBS85,p84,p85"
1,HGNC:11177,SOAT1,ACAT1,HGNC,GENE ID:6646,ENSG00000057252,"ACAT,ACAT1"
2,HGNC:11178,SOAT2,ACAT2,HGNC,GENE ID:8435,ENSG00000167780,ACAT2
3,HGNC:1612,CCRL2,ACKR5,HGNC,GENE ID:9034,ENSG00000121797,"ACKR5,CKRX,CRAM-A,CRAM-B,HCR"
4,HGNC:7694,NDUFAB1,ACP1,HGNC,GENE ID:4706,ENSG00000004779,"ACP,ACP1,FASN2A,SDAP"
...,...,...,...,...,...,...,...
555,HGNC:3147,ECEL1,XCE,HGNC,GENE ID:9427,ENSG00000171551,"DINE,XCE"
556,HGNC:12904,ZNF121,ZNF20,HGNC,GENE ID:7675,ENSG00000197961,"ZHC32,ZNF20"
557,HGNC:21159,RNF141,ZNF230,HGNC,GENE ID:50862,ENSG00000110315,"ZFP26,ZNF230"
558,HGNC:12886,ZNF106,ZNF474,HGNC,GENE ID:64397,ENSG00000103994,"SH3BP3,ZNF474"
559,HGNC:23328,ZFP1,ZNF475,HGNC,GENE ID:162239,ENSG00000184517,"FLJ34243,ZNF475"

In [445]:
ap_collision_alias_hgnc_set = set(
    ap_collision_hgnc_df["collision"]
)
len(ap_collision_alias_hgnc_set)

492

combine lists without duplicates to create list of ambiguous symbols for HGNC

In [446]:
hgnc_ambiguous_symbol_set = aa_collision_alias_hgnc_set.union(
    ap_collision_alias_hgnc_set
)
hgnc_ambiguous_symbol_set_count = len(hgnc_ambiguous_symbol_set)
hgnc_ambiguous_symbol_set_count

1534

In [485]:
lowercased = [s.lower() for s in hgnc_ambiguous_symbol_set]

duplicates = {k: v for k, v in Counter(lowercased).items() if v > 1}

print(duplicates)

{'p58': 2, 'p28': 2, 'p8': 2, 'p62': 2, 'p47': 2, 'p14': 2, 'p18': 2, 'p21': 2, 'p40': 2, 'p54': 2, 'p15': 2}

In [447]:
both_collision_hgnc_set = aa_collision_alias_hgnc_set & ap_collision_alias_hgnc_set
len(both_collision_hgnc_set)

40

In [448]:
only_aa_collision_alias_hgnc_set = aa_collision_alias_hgnc_set - both_collision_hgnc_set
len(only_aa_collision_alias_hgnc_set)

1042

In [449]:
only_ap_collision_alias_hgnc_set = ap_collision_alias_hgnc_set - both_collision_hgnc_set
len(only_ap_collision_alias_hgnc_set)

452

In [450]:
subset_genes_hgnc_df = pd.read_csv(
        ("../output/subset_genes_hgnc_df.csv"), index_col=[0],dtype={"NCBI_ID": str,"HGNC_ID":str})

In [451]:
hgnc_df = subset_genes_hgnc_df.copy()
hgnc_df['primary_gene_symbol'] = hgnc_df['gene_symbol'].str.upper()
hgnc_df.drop(["gene_symbol"], axis=1, inplace=True)
hgnc_df['alias_symbol'] = hgnc_df['alias_symbol'].str.upper()
hgnc_df = hgnc_df.drop_duplicates(subset=['primary_gene_symbol', 'alias_symbol'], keep='first')
hgnc_df

,HGNC_ID,alias_symbol,NCBI_ID,ENSG_ID,primary_gene_symbol
0,HGNC:100,BNAC2,GENE ID:41,ENSG00000110881,ASIC1
0,HGNC:100,HBNAC2,GENE ID:41,ENSG00000110881,ASIC1
1,HGNC:10000,NaN,GENE ID:5999,ENSG00000117152,RGS4
2,HGNC:10001,NaN,GENE ID:8490,ENSG00000143248,RGS5
3,HGNC:10002,NaN,GENE ID:9628,ENSG00000182732,RGS6
...,...,...,...,...,...
44232,HGNC:9997,RGS-R,GENE ID:6004,ENSG00000143333,RGS16
44233,HGNC:9998,NaN,GENE ID:5997,ENSG00000116741,RGS2
44234,HGNC:9999,C2PA,GENE ID:5998,ENSG00000138835,RGS3
44234,HGNC:9999,FLJ20370,GENE ID:5998,ENSG00000138835,RGS3
44234,HGNC:9999,PDZ-RGS3,GENE ID:5998,ENSG00000138835,RGS3

make a general column with primary and alias symbols

In [452]:
hgnc_df = combine_columns(hgnc_df, ["primary_gene_symbol", "alias_symbol"], ["primary_gene_symbol", "ENSG_ID", "HGNC_ID","NCBI_ID"], "symbol", "alias_symbol")
hgnc_df

,primary_gene_symbol,NCBI_ID,HGNC_ID,ENSG_ID,symbol
0,ASIC1,GENE ID:41,HGNC:100,ENSG00000110881,ASIC1
2,RGS4,GENE ID:5999,HGNC:10000,ENSG00000117152,RGS4
3,RGS5,GENE ID:8490,HGNC:10001,ENSG00000143248,RGS5
4,RGS6,GENE ID:9628,HGNC:10002,ENSG00000182732,RGS6
5,RGS7,GENE ID:6000,HGNC:10003,ENSG00000182901,RGS7
...,...,...,...,...,...
132325,RGS16,GENE ID:6004,HGNC:9997,ENSG00000143333,RGS-R
132326,RGS2,GENE ID:5997,HGNC:9998,ENSG00000116741,NaN
132327,RGS3,GENE ID:5998,HGNC:9999,ENSG00000138835,C2PA
132328,RGS3,GENE ID:5998,HGNC:9999,ENSG00000138835,FLJ20370
132329,RGS3,GENE ID:5998,HGNC:9999,ENSG00000138835,PDZ-RGS3

use list of ambiguous symbols and hgnc_combined_concept_ids_df to create a histogram of how many genes share ambiguous symbols

In [453]:
hgnc_symbol_value_counts = hgnc_df["symbol"].value_counts()

hgnc_ambiguous_symbol_counts = hgnc_symbol_value_counts[hgnc_symbol_value_counts.index.isin(hgnc_ambiguous_symbol_set)]
hgnc_ambiguous_symbol_counts = hgnc_ambiguous_symbol_counts.reset_index()
hgnc_ambiguous_symbol_counts.columns = ["symbols", "symbol_counts"]
hgnc_ambiguous_symbol_counts

       symbols  symbol_counts
0          P40             10
1          P14              9
2          P18              7
3          PAP              7
4          ASP              7
...        ...            ...
1433       RF1              2
1434  IGFBP-3R              2
1435       SIN              2
1436       RHO              2
1437       MIO              2

[1438 rows x 2 columns]

In [481]:
len(set(hgnc_ambiguous_symbol_counts["symbols"]))

1438

In [482]:
hgnc_ambiguous_symbol_set_count

1534

In [454]:
create_ambiguous_symbol_histogram(hgnc_ambiguous_symbol_counts, "HGNC", hgnc_ambiguous_symbol_set_count)

In [455]:
hgnc_ambiguous_symbol_counts_distribution_df = pd.read_csv(
    "../output/ambiguous_symbol_hgnc_distribution_df.csv", index_col=[0])
hgnc_ambiguous_symbol_counts_distribution_df

   symbol_counts  num_collision_symbol  percent_collision_symbol
0              2                  1204                 78.487614
1              3                   173                 11.277705
2              4                    34                  2.216428
3              5                    13                  0.847458
4              6                     8                  0.521512
5              7                     4                  0.260756
6              9                     1                  0.065189
7             10                     1                  0.065189

In [456]:
hgnc_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"].sum()

93.74185136897002

In [457]:
# Filter out rows with symbol_counts < 6
less_than_six_hgnc_ambiguous_symbol_counts_distribution_df = hgnc_ambiguous_symbol_counts_distribution_df[hgnc_ambiguous_symbol_counts_distribution_df["symbol_counts"] < 6].copy()

# Group all rows where symbol_counts >= 6
equal_more_than_six_hgnc_ambiguous_symbol_counts_distribution_df = hgnc_ambiguous_symbol_counts_distribution_df[hgnc_ambiguous_symbol_counts_distribution_df["symbol_counts"] >= 6].agg({
    'num_collision_symbol': 'sum',
    'percent_collision_symbol': 'sum'
})

# Create a new row for '6+'
agg_row = pd.DataFrame({
    'symbol_counts': ['6+'],
    'num_collision_symbol': [equal_more_than_six_hgnc_ambiguous_symbol_counts_distribution_df['num_collision_symbol']],
    'percent_collision_symbol': [equal_more_than_six_hgnc_ambiguous_symbol_counts_distribution_df['percent_collision_symbol']]
})

# Concatenate and reset index
limited_hgnc_ambiguous_symbol_counts_distribution_df = pd.concat([less_than_six_hgnc_ambiguous_symbol_counts_distribution_df, agg_row], ignore_index=True)
limited_hgnc_ambiguous_symbol_counts_distribution_df

  symbol_counts  num_collision_symbol  percent_collision_symbol
0             2                1204.0                 78.487614
1             3                 173.0                 11.277705
2             4                  34.0                  2.216428
3             5                  13.0                  0.847458
4            6+                  14.0                  0.912647

### <a id='toc1_1_4_'></a>[NCBI](#toc0_)

import file with ambiguous symbols resulting from alias-alias collisions

In [458]:
merged_alias_aa_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_aa_collision_ncbi_df.csv", index_col=[0])
merged_alias_aa_collision_ncbi_df

,NCBI_ID,gene_symbol,collision,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:5728,PTEN,10q23del,NCBI,HGNC:9588,ENSG00000171862,"10q23del,BZS,CWS1,DEC,GLM2,MHAM,MMAC1,PTEN1,PT..."
1,GENE ID:657,BMPR1A,10q23del,NCBI,HGNC:1076,ENSG00000107779,"10q23del,ACVRLK3,ALK-3,ALK3,BMPR-1A,CD292,SKR5"
2,GENE ID:239,ALOX12,12-LOX,NCBI,HGNC:429,ENSG00000108839,"12-LOX,12S-LOX,LOG12"
3,GENE ID:246,ALOX15,12-LOX,NCBI,HGNC:433,ENSG00000161905,"12-LOX,15-LOX,15-LOX-1,LOG15"
4,GENE ID:10219,KLRG1,2F1,NCBI,HGNC:6380,ENSG00000139187,"2F1,CLEC15A,MAFA,MAFA-2F1,MAFA-L,MAFA-LIKE"
...,...,...,...,...,...,...,...
8173,GENE ID:57223,PPP4R3B,smk1,NCBI,HGNC:29267,ENSG00000275052,"FLFL2,PP4R3B,PSY2,SMEK2,smk1"
8174,GENE ID:139420,PPP4R3C,smk1,NCBI,HGNC:33146,ENSG00000224960,"FLFL3P,PPP4R3CP,SMEK3P,smk1"
8175,GENE ID:55671,PPP4R3A,smk1,NCBI,HGNC:20219,ENSG00000100796,"FLFL1,KIAA2010,MSTP033,PP4R3,PP4R3A,SMEK1,smk-..."
8176,GENE ID:9825,SPATA2,tamo,NCBI,HGNC:14681,ENSG00000158480,"PD1,PPP1R145,tamo"
8177,GENE ID:124044,SPATA2L,tamo,NCBI,HGNC:28393,ENSG00000158792,"C16orf76,tamo"

In [459]:
aa_collision_alias_ncbi_set = set(
    merged_alias_aa_collision_ncbi_df["collision"]
)
len(aa_collision_alias_ncbi_set)

3412

import file with ambiguous symbols resulting from alias-primary collisions

In [460]:
ap_collision_ncbi_df = pd.read_csv(
    "../output/merged_alias_ap_collision_ncbi_df.csv", index_col=[0])
ap_collision_ncbi_df

,NCBI_ID,gene_symbol,collision,source,HGNC_ID,ENSG_ID,alias_symbol
0,GENE ID:3494,IGHA2,A2M,NCBI,HGNC:5479,ENSG00000211890,A2M
1,GENE ID:54776,PPP1R12C,AAVS1,NCBI,HGNC:14947,ENSG00000125503,"AAVS1,LENG3,MBS85,p84,p85"
2,GENE ID:6646,SOAT1,ACAT1,NCBI,HGNC:11177,ENSG00000057252,"ACACT,ACAT,ACAT-1,ACAT1,SOAT,STAT"
3,GENE ID:8435,SOAT2,ACAT2,NCBI,HGNC:11178,ENSG00000167780,"ACACT2,ACAT2,ARGP2"
4,GENE ID:9034,CCRL2,ACKR5,NCBI,HGNC:1612,ENSG00000121797,"ACKR5,CKRX,CRAM,CRAM-A,CRAM-B,HCR"
...,...,...,...,...,...,...,...
2031,GENE ID:29903,CCDC106,ZNF581,NCBI,HGNC:30181,ENSG00000173581,"HSU79303,ZNF581"
2032,GENE ID:146540,ZNF785,ZNF688,NCBI,HGNC:26496,ENSG00000197162,ZNF688
2033,GENE ID:57829,ZP4,ZP1,NCBI,HGNC:15770,ENSG00000116996,"ZBP,ZP1,ZP1B,ZPB,ZPB2,Zp-4"
2035,GENE ID:55663,ZNF446,ZSCAN30,NCBI,HGNC:21036,ENSG00000083838,"ZKSCAN20,ZSCAN30,ZSCAN52"
2036,GENE ID:342357,ZKSCAN2,ZSCAN31,NCBI,HGNC:25677,ENSG00000155592,"ZNF694,ZSCAN31,ZSCAN34"

In [461]:
ap_collision_alias_ncbi_set = set(
    ap_collision_ncbi_df["collision"]
)
len(ap_collision_alias_ncbi_set)

1394

combine lists without duplicates to create list of ambiguous symbols for NCBI

In [462]:
ncbi_ambiguous_symbol_set = aa_collision_alias_ncbi_set.union(
    ap_collision_alias_ncbi_set
)
ncbi_ambiguous_symbol_set_count = len(ncbi_ambiguous_symbol_set)
ncbi_ambiguous_symbol_set_count

4652

In [486]:
lowercased = [s.lower() for s in ncbi_ambiguous_symbol_set]

duplicates = {k: v for k, v in Counter(lowercased).items() if v > 1}

print(duplicates)

{'p58': 2, 'p19': 2, 'p150': 2, 'p97': 2, 'p42': 2, 'p60': 2, 'p8': 2, 'p62': 2, 'p47': 2, 'p37': 2, 'p65': 2, 'stv1': 2, 'p38': 2, 'p56': 2, 'vph1': 2, 'p40': 2, 'p54': 2, 'p18': 2, 'p21': 2, 'p15': 2, 'rpl7a': 2, 'p100': 2, 'p28': 2, 'met': 2, 'p14': 2, 'ppiase': 2}

In [463]:
both_collision_ncbi_set = aa_collision_alias_ncbi_set & ap_collision_alias_ncbi_set
len(both_collision_ncbi_set)

154

In [464]:
only_aa_collision_alias_ncbi_set = aa_collision_alias_ncbi_set - both_collision_ncbi_set
len(only_aa_collision_alias_ncbi_set)

3258

In [465]:
only_ap_collision_alias_ncbi_set = ap_collision_alias_ncbi_set - both_collision_ncbi_set
len(only_ap_collision_alias_ncbi_set)

1240

In [466]:
subset_genes_ncbi_df = pd.read_csv(
        ("../output/subset_genes_ncbi_df.csv"), index_col=[0],dtype={"NCBI_ID": str,"HGNC_ID":str})

In [467]:
ncbi_df = subset_genes_ncbi_df.copy()
ncbi_df['primary_gene_symbol'] = ncbi_df['gene_symbol'].str.upper()
ncbi_df.drop(["gene_symbol"], axis=1, inplace=True)
ncbi_df['alias_symbol'] = ncbi_df['alias_symbol'].str.upper()
ncbi_df = ncbi_df.drop_duplicates(subset=['primary_gene_symbol', 'alias_symbol'], keep='first')
ncbi_df

,NCBI_ID,alias_symbol,HGNC_ID,ENSG_ID,primary_gene_symbol
0,GENE ID:1,A1B,HGNC:5,ENSG00000121410,A1BG
0,GENE ID:1,ABG,HGNC:5,ENSG00000121410,A1BG
0,GENE ID:1,GAB,HGNC:5,ENSG00000121410,A1BG
0,GENE ID:1,HYST2477,HGNC:5,ENSG00000121410,A1BG
1,GENE ID:2,A2MD,HGNC:7,ENSG00000175899,A2M
...,...,...,...,...,...
193502,GENE ID:141732005,NaN,HGNC:40064,NaN,ADCY2-AS1
193503,GENE ID:141732006,NaN,HGNC:41074,NaN,NSG2-AS1
193504,GENE ID:141732007,NaN,HGNC:58430,NaN,ST18-AS1
193505,GENE ID:141732008,NaN,HGNC:58437,NaN,MICAL2-AS1
193506,GENE ID:141732009,NaN,HGNC:40863,NaN,TRIM41-AS1

make a general symbol column with primary and alias symbols

In [468]:
ncbi_df = combine_columns(ncbi_df, ["primary_gene_symbol", "alias_symbol"], ["primary_gene_symbol", "ENSG_ID", "HGNC_ID","NCBI_ID"], "symbol", "alias_symbol")
ncbi_df

,primary_gene_symbol,NCBI_ID,HGNC_ID,ENSG_ID,symbol
0,A1BG,GENE ID:1,HGNC:5,ENSG00000121410,A1BG
4,A2M,GENE ID:2,HGNC:7,ENSG00000175899,A2M
8,NAT1,GENE ID:9,HGNC:7645,ENSG00000171428,NAT1
12,NAT2,GENE ID:10,HGNC:7646,ENSG00000156006,NAT2
15,NATP,GENE ID:11,HGNC:15,NaN,NATP
...,...,...,...,...,...
182509,ADCY2-AS1,GENE ID:141732005,HGNC:40064,NaN,NaN
182510,NSG2-AS1,GENE ID:141732006,HGNC:41074,NaN,NaN
182511,ST18-AS1,GENE ID:141732007,HGNC:58430,NaN,NaN
182512,MICAL2-AS1,GENE ID:141732008,HGNC:58437,NaN,NaN
182513,TRIM41-AS1,GENE ID:141732009,HGNC:40863,NaN,NaN

use list of ambiguous symbols and ncbi_combined_concept_ids_df to create a histogram of how many genes share ambiguous symbols

In [469]:
ncbi_symbol_value_counts = ncbi_df["symbol"].value_counts()

ncbi_ambiguous_symbol_counts = ncbi_symbol_value_counts[ncbi_symbol_value_counts.index.isin(ncbi_ambiguous_symbol_set)]
ncbi_ambiguous_symbol_counts = ncbi_ambiguous_symbol_counts.reset_index()
ncbi_ambiguous_symbol_counts.columns = ["symbols", "symbol_counts"]
ncbi_ambiguous_symbol_counts

         symbols  symbol_counts
0             VH             37
1           H4C1             14
2           H4C3             14
3           H4C8             14
4          H4C12             14
...          ...            ...
4433        SYM1              2
4434  TRY-GTA5-1              2
4435         IA4              2
4436  TRP-TGG3-4              2
4437  TRW-CCA3-1              2

[4438 rows x 2 columns]

In [470]:
create_ambiguous_symbol_histogram(ncbi_ambiguous_symbol_counts, "NCBI", ncbi_ambiguous_symbol_set_count)

In [471]:
ncbi_ambiguous_symbol_counts_distribution_df = pd.read_csv(
    "../output/ambiguous_symbol_ncbi_distribution_df.csv", index_col=[0])
ncbi_ambiguous_symbol_counts_distribution_df

    symbol_counts  num_collision_symbol  percent_collision_symbol
0               2                  3627                 77.966466
1               3                   527                 11.328461
2               4                   133                  2.858985
3               5                    65                  1.397248
4               6                    27                  0.580396
5               7                    16                  0.343938
6               8                     5                  0.107481
7               9                     5                  0.107481
8              10                    12                  0.257954
9              11                     3                  0.064488
10             12                     2                  0.042992
11             14                    15                  0.322442
12             37                     1                  0.021496

In [472]:
ncbi_ambiguous_symbol_counts_distribution_df["percent_collision_symbol"].sum()

95.39982803095444

In [477]:
# Filter out rows with symbol_counts < 6
less_than_six_ncbi_ambiguous_symbol_counts_distribution_df = ncbi_ambiguous_symbol_counts_distribution_df[ncbi_ambiguous_symbol_counts_distribution_df["symbol_counts"] < 6].copy()

# Group all rows where symbol_counts >= 6
equal_more_than_six_ncbi_ambiguous_symbol_counts_distribution_df = ncbi_ambiguous_symbol_counts_distribution_df[ncbi_ambiguous_symbol_counts_distribution_df["symbol_counts"] >= 6].agg({
    'num_collision_symbol': 'sum',
    'percent_collision_symbol': 'sum'
})

# Create a new row for '6+'
agg_row = pd.DataFrame({
    'symbol_counts': ['6+'],
    'num_collision_symbol': [equal_more_than_six_ncbi_ambiguous_symbol_counts_distribution_df['num_collision_symbol']],
    'percent_collision_symbol': [equal_more_than_six_ncbi_ambiguous_symbol_counts_distribution_df['percent_collision_symbol']]
})

# Concatenate and reset index
limited_ncbi_ambiguous_symbol_counts_distribution_df = pd.concat([less_than_six_ncbi_ambiguous_symbol_counts_distribution_df, agg_row], ignore_index=True)
limited_ncbi_ambiguous_symbol_counts_distribution_df

  symbol_counts  num_collision_symbol  percent_collision_symbol
0             2                3627.0                 77.966466
1             3                 527.0                 11.328461
2             4                 133.0                  2.858985
3             5                  65.0                  1.397248
4            6+                  86.0                  1.848667

In [474]:
ncbi_ensg_ambiguous_symbol_set = ncbi_ambiguous_symbol_set.union(
    ensg_ambiguous_symbol_set
)

In [475]:
ncbi_ensg_hgnc_ambiguous_symbol_set = ncbi_ensg_ambiguous_symbol_set.union(
    hgnc_ambiguous_symbol_set
)

In [476]:
ambiguous_symbol_set = ncbi_ensg_hgnc_ambiguous_symbol_set
len(ambiguous_symbol_set)

4968