In [1]:
import civicpy.civic as civic
import pandas as pd

import gene_ids_in_lit.functions as fn

In [2]:
evidence = civic.get_all_evidence(include_status="accepted")
molecular_profiles = civic.get_all_molecular_profiles(include_status="accepted")

In [3]:
len(evidence)

4885

In [4]:
# Build lookup by CIViC molecular profile ID
mp_by_id = {
    mp.id: mp
    for mp in molecular_profiles
}

In [5]:
rows = []

for e in evidence:
    mp = mp_by_id.get(e.molecular_profile_id)

    if mp is None:
        continue

    for x in mp.parsed_name:
        if isinstance(x, civic.Gene):
            rows.append({
                "gene_symbol": x.name,
                "entrez_id": x.entrez_id,
                "PMID": e.source.citation_id
            })

In [6]:
df = (
    pd.DataFrame(rows)
    .drop_duplicates()
    .reset_index(drop=True)
)
df

     gene_symbol  entrez_id      PMID
0           NPM1       4869  19357394
1           EGFR       1956  25668228
2           MGMT       4255  15758010
3           KRAS       3845  18946061
4           BRAF        673  21639808
...          ...        ...       ...
2052        RHOA        387  27313181
2053        KRAS       3845  28259530
2054        EGFR       1956  29196463
2055         KIT       3815  28595259
2056        EGFR       1956  24658966

[2057 rows x 3 columns]

Make merged ambiguous symbol df from alias-alias and alias-primary collisions

In [7]:
aa_colliison_df = pd.read_csv("../output/merged_aa_collision_gene_df.csv")
ap_colliison_df = pd.read_csv("../output/merged_alias_primary_collisions_df.csv")

aa_colliison_df = aa_colliison_df.rename(columns={
    "collision": "ambiguous_symbol",
})

ap_colliison_df = ap_colliison_df.rename(columns={
    "collision": "ambiguous_symbol",
})

aa_colliison_df["collision type"] = "alias-alias"
ap_colliison_df["collision type"] = "alias-primary"

collision_df = pd.concat([aa_colliison_df, ap_colliison_df], ignore_index=True)

key_cols = [
    "ambiguous_symbol",
    "NCBI_ID",
    "primary_gene_symbol"
]

collision_df = (
    collision_df
    .groupby(key_cols, as_index=False)["collision type"]
    .agg(lambda x: sorted(set(x)))
)

In [8]:
collision_df

     ambiguous_symbol         NCBI_ID primary_gene_symbol   collision type
0                 7SK  GENE ID:125050               RN7SK  [alias-primary]
1                 A2M    GENE ID:3494               IGHA2  [alias-primary]
2               AAVS1   GENE ID:54776            PPP1R12C  [alias-primary]
3               ACAT1    GENE ID:6646               SOAT1  [alias-primary]
4               ACAT2    GENE ID:8435               SOAT2  [alias-primary]
...               ...             ...                 ...              ...
1679           ZNF581   GENE ID:29903             CCDC106  [alias-primary]
1680           ZNF688  GENE ID:146540              ZNF785  [alias-primary]
1681              ZP1   GENE ID:57829                 ZP4  [alias-primary]
1682          ZSCAN30   GENE ID:55663              ZNF446  [alias-primary]
1683          ZSCAN31  GENE ID:342357             ZKSCAN2  [alias-primary]

[1684 rows x 4 columns]

In [9]:
collision_df = (
    collision_df.groupby(
        ["NCBI_ID", "primary_gene_symbol"],
        as_index=False
    )
    .agg({
        "ambiguous_symbol": lambda x: list(x)
    })
)

In [10]:
collision_df

                NCBI_ID primary_gene_symbol ambiguous_symbol
0     GENE ID:100008586             GAGE12F          [GAGE7]
1     GENE ID:100008587           RNA5-8SN5       [RNA5-8S5]
2     GENE ID:100008588            RNA18SN5        [RNA18S5]
3     GENE ID:100008589            RNA28SN5        [RNA28S5]
4     GENE ID:100009602          TRY-GTA5-4     [TRY-GTA5-2]
...                 ...                 ...              ...
1667       GENE ID:9962             SLC23A2        [SLC23A1]
1668       GENE ID:9963             SLC23A1        [SLC23A2]
1669       GENE ID:9968               MED12           [OPA1]
1670       GENE ID:9988               DMTF1           [DMP1]
1671       GENE ID:9997                SCO2           [TYMP]

[1672 rows x 3 columns]

Remove genes from civic pmids df that are not involved in collisions

In [11]:
collision_df["entrez_id"] = (
    collision_df["NCBI_ID"]
    .str.extract(r"(\d+)", expand=False)
    .astype("Int64")
)

In [12]:
collision_df

                NCBI_ID primary_gene_symbol ambiguous_symbol  entrez_id
0     GENE ID:100008586             GAGE12F          [GAGE7]  100008586
1     GENE ID:100008587           RNA5-8SN5       [RNA5-8S5]  100008587
2     GENE ID:100008588            RNA18SN5        [RNA18S5]  100008588
3     GENE ID:100008589            RNA28SN5        [RNA28S5]  100008589
4     GENE ID:100009602          TRY-GTA5-4     [TRY-GTA5-2]  100009602
...                 ...                 ...              ...        ...
1667       GENE ID:9962             SLC23A2        [SLC23A1]       9962
1668       GENE ID:9963             SLC23A1        [SLC23A2]       9963
1669       GENE ID:9968               MED12           [OPA1]       9968
1670       GENE ID:9988               DMTF1           [DMP1]       9988
1671       GENE ID:9997                SCO2           [TYMP]       9997

[1672 rows x 4 columns]

make sure types are the same

In [13]:
df["entrez_id"] = df["entrez_id"].astype("Int64")

In [20]:
df_filtered = df[
    df["entrez_id"].isin(collision_df["entrez_id"])
].copy()

In [21]:
df_filtered

     gene_symbol  entrez_id      PMID
11        UGT1A1      54658  26313268
60          NRAS       4893  28275037
89         H3-3A       3020  38335473
95          EZH2       2146  33035457
96         CHEK2      11200  32343890
...          ...        ...       ...
2013        KLF5        688  28963353
2014        PTEN       5728  24088382
2016       FGFR1       2260  34593528
2027        NRAS       4893  24950457
2050       FBXW7      55294  24253377

[215 rows x 3 columns]

Query pubmed articles for ambiguous symbol

In [22]:
df_filtered = df_filtered.merge(
    collision_df[["entrez_id", "ambiguous_symbol"]],
    on="entrez_id",
    how="left"
)
df_filtered

    gene_symbol  entrez_id      PMID ambiguous_symbol
0        UGT1A1      54658  26313268          [UGT1A]
1          NRAS       4893  28275037           [KRAS]
2         H3-3A       3020  38335473          [H3-3B]
3          EZH2       2146  33035457           [EZH1]
4         CHEK2      11200  32343890           [CDS1]
..          ...        ...       ...              ...
210        KLF5        688  28963353           [CKLF]
211        PTEN       5728  24088382           [TEP1]
212       FGFR1       2260  34593528            [FLG]
213        NRAS       4893  24950457           [KRAS]
214       FBXW7      55294  24253377         [FBXO30]

[215 rows x 4 columns]

In [ ]:
import re
import time

In [24]:
def find_aliases_in_document(
    document: dict,
    aliases: list[str],
) -> list[str]:
    """Find ambiguous gene aliases in PubTator document text."""

    found = set()

    for passage in document.get("passages", []):
        text = str(passage.get("text", ""))

        for alias in aliases:
            pattern = re.compile(
                rf"(?<!\w){re.escape(alias)}(?!\w)",
                re.IGNORECASE,
            )

            if pattern.search(text):
                found.add(alias)

    return sorted(found)

In [25]:
pmids = set(
    df_filtered["PMID"]
    .dropna()
    .astype(str)
)

In [26]:
def fetch_documents_by_pmids(
    pmids,
    batch_size=50,
):
    """Fetch PubTator documents for a collection of PMIDs."""

    sorted_pmids = sorted(
        {str(pmid) for pmid in pmids}
    )

    for batch in fn.chunked(sorted_pmids, size=batch_size):

        response = fn.get_with_retry(
            f"{fn.BASE_URL}/publications/export/biocjson",
            params={
                "pmids": ",".join(batch),
                "full": "true",
            },
            timeout=180,
        )

        result = response.json()

        if isinstance(result, list):
            documents = result

        elif isinstance(result, dict) and "PubTator3" in result:
            documents = result["PubTator3"]

        elif isinstance(result, dict) and "documents" in result:
            documents = result["documents"]

        elif isinstance(result, dict) and "id" in result:
            documents = [result]

        else:
            documents = []

        yield from documents

        time.sleep(2)

In [27]:
import importlib

importlib.reload(fn)

In [28]:
pmids = set(
    df_filtered.loc[
        df_filtered["PMID"].astype(str).str.fullmatch(r"\d+"),
        "PMID"
    ]
    .astype(str)
)

In [29]:
documents_by_pmid = {}

for document in fetch_documents_by_pmids(pmids):

    pmid = str(
        document.get("pmid")
        or document.get("id")
        or ""
    ).strip()

    if pmid:
        documents_by_pmid[pmid] = document

In [32]:
def find_row_aliases(row):
    pmid = str(row["PMID"])

    document = documents_by_pmid.get(pmid)

    if document is None:
        return []

    return find_aliases_in_document(
        document,
        row["ambiguous_symbol"],
    )

In [33]:
def document_has_full_text(document):
    passage_types = {
        passage.get("infons", {}).get("type", "unknown")
        for passage in document.get("passages", [])
    }

    return not passage_types <= {"title", "abstract"}

In [34]:
def analyze_row(row):
    pmid = str(row["PMID"])
    document = documents_by_pmid.get(pmid)

    if document is None:
        return pd.Series({
            "full_text_available": False,
            "aliases_found": [],
        })

    return pd.Series({
        "full_text_available": document_has_full_text(document),
        "aliases_found": find_aliases_in_document(
            document,
            row["ambiguous_symbol"],
        ),
    })

In [35]:
results = df_filtered.apply(
    analyze_row,
    axis=1,
)

df_filtered = pd.concat(
    [df_filtered, results],
    axis=1,
)

In [36]:
df_filtered = df_filtered.reset_index(drop=True)

df_filtered = df_filtered[
    df_filtered["aliases_found"].apply(len) > 0
].reset_index(drop=True)

In [37]:
df_filtered

,gene_symbol,entrez_id,PMID,ambiguous_symbol,full_text_available,aliases_found
0,NRAS,4893,28275037,[KRAS],False,[KRAS]
1,NRAS,4893,25666295,[KRAS],False,[KRAS]
2,CHEK2,11200,10617473,[CDS1],False,[CDS1]
3,EZH2,2146,20081860,[EZH1],True,[EZH1]
4,PTEN,5728,17700571,[TEP1],True,[TEP1]
5,NRG1,3084,26137564,[HRG],True,[HRG]
6,NRAS,4893,24666267,[KRAS],False,[KRAS]
7,NRAS,4893,15951308,[KRAS],False,[KRAS]
8,NRAS,4893,20619739,[KRAS],False,[KRAS]
9,NRAS,4893,22650231,[KRAS],False,[KRAS]
10,PTEN,5728,16404430,[TEP1],True,[TEP1]
11,NRAS,4893,35363510,[KRAS],False,[KRAS]
12,NRAS,4893,24947927,[KRAS],False,[KRAS]
13,NRAS,4893,18390968,[KRAS],False,[KRAS]
14,NRAS,4893,30809568,[KRAS],True,[KRAS]
15,EZH2,2146,27135738,[EZH1],True,[EZH1]
16,NRAS,4893,26821351,[KRAS],True,[KRAS]
17,NRAS,4893,25504439,[KRAS],True,[KRAS]
18,NRAS,4893,22392911,[KRAS],False,[KRAS]
19,EZH2,2146,21078963,[EZH1],False,[EZH1]
20,NRAS,4893,22194965,[KRAS],True,[KRAS]
21,NRAS,4893,22586653,[KRAS],False,[KRAS]
22,NRAS,4893,23515407,[KRAS],False,[KRAS]

In [40]:
dgidb_genes_df = pd.read_csv("../input/genes (4).tsv", sep="\t", comment="#")

In [41]:
dgidb_genes_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
0,TNFRSF10B,Gene Symbol,hgnc:11905,TNFRSF10B,HGNC,20260619
1,TNFRSF10B,Gene Symbol,hgnc:11905,TNFRSF10B,Ensembl,116
2,TNFRSF10B,Gene Symbol,hgnc:11905,TNFRSF10B,NCBI,20260622
3,TNFRSF10B,Gene Symbol,hgnc:11905,TNFRSF10B,ChEMBL,37
4,SOST,Gene Symbol,hgnc:13771,SOST,HGNC,20260619
...,...,...,...,...,...,...
77492,CD2,Gene Name,hgnc:1639,CD2,NCI,14-September-2017
77493,MUC16,Gene Name,hgnc:15582,MUC16,NCI,14-September-2017
77494,CYP19A1,Gene Name,hgnc:2594,CYP19A1,NCI,14-September-2017
77495,CCNE1,Gene Symbol,hgnc:1589,CCNE1,MskImpact,May-2015
77496,ABL,Gene Symbol,hgnc:76,ABL1,CarisMolecularIntelligence,2020-09-04

In [43]:
ambig_symbol_set = set(collision_df["ambiguous_symbol"].explode().dropna())
dgidb_genes_set = set(dgidb_genes_df["gene_name"])
ambig_symbol_set & dgidb_genes_set

{'A2M',
 'ACAT1',
 'ACAT2',
 'ACKR5',
 'ACP1',
 'ACTB',
 'ADA2',
 'ADAM18',
 'ADAM23',
 'ADCY3',
 'ADH4',
 'ADK',
 'ADRA1A',
 'AFP',
 'AGPS',
 'AGT',
 'AHRR',
 'AIP',
 'AK3',
 'AK6',
 'ALB',
 'ALG10',
 'ALG2',
 'ALPI',
 'AMD1',
 'AMN',
 'ANXA8',
 'APC',
 'APOA2',
 'APOBEC3A',
 'APPL2',
 'AQP1',
 'AQP9',
 'AR',
 'ARF1',
 'ARG1',
 'ARHGAP10',
 'ARL1',
 'ARNT',
 'ARPC4',
 'ARSB',
 'ART1',
 'ARX',
 'ASIP',
 'ASL',
 'ATF1',
 'ATL1',
 'ATP1A1',
 'ATP2B2',
 'ATR',
 'AVP',
 'AZI2',
 'B3GNT6',
 'BAP1',
 'BCAM',
 'BCR',
 'BDNF',
 'BDP1',
 'BEX1',
 'BEX2',
 'BMI1',
 'BOLA2',
 'BRAP',
 'BRCC3',
 'BRF1',
 'BRF2',
 'BRIP1',
 'BRPF1',
 'BST1',
 'BTD',
 'BTF3',
 'C1QTNF5',
 'C2',
 'C4B',
 'C4B_2',
 'C6',
 'C7',
 'C9',
 'CA11',
 'CABP1',
 'CACNA1I',
 'CAD',
 'CAMP',
 'CAPG',
 'CAPS',
 'CARF',
 'CAST',
 'CAT',
 'CBLB',
 'CBLC',
 'CCK',
 'CCL28',
 'CCN1',
 'CCNL1',
 'CCR10',
 'CCR4',
 'CD14',
 'CD1A',
 'CD34',
 'CD3G',
 'CDC14B',
 'CDH1',
 'CDH3',
 'CDKN1A',
 'CDS1',
 'CEACAM3',
 'CENPS',
 'CEP68',
 'CER1',
 'CERS1',
 'CERS5',
 'CES2',
 'CFC1B',
 'CFD',
 'CFL1',
 'CGA',
 'CGB5',
 'CHAT',
 'CHD2',
 'CHD5',
 'CHL1',
 'CHMP3',
 'CHMP4A',
 'CHMP4B',
 'CHP1',
 'CHRNA7',
 'CIC',
 'CIT',
 'CKB',
 'CKLF',
 'CLC',
 'CLIC5',
 'CLK1',
 'CLK2',
 'CLP1',
 'CNP',
 'CNR1',
 'CNR2',
 'COP1',
 'COPS7B',
 'CORO7',
 'COX11',
 'COX2',
 'CPA3',
 'CPA6',
 'CPD',
 'CPN1',
 'CPN2',
 'CPO',
 'CPS1',
 'CPT1B',
 'CREB3',
 'CRIPTO',
 'CRP',
 'CSN2',
 'CSN3',
 'CSNK2A1',
 'CST6',
 'CTH',
 'CTSO',
 'CUZD1',
 'CYC1',
 'CYP2D6',
 'CYP3A7',
 'DAB1',
 'DAO',
 'DBI',
 'DBP',
 'DDT',
 'DEFA1',
 'DEFB108B',
 'DESI1',
 'DESI2',
 'DGCR6',
 'DHFRP1',
 'DIO1',
 'DLD',
 'DLG1',
 'DLG2',
 'DLG3',
 'DLG4',
 'DMC1',
 'DMP1',
 'DOK1',
 'DSP',
 'DTL',
 'DUSP1',
 'DUSP23',
 'DUSP26',
 'DUX1',
 'DUX4',
 'EBF3',
 'EBP',
 'ECE2',
 'EEF1AKMT4',
 'EFL1',
 'EGLN2',
 'EIF2AK1',
 'EIF5A',
 'ELF1',
 'ELK1',
 'ELK3',
 'ELN',
 'ELP1',
 'EMB',
 'EMILIN3',
 'EPM2A',
 'EPO',
 'ERF',
 'EZH1',
 'F10',
 'F11',
 'F2',
 'F3',
 'FAAH',
 'FABP5',
 'FADS1',
 'FADS2',
 'FADS3',
 'FAH',
 'FAN1',
 'FAP',
 'FAS',
 'FBP2',
 'FBXO31',
 'FCGR2C',
 'FCGR3A',
 'FCRL1',
 'FCRL2',
 'FCRLB',
 'FGF2',
 'FH',
 'FHL5',
 'FHOD3',
 'FKBP6',
 'FKBP9',
 'FLG',
 'FLI1',
 'FMO2',
 'FMR1',
 'FNTB',
 'FOLR1',
 'FXYD6',
 'FZD3',
 'FZD5',
 'G6PD',
 'GAB1',
 'GABPB1',
 'GABPB2',
 'GAL',
 'GAL3ST2',
 'GALNT17',
 'GALNT7',
 'GAPDH',
 'GAS7',
 'GBF1',
 'GBP3',
 'GC',
 'GCK',
 'GCKR',
 'GDA',
 'GDF1',
 'GEM',
 'GIP',
 'GJA10',
 'GJA9',
 'GJC1',
 'GJE1',
 'GK',
 'GK2',
 'GLA',
 'GLS',
 'GLUD1',
 'GLUD2',
 'GOLGA5',
 'GOT1',
 'GP1BB',
 'GPI',
 'GPR42',
 'GPRASP3',
 'GPT',
 'GPX6',
 'GRIK2',
 'GRIN1',
 'GRP',
 'GSS',
 'GTF2A1L',
 'GTF2I',
 'GTF2IRD2',
 'GUCA1A',
 'GUSBP1',
 'GYPA',
 'H2AC11',
 'H2BC4',
 'H3-3A',
 'H3-3B',
 'H3C1',
 'H3C10',
 'H3C13',
 'H3C14',
 'H4C1',
 'H4C11',
 'HADH',
 'HAP1',
 'HARS2',
 'HBB',
 'HCP5',
 'HCRTR2',
 'HCST',
 'HDAC7',
 'HDC',
 'HEBP1',
 'HES1',
 'HGF',
 'HK1',
 'HK2',
 'HK3',
 'HLA-DPB1',
 'HLA-DQB1',
 'HLA-H',
 'HLF',
 'HNF4A',
 'HP',
 'HPCA',
 'HPF1',
 'HRG',
 'HRH1',
 'HRH2',
 'HS3ST5',
 'HSD17B7',
 'HTR2B',
 'HTRA3',
 'HTT',
 'HYAL1',
 'IFNA13',
 'IGH',
 'IGHEP1',
 'IGL',
 'IK',
 'IL17A',
 'IL25',
 'IL27',
 'IMPDH1',
 'INPP5E',
 'JUNB',
 'KCNMB2',
 'KIR2DL1',
 'KIR2DL3',
 'KIR2DL5B',
 'KIR2DS5',
 'KLF14',
 'KLHL6',
 'KLK3',
 'KLK6',
 'KLK7',
 'KRAS',
 'KRTAP5-2',
 'KRTAP5-3',
 'KSR2',
 'LAMA3',
 'LAMB2',
 'LAP3',
 'LAT',
 'LAT2',
 'LBH',
 'LBP',
 'LCP1',
 'LDB1',
 'LEPR',
 'LGALS2',
 'LGALS7',
 'LIG1',
 'LIG3',
 'LILRA5',
 'LILRA6',
 'LINC00473',
 'LIPA',
 'LIPB',
 'LIPH',
 'LMO4',
 'LPL',
 'LRP1',
 'LRP4',
 'LRRC51',
 'LRRN1',
 'LSS',
 'LST1',
 'LTBP2',
 'LTBP3',
 'LY6G6D',
 'LY75',
 'MADD',
 'MAFA',
 'MAG',
 'MAGEA2',
 'MAGEA4',
 'MAGEA6',
 'MAGEE1',
 'MAGI1',
 'MAGOH',
 'MAK',
 'MAML2',
 'MAP1A',
 'MAP2',
 'MAS1',
 'MAST1',
 'MBP',
 'MCM2',
 'ME1',
 'ME2',
 'ME3',
 'MED1',
 'MED24',
 'MED25',
 'MEIS3',
 'MET',
 'MGA',
 'MGAT1',
 'MGAT2',
 'MGAT3',
 'MID1',
 'MIF',
 'MIP',
 'MLC1',
 'MLN',
 'MLX',
 'MMAA',
 'MME',
 'MMP20',
 'MMP21',
 'MMP23A',
 'MMP25',
 'MOS',
 'MPI',
 'MPP1',
 'MPP2',
 'MPP4',
 'MPP7',
 'MR1',
 'MST1',
 'MTCP1',
 'MTF1',
 'MTHFS',
 'MTMR8',
 'MTTP',
 'MUC3A',
 'MYH14',
 'MYO1C',
 'MYPOP',
 'MYT1',
 'MYZAP',
 'NAT1',
 'NAT2',
 'NBN',
 'ND1',
 'NEK8',
 'NEU1',
 'NFIC',
 'NGB',
 'NIPA2',
 'NLK',
 'NMB',
 'NME1',
 'NMI',
 'NOP9',
 'NOS1',
 'NOS2',
 'NOS3',
 'NOTCH2NLA',
 'NPR2',
 'NPR3',
 'NPY4R',
 'NRF1',
 'NRP1',
 'NRP2',
 'NT5C1B',
 'NTN4',
 'NTNG1',
 'NUS1',
 'OCM',
 'ODC1',
 'OPA1',
 'OPN1MW',
 'OR11H12',
 'OR1D4',
 'OR1K1',
 'OR2A7',
 'OR2T29',
 'OR3A5P',
 'OR4F5',
 'OR4M2',
 'OR52I1',
 'OR9G1',
 'ORC1',
 'OSM',
 'OSR1',
 'P2RX5',
 'P2RY11',
 'PAF1',
 'PAK1',
 'PAK2',
 'PAK3',
 'PAK5',
 'PAM',
 'PAN2',
 'PAN3',
 'PASK',
 'PBX2',
 'PC',
 'PCDH19',
 'PCM1',
 'PDC',
 'PDE4DIP',
 'PDF',
 'PDK1',
 'PDP1',
 'PDX1',
 'PEMT',
 'PER1',
 'PEX1',
 'PGAM1',
 'PGD',
 'PGK2',
 'PGP',
 'PHF2',
 'PIGF',
 'PIK3CD',
 'PIM1',
 'PIN1',
 'PIP',
 'PISD',
 'PKD2',
 'PLD1',
 'PLSCR3',
 'PMF1',
 'PMP22',
 'PNMT',
 'PNP',
 'POGZ',
 'POLB',
 'POLG',
 'POLH',
 'POLK',
 'POLQ',
 'POLR1C',
 'POP1',
 'POR',
 'POU5F1',
 'PPAT',
 'PPOX',
 'PRDX6',
 'PREP',
 'PRF1',
 'PRG2',
 'PRG4',
 'PRH1',
 'PRH2',
 'PRKACA',
 'PRMT9',
 'PRODH2',
 'PRPS1',
 'PRR4',
 'PRSS1',
 'PRX',
 'PSAP',
 'PSG1',
 'PTH',
 'PTH2',
 'PTMA',
 'PTPA',
 'PTPN20CP',
 'PTPRO',
 'PTPRQ',
 'PTX3',
 'PVALB',
 'RAC1',
 'RAC3',
 'RAD1',
 'RAD54L',
 'RAET1L',
 'RAF1',
 'RALBP1',
 'RASA1',
 'RAX',
 'RBAK',
 'RBM14',
 'RBP1',
 'RBP2',
 'RBP3',
 'RBP4',
 'RBP5',
 'RCN3',
 'REN',
 'RFC1',
 'RFT1',
 'RGR',
 'RGS13',
 'RGS9',
 'RHEB',
 'RHO',
 'RNASE4',
 'RNASE9',
 'RNASEH1',
 'ROR1',
 'RPA1',
 'RPA2',
 'RPL10',
 'RPL13',
 'RPL17',
 'RPL23',
 'RPL24',
 'RPL36A',
 'RPL7A',
 'RPN1',
 'RPN2',
 'RPS12',
 'RPS18',
 'RPS26',
 'RS1',
 'RUFY3',
 'S100A16',
 'SAA1',
 'SAA2',
 'SAG',
 'SAP130',
 'SAT1',
 'SAT2',
 'SCAP',
 'SCD',
 'SCG2',
 'SCG3',
 'SCGB1C1',
 'SCP2',
 'SCT',
 'SCYL1',
 'SCYL2',
 'SCYL3',
 'SDHC',
 'SDS',
 'SELP',
 'SENP2',
 'SERPINA11',
 'SERPINB11',
 'SF1',
 'SF3B1',
 'SFN',
 'SFPQ',
 'SGK2',
 'SI',
 'SKI',
 'SKP2',
 'SLC17A2',
 'SLC23A1',
 'SLC23A2',
 'SLC24A2',
 'SLC4A5',
 'SLC9A6',
 'SLIT1',
 'SLIT3',
 'SLK',
 'SMAD1',
 'SMO',
 'SMS',
 'SOD2',
 'SP1',
 'SP110',
 'SP5',
 'SPAG11A',
 'SPEN',
 'SPINT3',
 'SPN',
 'SPP1',
 'SPP2',
 'SPR',
 'SRA1',
 'SRGAP3',
 'SRM',
 'STAR',
 'STK3',
 'STN1',
 'STRAP',
 'SULT1A3',
 'SULT1C2',
 'SUMO3',
 'TAAR2',
 'TAF4B',
 'TAP1',
 'TAP2',
 'TAT',
 'TCEA1',
 'TCF3',
 'TCF4',
 'TEP1',
 'TF',
 'TGM6',
 'TGS1',
 'TK2',
 'TKT',
 'TMED10',
 'TMEM123',
 'TNC',
 'TNFRSF11B',
 'TNNC1',
 'TNNI3K',
 'TPH2',
 'TPO',
 'TPP1',
 'TPSB2',
 'TRA',
 'TRAC',
 'TRAF2',
 'TRAP1',
 'TRB',
 'TRGC1',
 'TRIM34',
 'TRIM49B',
 'TRIM49D2',
 'TRMT1',
 'TRNP1',
 'TRPC7',
 'TRPM2',
 'TRX-CAT1-2',
 'TSSK1B',
 'TSSK4',
 'TST',
 'TTF1',
 'TTF2',
 'TTL',
 'TTN',
 'TUBB',
 'TUBB1',
 'TXN',
 'TYMP',
 'UBC',
 'UCN2',
 'UGT1A',
 'UGT2B11',
 'USP10',
 'USP12',
 'USP16',
 'USP17L10',
 'USP21',
 'USP31',
 'VARS2',
 'VAT1',
 'VDAC3',
 'VDR',
 'VIP',
 'WBP1',
 'WDR11',
 'XBP1',
 'XDH',
 'ZBP1',
 'ZNF322',
 'ZP1',
 'ZSCAN31'}

In [47]:
dgidb_genes_df[dgidb_genes_df["gene_name"].isin(ambig_symbol_set)]

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
45,PTX3,Gene Symbol,hgnc:9692,PTX3,HGNC,20260619
46,PTX3,Gene Symbol,hgnc:9692,PTX3,NCBI,20260622
61,TRAC,Gene Symbol,hgnc:12029,TRAC,HGNC,20260619
62,TRAC,Gene Symbol,hgnc:12029,TRAC,Ensembl,116
63,TRAC,Gene Symbol,hgnc:12029,TRAC,NCBI,20260622
...,...,...,...,...,...,...
77428,CPS1,Gene Symbol,hgnc:2323,CPS1,FoundationOneGenes,2020-09-03
77429,HK1,Gene Name,hgnc:4922,HK1,NCI,14-September-2017
77438,BRIP1,Gene Symbol,hgnc:20473,BRIP1,FoundationOneGenes,2020-09-03
77443,SOD2,Gene Name,hgnc:11180,SOD2,NCI,14-September-2017
77479,G6PD,Gene Name,hgnc:4057,G6PD,DTC,2020-09-02